### ISSUE TITLE
InstrumentHandler should expose a gauge "requests in flight"

### ISSUE THREAD

**Issue by neelance** [prometheus/client_golang#101]
It would be great if `InstrumentHandler` could not only track completed requests by `http_requests_total`, but also have a metric of how many requests were received, e.g. `http_requests_received`. Then one could calculate `http_requests_received - http_requests_total` to get the number of concurrent requests that have not been processed yet.

**Comment by brian-brazil** [comment]
That'd be better done as a gauge. Direct arithmetic on counters can break in a number of fun ways such as resets and race conditions, and is to be avoided.

**Comment by neelance** [comment]
Okay, whatever you think is best. :-)

**Comment by beorn7** [comment]
Changed the title accordingly.

**Comment by beorn7** [comment]
Since `InstrumentHandler` is deprecated, this will be implemented as a middleware in the new `promhttp` package.
