### ISSUE TITLE
How to parse the query result, it seems like only provides Type and String

### ISSUE THREAD

**Issue by wmf508** [prometheus/client_golang#1011]
I want to iterator result from query, but it's a string, so, i need to handle it by myself?

 `result, warnings, err := cli.api.Query(context.TODO(), "kube_node_status_condition{condition=\"Ready\"}", time.Now())
	if warnings != nil {
		log.Printf("warning: %v", warnings)
	}

	if err != nil {
		log.Printf("warning: %v", err)
	}

	log.Printf("result: %v", result)`

**Comment by prymitive** [comment]
You need to cast `result` to `model.Vector` (https://pkg.go.dev/github.com/prometheus/common/model#Vector) for instant queries or `model.Matrix` (https://pkg.go.dev/github.com/prometheus/common/model#Matrix) for range queries.

```
result, warnings, err := cli.api.Query(...)
for _, sample := range result.(model.Vector) {
  ...
}
```
