### ISSUE TITLE
missing requirement to go >= 1.3

### ISSUE THREAD

**Issue by dachary** [prometheus/client_golang#102]
<pre>
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
$ go version
go version go1.2.1 linux/amd64
$ go get github.com/prometheus/client_golang
/home/tmp/src/github.com/prometheus/client_golang/model/signature.go:32: undefined: sync.Pool
</pre>
 looks like sync.Pool was added in Go1.3, https://golang.org/doc/go1.3

**Comment by juliusv** [comment]
Yup - what would you concretely like to see here? Something in the README.md stating the required Go version?

**Comment by juliusv** [comment]
Ah, I see that this is affecting `github.com/hashicorp/raft` via `github.com/armon/go-metrics`.

Hm, what should one do in such a situation? Abstaining from using any reasonably modern Go features like `sync.Pool` sounds suboptimal (it came out in 1.3, now there's Go version 1.4.2).

A possibility would be to put metric sinks like https://github.com/armon/go-metrics/blob/master/prometheus.go into their own subpackage within `go-metrics`, so it wouldn't be necessary to fetch&build all possible output metric systems when using `go-metrics`. @armon, what do you think? Of course, that would require users of the library to update their code.

**Comment by dachary** [comment]
@juliusv is it possible to add a version constraint to client_golang ? Something that **go get -d** would check ?

**Comment by juliusv** [comment]
@dachary I thought it wasn't possible, but it actually is possible via build tags (http://golang.org/pkg/go/build/)!

I filed a PR against `go-metrics`: https://github.com/armon/go-metrics/pull/11

This approach lets the using library say that there is a version constraint. There would also be the possibility to do a build switch inside the Prometheus client library to conditionally build code using `sync.Pool` vs. some manual pool implementation. I wouldn't do that quite yet, but if it becomes necessary, that should be possible. Then again, I expect fewer and fewer people to be on Go <1.3 the more time passes, so this will probably become moot by itself...

**Comment by juliusv** [comment]
Fixed by version constraint in `go-metrics`
