### ISSUE TITLE
Extensions need more exemplar support

### ISSUE THREAD

**Issue by MikeSpreitzer** [prometheus/client_golang#1024]
I am working on some histogram extensions in https://github.com/kubernetes/kubernetes/pull/109277 , and have run into a couple of blockages regarding examplars.

(1) constHistogram (https://github.com/prometheus/client_golang/blob/29e8191aff2174cb56888658b4afd6a7940a9b3e/prometheus/histogram.go#L570) does not support exemplars.

(2) once it does, I may need to call the private function `newExemplar` (like histogram::updateExemplar does).

**Comment by bwplotka** [comment]
Thanks for this report, but I think it's already implemented. Merged recently with https://github.com/prometheus/client_golang/pull/986

See how to use it here: https://github.com/prometheus/client_golang/blob/main/prometheus/examples_test.go#L601

I will close it for now, but feel free to comment if you think it's should be reopened (something is missing?). Cheers!

**Comment by MikeSpreitzer** [comment]
Thanks.
Now I need this to appear in a release.
