### ISSUE TITLE
New GoCollector metrics in 1.12 do not pass `promtool check metrics` lint

### ISSUE THREAD

**Issue by chancez** [prometheus/client_golang#1026]
Using git tag  v1.12.1, if we run `promtool check metrics` on our metrics we get the following failure:

```
go_gc_heap_allocs_by_size_bytes_total non-counter metrics should not have "_total" suffix
go_gc_heap_frees_by_size_bytes_total non-counter metrics should not have "_total" suffix
go_gc_pauses_seconds_total non-counter metrics should not have "_total" suffix
```

It seems that new metrics were potentially introduced in https://github.com/prometheus/client_golang/pull/955

I also filed https://github.com/prometheus/prometheus/issues/10574 before realizing these are new metrics as part of a library upgrade, though it still seems useful in general.

**Comment by bwplotka** [comment]
Hmm, those are indeed histogram metrics, which are derived from `runtime/metrics` - thanks for pointing.

I would really consider renaming it now, given it's a fresh change (but this will break some compatibility though). Let me look on it.
