### ISSUE TITLE
API Tests do not appear to verify request parameters

### ISSUE THREAD

**Issue by josephwoodward** [prometheus/client_golang#1034]
Whilst working on [updating the Query API to support timeouts](https://github.com/prometheus/client_golang/pull/1014) I noticed that the API tests [do not currently verify the request parameters](https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api_test.go#L69-L92) against the `reqParam` type [configured as part of the test](https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api_test.go#L260-L264).

This can be verified by deleting all the request parameters within Query (for instance) and the tests will continue to pass.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1237341/164562633-16767a8b-ce7f-4cf2-9682-0e5b0469d5c6.png">

I'm happy to raise a PR to address this.

**Comment by kakkoyun** [comment]
Feel free to address it. Anything improves the quality assurance is much appreciated :)

**Comment by JosephWoodward** [comment]
@kakkoyun I've made a start on ensuring the tests cover the request parameters [here](https://github.com/prometheus/client_golang/pull/1047).

**Comment by josephwoodward** [comment]
This can be closed as it's been [merged](https://github.com/prometheus/client_golang/pull/1047).
