### ISSUE TITLE
API: Add documentation for API config options

### ISSUE THREAD

**Issue by kakkoyun** [prometheus/client_golang#1036]
At first glance I thought this would set the context timeout. I think there should at least be a documentation comment saying what the intended behaviour is.

_Originally posted by @bboreham in https://github.com/prometheus/client_golang/issues/1014#issuecomment-1107807524_

**Comment by JosephWoodward** [comment]
@kakkoyun Feel free to assign this one to me, I missed the docs on my previous PR.
