### ISSUE TITLE
Pushgateway support JWT Auth

### ISSUE THREAD

**Issue by totorolee** [prometheus/client_golang#1065]
Pushgateway supports basic auth, it's good but not enough. JWT is in common use when authenticating, I thought it should be added as the auth feature. If pleasure, I could implement it.

**Comment by songjiayang** [comment]
hi @beorn7 , Can you help to look at this issue?

In our use case, some users want push metrics  to vendor directly like a cortex,  JWT Auth sometimes easier to manage.

**Comment by beorn7** [comment]
I don't think it's feasible to implement all auth methods explicitly in the `push` package (as it was done for basic auth).

Instead, we need to give the user access to the necessary knobs of the Go `net.http` package to manage the auth method of their choice.

Note that you can already set a custom [`http.Client`](https://pkg.go.dev/net/http#Client) via the [`Pusher.Client` method](https://pkg.go.dev/github.com/prometheus/client_golang@v1.14.0/prometheus/push#Pusher.Client). This might already enable you to support the auth method of your choice.

If you need anything else exposed, please provide a code example, and we can find a solution.

**Comment by songjiayang** [comment]
hi @beorn7 , thanks for your replay.

Although using [Pusher.Client method](https://pkg.go.dev/github.com/prometheus/client_golang@v1.14.0/prometheus/push#Pusher.Client) will work, but we need to implement a very similar interface, some codes like:

``` go
type JwtHttpDoer struct {
	jwtToken string
	client   *http.Client
}

func NewJwtHttpDoer(token string) *JwtHttpDoer {
	return &JwtHttpDoer{
		jwtToken: token,
		client:   &http.Client{},
	}
}

func (d *JwtHttpDoer) Do(req *http.Request) (*http.Response, error) {
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", d.jwtToken))
	return d.client.Do(req)
}
```

If add  a `(p *Pusher) bearerAuth(token string) ` to `Pusher` like BasicAuth, this will help user to use.

**Comment by beorn7** [comment]
Thanks @songjiayang . I think that code doesn't look to bad. If there aren't a lot of people needing the same feature, it seems acceptable to me. It's essentially a trade-off how many users will have to write this additional code vs. how many users will waste brain cycles thinking about that additional method that they might not need.

But maybe the sweet spot is somewhere in the middle. How about adding a `Pusher.Header` method to add an HTTP header? That would make your use case almost as easy as the proposed `Pusher.BearerToken` method, but it would support other use cases that need to set custom headers, too.

**Comment by songjiayang** [comment]
I really like `Pusher.Header` way, It can solve solve the jwt authentication problem and allow users to inject custom header.

**Comment by beorn7** [comment]
Yes, let's do it. Looking forward to your PR. It should be straight forward. Thank you.

**Comment by songjiayang** [comment]
hi @beorn7 , I add the `Header` method to `Pusher`，code review please.
