### ISSUE TITLE
Add option to control Go metrics in the default collector.

### ISSUE THREAD

**Issue by SuperQ** [prometheus/client_golang#1089]
With client_golang v1.12.2, [we removed the `runtime/metrics` from the default collector](https://github.com/prometheus/client_golang/pull/1033).

But now it seems difficult to get these metrics back without having to abandon the default registry. This makes the use of `promauto` more cumbersome.

Some ideas:
* Add a default registry method to adjust what metrics features are enabled at build time/runtime.
* Add some filtering methods so that only specific sets of `runtime/metrics` are included.

For example, of the new metrics I only need `/sched/latencies:seconds` right now.

**Comment by bwplotka** [comment]
It is indeed unfortunate we cannot change the default registry Go collector to new metrics as registering another GoCollector would register base metrics. It's relatively easy to change it, but not sure it's worth it. We generally want to deprecate global registry (my opinion).

`promauto` is quite nice with custom registry. Just use `promauto.With(reg).New....`. I don't think 9 more characters are more `cumbersome` 🙈 This is what we use everywhere and recommend (probably we might want to update docs).

You are right that some filtering might be amazing. Perhaps it could solve GoCollector on the default register. I think it's worth considering. 

### Open Questions

* Should we filter based on core runtime metric name like `/shed/latencies:second` or resulted Prometheus-like metric names?
* Should we filter on Go collector level or on registered level? (would allow doing this for any collector in the registry).

**Comment by SuperQ** [comment]
I all I really want to do is be able to toggle or update the filter on the GoCollector.

**Comment by bwplotka** [comment]
Let us know if that (https://github.com/prometheus/client_golang/pull/1102) will satisfy you @SuperQ  - I will add more details, even how to add it to defaultRegistry
