### ISSUE TITLE
Missing way to define ConstLabels and Subsystem for ProcessCollector

### ISSUE THREAD

**Issue by piotrkowalczuk** [prometheus/client_golang#109]
I would like to track process stats per machine. Currently I am forced  to rewrite entire [ProcessCollector](https://godoc.org/github.com/prometheus/client_golang/prometheus#NewProcessCollector) logic.

Dedicated ProcessCollector options would be enough imo.
```
type ProcessCollectorOpts struct {
    PID int
    Namespace string
    Subsystem string
    ConstLabels Labels
}
```

**Comment by brian-brazil** [comment]
The existing namespace parameter should cover you for the subsystem.

What do you mean by tracking stats by machine? The metrics will gain an instance label when prometheus scrapes them.

**Comment by piotrkowalczuk** [comment]
Instance label is `host:port` but in my case i identify them by name.

**Comment by brian-brazil** [comment]
That'll come out as part of the service discovery work, as instance label and host:port to connect to will be separated out. @fabxc 

Adding labels to all metrics in all libraries you might want to use to support this use case isn't scalable (though there are use cases for adding labels to the process collector in particular, for when there's multiple pids you're monitoring such as HAProxy multi-process).

**Comment by fabxc** [comment]
Depends on the SD and its configuration - defaulting to `host:port` will make sense though.

**Comment by beorn7** [comment]
@fabxc Is this dealt with by the SD code on the server?

**Comment by beorn7** [comment]
After talking to @fabxc in person, with the new features around SD and the various relabeling steps on the server, you should be able to achieve all of the above on the server side.
