### ISSUE TITLE
Yaml V2 Vulnerability

### ISSUE THREAD

**Issue by reachlakstar** [prometheus/client_golang#1114]
FORTIFY is throwing Yaml V2 vulnerabilities, could you please migrate to new versions

**Comment by reachlakstar** [comment]
github.com/prometheus/common is using lower version

**Comment by kakkoyun** [comment]
Could you please point give references to vulnerabilities? We can check if the yaml v2 has the security patches we've missed.

Please keep in mind that, certain security scanners raise blanket issues as soon as they see a dependency. We need to check if we're affected.
