### ISSUE TITLE
How to avoid duplicate metrics collector registration attempted in parallel tests

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/client_golang#1140]
The code below panics for duplicate registration because by default golang runs tests in parallel.
The actual code would work since `New()` is called only once so wondering if there could be any workaround that can use for the testing.
I really want to avoid having to use a custom register. 

```
type TT struct {
	a prometheus.Gauge
}

func New() *TT {
	return &TT{
		a: promauto.NewGauge(prometheus.GaugeOpts{
			Namespace: "a",
			Subsystem: "a",
			Name:      "a",
			Help:      "a",
		}),
	}
}

func Test1(t *testing.T) {
	New()
}
func Test2(t *testing.T) {
	New()
}
```

**Comment by kakkoyun** [comment]
@krasi-georgiev By default, `promauto` uses the default registry and it's a package global. I would suggest you to create a new registry for each test cases.

```
type TT struct {
	a prometheus.Gauge
}

func New() *TT {
	reg := prometheus.NewRegistry()
	return &TT{
		a: promauto.With(reg).NewGauge(prometheus.GaugeOpts{
			Namespace: "a",
			Subsystem: "a",
			Name:      "a",
			Help:      "a",
		}),
	}
}

func Test1(t *testing.T) {
	New()
}
func Test2(t *testing.T) {
	New()
}
```
