### ISSUE TITLE
Exemplar for `+Inf` bucket adds bucket with wrong value

### ISSUE THREAD

**Issue by balintzs** [prometheus/client_golang#1147]
When writing histogram metrics, and there is an exemplar for the `+Inf` bucket, then the `+Inf` bucket is added with the value of the previous bucket:
https://github.com/prometheus/client_golang/blob/main/prometheus/metric.go#L188

This is incorrect, as the cumulative count of the `+Inf` bucket should instead be added with the total count of the histogram datapoint.

The above behaviour results in invalid values being reported for the `+Inf` bucket.

**Comment by balintzs** [comment]
I'll open a PR shortly

**Comment by bwplotka** [comment]
Thanks! Approved fix with some small nit.

**Comment by balintzs** [comment]
Thanks for merging it, @bwplotka. When can we expect it to get released?

**Comment by bwplotka** [comment]
Can you just use commit sha for now? We will release soon, but don't know when (KubeCom + PromCon is coming)

**Comment by bboreham** [comment]
Note your link to the problem now shows the fixed code, because it references `main`.
You can get a fixed link by pressing 'Y' in the GitHub UI, e.g.:
https://github.com/prometheus/client_golang/blob/3faf3bae7076031e56adc1f76d0c2d817410597e/prometheus/metric.go#L188-L190
