### ISSUE TITLE
AddWithExemplar uses argument provided for exemplar value instead of counter's value

### ISSUE THREAD

**Issue by chancez** [prometheus/client_golang#1149]
Currently [`AddWithExemplar`](https://github.com/prometheus/client_golang/blob/a528affed905f64ed33ed2f52b7880ed7247f99e/prometheus/counter.go#L127-L130) uses the argument provided to set the value of the exemplar, not the counter's value.

If you are using `AddWithExemplar` as an alternative to `.Inc()`, the value you would be using is probably `1`, meaning your exemplars are always `1`. 

I wonder, should this method be using the value of the counter, or at least, should there be another method to use the counter's value instead of the value provided? Perhaps there should be a  `IncrementWithExemplar` method and an `type ExemplarIncrementer interface`?

**Comment by bwplotka** [comment]
Yea, there is a bug here, thanks for noticing!

**Comment by bwplotka** [comment]
So I think it works as expected, feel free to comment if you don't think so, I will reopen.

**Comment by chancez** [comment]
> So I think it works as expected, feel free to comment if you don't think so, I will reopen.

Does it make sense to have an option to use the value of the counter?
