### ISSUE TITLE
go get github.com/prometheus/client_golang/prometheus@v1.12.2 gives 503 service unavailable error

### ISSUE THREAD

**Issue by itisbsg** [prometheus/client_golang#1156]
Go Version: 
go version go1.14.13 darwin/amd64
 
Error Message seen is:
go get github.com/prometheus/client_golang/prometheus@v1.12.2
go get github.com/prometheus/client_golang/prometheus@v1.12.2: github.com/prometheus/client_golang/prometheus@v1.12.2: reading https://gonexus.dev/github.com/prometheus/client_golang/prometheus/@v/v1.12.2.info: 503 Service Unavailable

**Comment by kakkoyun** [comment]
@itisbsg Could you please check your local environment settings? It seems like you are using a Go module proxy https://gonexus.dev/ and that proxy somehow doesn't work correctly.
