### ISSUE TITLE
Allow creating summaries without quantiles

### ISSUE THREAD

**Issue by juliusv** [prometheus/client_golang#118]
From reading the code, it seems like it's not possible to create summaries without any quantiles at the moment:

https://github.com/prometheus/client_golang/blob/master/prometheus/summary.go#L183-L185

If that `len(...) == 0` check was changed to a `... == nil`, then I guess it should work (one would then be able to pass in an empty, but constructed slice of objectives).

The same is true for histograms (although a summary/histogram without quantiles/buckets would behave identically to each other):

https://github.com/prometheus/client_golang/blob/master/prometheus/histogram.go#L184-L186

**Comment by beorn7** [comment]
Yeah, should be possible. For both cases, I guess.
