### ISSUE TITLE
How to add a value to MustNewConstMetric

### ISSUE THREAD

**Issue by yiqinguo** [prometheus/client_golang#1192]
```
prometheus.NewMetricWithTimestamp(t, prometheus.MustNewConstMetric(c.metric, prometheus.CounterValue, 123, "2"))
 ```

When I use this method to set the metrics, the value is always 123 and cannot be incremented from the original value.

**Comment by rogerogers** [comment]
This cannot be changed

**Comment by bboreham** [comment]
As the documentation says, "NewConstMetric returns a metric with one fixed value that cannot be changed."
It also says "Users of this package will not have much use for it in regular operations.", which is a gentle way to say "don't use this".

Suggest you look through the [examples](https://github.com/prometheus/client_golang/blob/27f0506d6ebbb117b6b697d0552ee5be2502c5f2/prometheus/examples_test.go) and see if there is something more suitable for what you want to do.
