### ISSUE TITLE
Rename `process_goroutines` to `go_goroutines`.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#121]
`process_goroutines` is a Go specific metrics. It should probably be renamed to `go_goroutines` in https://github.com/prometheus/client_golang/blob/master/prometheus/go_collector.go#L19 to match `go_gc_duration_seconds`.

**Comment by juliusv** [comment]
Noticed this already. :+1: - strictly speaking this will be a backwards-incompatible breakage, but it seems worth it.

**Comment by grobie** [comment]
:+1:
