### ISSUE TITLE
Bump x/net, prometheus/common deps to avoid GO-2023-1495 and GO-2022-1144 govuln warnings

### ISSUE THREAD

**Issue by xxgreg** [prometheus/client_golang#1216]
I've started using govulncheck in my project and I'm getting warnings due to the following dependency chain:

github.com/prometheus/client_golang v1.14.0
github.com/prometheus/common v0.37.0
golang.org/x/net/http2@v0.0.0-20221012135044-0b7e1fb9d458

It looks like there's a newer version of prometheus/common which has bumped the x/net dependency. I 
assume the fix is for prometheus/client_golang to bump the prometheus/common dep.

```
Vulnerability #1: GO-2023-1495
  A request smuggling attack is possible when using
  MaxBytesHandler. When using MaxBytesHandler, the body of an HTTP
  request is not fully consumed. When the server attempts to read
  HTTP2 frames from the connection, it will instead be reading the
  body of the HTTP request, which could be attacker-manipulated to
  represent arbitrary HTTP2 requests.

  Call stacks in your code:
      <snip> calls github.com/uber-go/tally/v4/prometheus.Configuration.NewReporter, which eventually calls golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP

  Found in: golang.org/x/net/http2/h2c@v0.0.0-20221012135044-0b7e1fb9d458
  Fixed in: golang.org/x/net/http2/h2c@v0.1.1-0.20221104162952-702349b0e862
  More info: https://pkg.go.dev/vuln/GO-2023-1495

Vulnerability #2: GO-2022-1144
  An attacker can cause excessive memory growth in a Go server
  accepting HTTP/2 requests. HTTP/2 server connections contain a
  cache of HTTP header keys sent by the client. While the total
  number of entries in this cache is capped, an attacker sending
  very large keys can cause the server to allocate approximately
  64 MiB per open connection.

  Call stacks in your code:
      <snip> calls github.com/uber-go/tally/v4/prometheus.Configuration.NewReporter, which eventually calls golang.org/x/net/http2.Server.ServeConn

  Found in: golang.org/x/net/http2@v0.0.0-20221012135044-0b7e1fb9d458
  Fixed in: golang.org/x/net/http2@v0.4.0
  More info: https://pkg.go.dev/vuln/GO-2022-1144
```

**Comment by cmur2** [comment]
This is bothering me as well, is it possible to release an update?

**Comment by foosinn** [comment]
Also popped up for my projects

**Comment by beorn7** [comment]
Dependencies are regularly updated in the main branch (and in fact, github.com/prometheus/common has been updated multiple times). Any new release cut will include those updates (and you are free to build from the head of the main branch yourself, of course).

We would only cut a bugfix release for those if they actually affect prometheus/client_golang. I doubt that any of the vulnerable code is actually called through anything in prometheus/client_golang, but we would love to hear if that assessment is wrong (in which case a bugfix release should be cut).
