### ISSUE TITLE
Release without deprecated github.com/golang/protobuf package needed

### ISSUE THREAD

**Issue by 0xccccccccBadPtr** [prometheus/client_golang#1241]
Deprecated package `github.com/golang/protobuf` was already replaced by `google.golang.org/protobuf/proto` with #1183 
  
Would it be possible to release a version containing this change?

**Comment by bwplotka** [comment]
Yup, we are on it. Should be this week, thanks for ping! Next time, feel free to our our slack mentioned in [the README](https://github.com/prometheus/client_golang#prometheus-go-client-library)
