### ISSUE TITLE
api: Execution order on multiple return variables with multiple vars is unspecified (and does not work with gogc)

### ISSUE THREAD

**Issue by go101** [prometheus/client_golang#1259]
https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api.go#L894-L895

More details: https://github.com/golang/go/issues/58233#issuecomment-1499471060

**Comment by bwplotka** [comment]
Wow, first time I saw this being an issue, thanks for reporting. Help wanted to fix it.
