### ISSUE TITLE
Golang version specified in Readme.md is not align with go.mod golang version

### ISSUE THREAD

**Issue by ukumar009** [prometheus/client_golang#1273]
The Golang version specified in Readme.md file is 1.18 or later: https://github.com/prometheus/client_golang/blob/main/README.md?plain=1#L13

Whereas the Golang version used in go.mod file is 1.17: https://github.com/prometheus/client_golang/blob/main/go.mod#L3

**Comment by beorn7** [comment]
I guess it would be less confusing to update the `go` directive in `go.mod`. But note that the `go` directive in `go.mod` does not prevent older Go compilers from compiling the code (or at least attempting to do so).

Note that the current code of client_golang compiles and tests just fine with Go1.17. It's therefore technically correct to leave the `go` directive at 1.17.

See also https://go.dev/ref/mod#go-mod-file-go

**Comment by kakkoyun** [comment]
Exactly as @beorn7 stated, we are only committed to supporting the latest three major versions.
Just so you know- I have updated the README in #1325 accordingly.

> The library mandates the use of Go1.19 or subsequent versions. While it has demonstrated functionality with versions as old as Go 1.17, our commitment remains to offer support and rectifications for only the most recent three major releases.
