### ISSUE TITLE
constrainLabels allocates too many memory

### ISSUE THREAD

**Issue by khasanovbi** [prometheus/client_golang#1276]
Hi, in my application prometheus allocates a lot of memory in constrainLabels.
I suggest replacing labels inplace instead of creating a new map.
![image](https://github.com/prometheus/client_golang/assets/8990821/7d131cbf-1821-491b-b29b-7bb5935c9824)

**Comment by khasanovbi** [comment]
Related PR https://github.com/prometheus/client_golang/pull/1272

**Comment by bwplotka** [comment]
Yes, and not I realized it's for very rare feature (new one). Your PR optimizes it well (https://github.com/prometheus/client_golang/pull/1272), but we should likely have a quick path for metrics without constrains. Leaving that open for community to help here 🤗
