### ISSUE TITLE
Feature Request: instrument http client connection metrics

### ISSUE THREAD

**Issue by proost** [prometheus/client_golang#1312]
Hi!

Adding http client connection metrics like whether put idle connection to connection pool success or fail, connection is from connection pool or created, dialing new connections is success or failed is more helpful to http client.

If use [ `httptrace`](https://pkg.go.dev/net/http/httptrace), it can be achieved. 

These metrics can help me in this way connection pool is large enough, there is something wrong to connection pool such as stale connection, what & when is wrong when create new connection. There metrics can give you clue about health of  HTTP connection and HTTP connection pool.

**Comment by agebhar1** [comment]
Does this help you? https://github.com/prometheus/client_golang/blob/920e6f73cc9fe9c2226a4cd6a02097b1305e8f8d/prometheus/promhttp/instrument_client.go#L152-L165
