### ISSUE TITLE
Add `/godebug/non-default-behavior/*` metrics to go collector

### ISSUE THREAD

**Issue by MadhavJivrajani** [prometheus/client_golang#1337]
Hi all, greetings from the Kubernetes community 👋🏼 

Recently, as part of go1.21's [extended backwards compatibility changes](https://go.dev/blog/compat), the [`runtime/metrics`](https://pkg.go.dev/runtime/metrics) packages [exposes metrics](https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics) on the usage of codepaths that depend on non-default values of `GODEBUG` settings (see metrics of the form `/godebug/non-default-behavior/*`).

These metrics, IMO, are an excellent addition complementing the new minimum 2 year period of `GODEBUG` settings, and can help give users confidence in moving away from non-default `GODEBUG` settings eventually based on these metrics.

I'd like to work on adding support for this in the go collector so that `client_golang` can be used to expose these metrics in consumers of it, like Kubernetes.

In the past, we've added custom metrics in Kubernetes for tracking usage of these non-default `GODEBUG` settings: https://github.com/kubernetes/kubernetes/pull/109024

If and when incidences like these happen again, we can just rely on the metrics exposed by Go to provide a better signal.

Please lmk what your thoughts on this are, or if there's something else I should do before starting a discussion here.

Thanks!

cc @dgrisonnet

**Comment by MadhavJivrajani** [comment]
Ah, I see the `AllMetrics` rule.
Then I think it might be worth adding in a rule for `MetricsGodebug`.

**Comment by bwplotka** [comment]
Nice, assuming it can be closed now then 🤗
