### ISSUE TITLE
Add duration to the model

### ISSUE THREAD

**Issue by fabxc** [prometheus/client_golang#134]
Just as time, our custom duration format should also be in the model. Especially for its parsing and marshalling functionality.

We should drop `y` and `w` as suffixes. They are rarely used and ambiguous. `d` is a unit sufficient to express long time intervals, i.e. everybody has a good notion of what 7, 14, 90, or 360 days are.

**Comment by beorn7** [comment]
That's done in https://github.com/prometheus/common/blob/master/model/time.go#L164. Please re-open if I'm mistaken.
