### ISSUE TITLE
Expose interface for serving metrics

### ISSUE THREAD

**Issue by fabxc** [prometheus/client_golang#136]
We need functionality to make allow simple serving of metrics via HTTP handlers that hides details such as content type negotiation, buffering, sorting, etc.

**Comment by beorn7** [comment]
But that's what `client_golang/prometheus` is all about. What are you missing?

**Comment by fabxc** [comment]
That's the stuff I did in `common/expfmt` – this came with implementing federation where there is currently some code duplication.

**Comment by beorn7** [comment]
I see... assigning to you so that you can close once that refactoring is in effect.

**Comment by beorn7** [comment]
I think this is done. Please re-open if I missed something.
