### ISSUE TITLE
Use of native histograms

### ISSUE THREAD

**Issue by MeAndMyTeam** [prometheus/client_golang#1363]
Hello,

i am trying to use the new native histograms and don't understand it fully. I wrote this simple example code and run it.
Version is github.com/prometheus/client_golang v1.17.0

```go
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func NewPrometheusMiddleware() func(http.Handler) http.Handler {

	httpResponseLatencies := prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			// As we read in die documentation: A generally good trade-off between cost and accuracy is a value of 1.1
			NativeHistogramBucketFactor: 1.1,
			// The max bucket number is highly recommended to set, so we just start with 100
			NativeHistogramMaxBucketNumber: 100,
			Name:                           "_http_latencies",
		},
		[]string{},
	)

	err := prometheus.Register(httpResponseLatencies)
	if registeredError, ok := err.(prometheus.AlreadyRegisteredError); ok {
		httpResponseLatencies = registeredError.ExistingCollector.(*prometheus.HistogramVec)
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			next.ServeHTTP(w, r)
			time.Sleep(100 * time.Millisecond)
			msElapsed := float64(time.Since(start).Milliseconds())

			httpResponseLatencies.WithLabelValues().Observe(msElapsed)
		})
	}
}

func main() {
	router := chi.NewMux()
	router.Use(NewPrometheusMiddleware())
	router.Get("/metrics", promhttp.Handler().ServeHTTP)
	log.Fatalln(http.ListenAndServe(":20000", router))
}
``` 
If i now call the /metrics endpoint twice, i got the _http_latencies metric, but it does look like the old histogram values with buckets?

```
# HELP _http_latencies 
# TYPE _http_latencies histogram
_http_latencies_bucket{test="123",le="+Inf"} 4
_http_latencies_sum{test="123"} 442
_http_latencies_count{test="123"} 4
```
What must i do to get the new native histogram values?

**Comment by bwplotka** [comment]
Hey, sparse/native histograms are only available via Prometheus proto exposition format. You can "ask" for it using content header "Accept" e.g. `curl -H 'Accept:application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited' <your server's /metrics path>` 

- it's protobuf so it won't be human readable without deserialization. However this will work well with Prometheus with Native histograms feature flag (:

**Comment by MeAndMyTeam** [comment]
@bwplotka Ok, i understand.
Then it was only my unknown, that everything is already there :-)
I just switched the flag for native histograms on my prometheus server and i got new labels like ymax, xmax, ylayout i not see before.

**Comment by bwplotka** [comment]
Nice epic! There is some room for better documentation I guess, but let's add another issue with specific ideas on how to improve docs if needed.
