### ISSUE TITLE
Circular dependency on prometheus/common

### ISSUE THREAD

**Issue by cornfeedhobo** [prometheus/client_golang#1381]
This repo pulls vulnerable dependencies. For example, [yaml.v2 <2.4.0](https://security.snyk.io/package/golang/github.com%2Fgo-yaml%2Fyaml)

I noticed this when a dependency of mine ended up pulling in [v1.11.1](https://github.com/prometheus/client_golang/tree/v1.11.1), which depends on [prometheus/common@v0.26.0](https://github.com/prometheus/common/tree/v0.26.0), which depends on [v1.7.1](https://github.com/prometheus/client_golang/tree/v1.7.1).

This circular dependency is causing a bunch of older dependencies to linger.

As far as I can tell, this is still happening right now on `main`.

**Comment by bwplotka** [comment]
Thanks for pointing! There was already an discussion about that in https://github.com/prometheus/common/issues/58 - circular dep is unlikely to change. I believe you should be able to pin yaml.v2 to version you want in your go mod file, is that right?

**Comment by bwplotka** [comment]
I don't believe client_golang itself use YAML for any logic itself.

**Comment by cornfeedhobo** [comment]
You can't pin it to a specific version because sum will always calculate the entire tree of hashes. The only way is for everyone that depends on this package to include a lot of `exclude` directives. The YAML package alone pulls like 8 flagged versions.

**Comment by bwplotka** [comment]
Thanks everyone! 💪🏽
