### ISSUE TITLE
Can you set an expiration time for the indicators written into/metrics

### ISSUE THREAD

**Issue by fenggolang** [prometheus/client_golang#1397]
I have an indicator that is updated every second, but after a period of time, the indicator runs out of data and will not be updated again. So how do I clean up these expired indicators written to the/metric interface (if the application does not restart, it will remain in memory)

**Comment by ArthurSens** [comment]
Have you tried using the [Delete](https://github.com/prometheus/client_golang/blob/38631c665bb77a984ea93eaee51af5b8c7ae52da/prometheus/vec.go#L95) method?

**Comment by bwplotka** [comment]
Or [reset](https://github.com/prometheus/client_golang/blob/38631c665bb77a984ea93eaee51af5b8c7ae52da/prometheus/vec.go#L130) (if you use `*Vec`) or Unregister if you want to get rid of the metric totally (and it's not a vector).

Closing for now, we can always reopen 🤗
