### ISSUE TITLE
Release v0.18.0？

### ISSUE THREAD

**Issue by Alfonsxh** [prometheus/client_golang#1415]

**Comment by Alfonsxh** [comment]
![image](https://github.com/prometheus/client_golang/assets/9427550/619dede8-f7a0-4c7b-81f2-113531df16f2)

**Comment by ArthurSens** [comment]
Hey, I'm not sure if I'm missing something here. Could you elaborate?

**Comment by ArthurSens** [comment]
Oooooooh okey I got it!

Release name fixed 😅

**Comment by bwplotka** [comment]
Thanks for pointing out @Alfonsxh 💪🏽
