### ISSUE TITLE
Expose timestamp interface for metrics

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/client_golang#143]
Prometheus's exposition format has an optional timestamp field which can be used to set the time a metric was collected (with some caveats as to the danger). This interface should be exposed by the client library so it can be set.

A classic use case is when a service might poll during the collection of the metric, but you want to prevent flooding by limiting the maximum poll rate to some value - in these cases, it would be desirable to send the exact time the metric was collected last while still serving the metric. This allows many scrapes, but only one poll of the underlying metric.

**Comment by beorn7** [comment]
In your use case, you would put the time stamp of last polling in a metric of its own. It would be explicitly against the Prometheus semantics to manipulate the scrape timestamp in that way. The scrape timestamp is really that: the scrape timestamp.

Furthermore, in your case of many scrapes but few polls, you would accumulate many samples at the same timestamp within Prometheus. If a set timestamp makes sense at all, it's the inverse case: Many polls and fewer scrapes. But even that is questionable. (The reason we have the timestamp in the protocol at all is really streaming, i.e. if you want to replicate samples 1:1 from one Prometheus server to another.)

I'll close this until I see a convincing use case for exposing timestamps.
