### ISSUE TITLE
Auto increment supported Go version

### ISSUE THREAD

**Issue by kakkoyun** [prometheus/client_golang#1435]
Client_golang promises support for the latest the last 3 major versions of Go. On every new Go release, we need to submit a few PRs updating the metrics collected by Go Collector. We already have scripts that autogenerates those new metrics, but it is not fully automated with our CI/CD.

--- 

This task is about connecting the dots between CI/CD and Go Collector metrics autogeneration

xref: https://github.com/cncf/mentoring/pull/1120

**Comment by dvjsharma** [comment]
Hello @kakkoyun ,

It would be helpful if you could outline the specific segments of the pipeline that haven't been automated yet. Additionally, could you provide detailed insights into the manual tasks required during a new release? If there's any supporting documentation available, please include it.
Thanks!

CC @ArthurSens

**Comment by kakkoyun** [comment]
Hey @dvjsharmam thanks for the question. All these will be discussed as part of the mentorship program. 

IMHO, going through the whole life-cycle of development tasks and helping interns navigate the open-source world is the core idea behind the program. It's not about specifying some issues and just getting them implemented.

I also mentioned what's needed in the issue description. A quick GH search would lend you to the program that generates those metrics https://github.com/prometheus/client_golang/blob/main/prometheus/gen_go_collector_metrics_set.go and an example PR https://github.com/prometheus/client_golang/pull/1105

**Comment by dvjsharma** [comment]
Thanks @kakkoyun for the response, excited for the mentorship program! I'll take a look at the resources.

**Comment by SachinSahu431** [comment]
Relevant PRs:

https://github.com/prometheus/client_golang/pull/1476
https://github.com/prometheus/client_golang/pull/1481
https://github.com/prometheus/client_golang/pull/1489
