### ISSUE TITLE
[CI]: Add Concurrency Grouping to GitHub Workflows

### ISSUE THREAD

**Issue by Ishani217** [prometheus/client_golang#1437]
### Requirement

Whenever we push commits to a PR, workflows are triggered for that commit. After that, if we push additional commits to this PR, workflows in Github Actions run on both commit

### Problem

We need to cancel the previous run and run only on the most recent pushed commit. This would help save some GitHub Action Minutes and unexpected workflow failures on subsequent commits.

### Proposal
Use concurrency groups to achieve this

**Comment by Ishani217** [comment]
@ArthurSens @kakkoyun Could you please give me a heads up on this issue. I would love to solve this, to gain experience with this project.

**Comment by ArthurSens** [comment]
Hi @Ishani217, we haven't had any issues with Action minutes as far as I can remember

I don't see a reason to not do this though, so feel free to come up with a PR :)
