### ISSUE TITLE
Q: Are you going to release a new version anytime soon?

### ISSUE THREAD

**Issue by mostafa** [prometheus/client_golang#1452]
The reason I am asking is that the current release is incompatible with the other projects it imports and uses. So, I used the latest commit on the main branch.
- https://github.com/gatewayd-io/gatewayd/pull/451/commits/e564acee5a2f53e24fb1b0ec8fdf158f6581e0e0

**Comment by mostafa** [comment]
Hadn't notice this one:
- https://github.com/prometheus/client_golang/pull/1451

**Comment by ArthurSens** [comment]
Yeah, I'm just going after some reviews and will get this tagged :)

**Comment by ArthurSens** [comment]
There you go!

https://github.com/prometheus/client_golang/releases/tag/v1.19.0

**Comment by mostafa** [comment]
Perfect, thank you!
