### ISSUE TITLE
Can client_golang be used to export data to a native file on system?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [prometheus/client_golang#147]
As we known,  people who are familier with the linux OS should be used to read data from native file on the system.
I have read the client_golang/prometheus/README.md file , that shows:
func main() {
    http.Handle("/metrics", prometheus.Handler())

    indexed.Inc()
    size.Set(5)

    http.ListenAndServe(":8080", nil)
}

In the example in the README.md, the data is exported to the localhost accroding the http  package.
Is there a way to exported the data to a native file according the prometheus/client_golang, which api should be use? Or, is there a example for it?

thanks very much.

**Comment by beorn7** [comment]
So far, we only expose the handler. I'm currently working on a more modular version of the registry where you can access the created protobuf. Then, you can easily write them to disk, if you so desire.

**Comment by zenlinTechnofreak** [comment]
@beorn7  so can u fingure out where to get the registry, and simply tell me how to realize?
thx.

**Comment by beorn7** [comment]
The registry is private as of now. I'm working on changing that.

**Comment by zenlinTechnofreak** [comment]
ok, so if u have done, if possible, plz let me know, thank u.

**Comment by brian-brazil** [comment]
Only the Python client can do this currently: https://github.com/prometheus/client_python#node-exporter-textfile-collector

**Comment by zenlinTechnofreak** [comment]
@brian-brazil  thx, I am going to read it ,and try to realize it. @beorn7 , if u have any further suggestion according this way?

**Comment by grobie** [comment]
The ruby client also supports the text file format and any kind of output of it.

```ruby
prometheus = Prometheus::Client.registry
# ... do something with the registry
File.write('/path/of/textfile', Prometheus::Client::Formats::Text.marshal(prometheus))
```

**Comment by juliusv** [comment]
Btw., here's a hack to get the entire output in text format programmatically within a test in cAdvisor: https://github.com/google/cadvisor/blob/master/metrics/prometheus_test.go#L123 - you could then write that output (in `rw.Body.String()`) to a file if you wanted to.

**Comment by zenlinTechnofreak** [comment]
@juliusv  thanks very much.

**Comment by thara** [comment]
For those of you like me who are looking here.:

> https://github.com/google/cadvisor/blob/master/metrics/prometheus_test.go#L123 

This link indicates wrong location because it's been a long time since this issue was created.
Probably, the correct code location is here.
https://github.com/google/cadvisor/blob/ff0796712b1910cc7bd96fb97588083cd1f9e029/metrics/prometheus_test.go#L123
