### ISSUE TITLE
Remove go-spew dependency

### ISSUE THREAD

**Issue by anurag-deshpande** [prometheus/client_golang#1490]
[Problem Description]
We are consuming `prometheus/client_golang v1.19`, which is latest as of date. This package is scanned for security vulnerabilities and EOLs by **blackduck scanner** at our source.

The blackduck scanner has identified a `Project EOL` component, `go-spew20180930-snapshot-d8f796af`, which is a **transitive dependency** of  `prometheus/client_golang v1.19`. This project is not maintained and thus EOLed much earlier.

[Request]
We wish to consume all the dependencies which are non-EOLed, to maintain good coding practices. Can this EOLed component be updated by client_golang contributors or replaced with some alternative with similar functionality, to reduce the EOL risk?

Let me know if any more information is needed for this issue.

**Comment by kakkoyun** [comment]
Thanks for opening the issue. 

When I checked, I saw that the mentioned dependency is not used anywhere critical. It is only used in tests and tutorial apps. https://github.com/search?q=repo%3Aprometheus%2Fclient_golang%20spew&type=code

That being said, we'd be happy to remove that dependency. 

Contributions are very welcome 😊

**Comment by dongjiang1989** [comment]
@kakkoyun I'll add PR to fix it
