### ISSUE TITLE
Text format parser does not de-dup quantiles.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#150]
...and presumably the same is true for buckets in Histograms.

See https://github.com/prometheus/pushgateway/issues/51 for a detailed example.

**Comment by msiebuhr** [comment]
Whoa - the *parser* is supposed to de-duplicate data!?

I am trying to backfill historic data (including response-time quantiles), but stuff like this makes it quite hard to get in, let alone correct...

**Comment by beorn7** [comment]
It's not de-duping of data in general, it's deduping data in a single text input to the parser. That's an error in the input, and the parser has to be able to deal with it.

Backfilling is an issue of its own and has to be solved properly. It's on our agenda (but not top priority).

**Comment by beorn7** [comment]
FTR: https://github.com/prometheus/prometheus/issues/535 deals with bulk import AKA backfilling.

**Comment by beorn7** [comment]
Moved to https://github.com/prometheus/common/issues/51
