### ISSUE TITLE
go_memstats_gc_cpu_fraction

### ISSUE THREAD

**Issue by A07110517** [prometheus/client_golang#1500]
go_memstats_gc_cpu_fraction no longer exists. Which indicator needs to be replaced in 1.18?

**Comment by kakkoyun** [comment]
These metrics are auto-generated. But somehow, we have missed update 1.18 🤔 https://github.com/prometheus/client_golang/tree/main/prometheus/collectors

We should double-check.

cc @SachinSahu431 @ArthurSens

**Comment by SachinSahu431** [comment]
@kakkoyun @ArthurSens  I wonder why 1.18 was [skipped](https://github.com/prometheus/client_golang/blob/a330ac5cee8f3cd7b51563a302fd8142189c0499/prometheus/collectors/go_collector_go117_test.go#L14)? 🤔

Also, I see [this comment](https://github.com/prometheus/client_golang/issues/842#issuecomment-861812034) mentioning about `gc_cpu_fraction` metric, please see if this helps?

**Comment by A07110517** [comment]
> @kakkoyun @ArthurSens I wonder why 1.18 was [skipped](https://github.com/prometheus/client_golang/blob/a330ac5cee8f3cd7b51563a302fd8142189c0499/prometheus/collectors/go_collector_go117_test.go#L14)? 🤔
> 
> Also, I see [this comment](https://github.com/prometheus/client_golang/issues/842#issuecomment-861812034) mentioning about `gc_cpu_fraction` metric, please see if this helps?

I got it, thank you
