### ISSUE TITLE
Ability to set CreatedTimestamp on constant histogram metrics

### ISSUE THREAD

**Issue by swar8080** [prometheus/client_golang#1535]
#1313 added created timestamp to the internal histogram data model:

https://github.com/ArthurSens/client_golang/blob/e5639d1dcb98e3f1027e110d11ab9eda54e36f34/prometheus/histogram.go#L1202-L1218

I don't see a way for clients to set the value for created timestamp? Specifically we are trying to use `prometheus.NewConstHistogram` 

I think this is why we're not getting any results when trying to calculate `histogram_quantile` since our `_bucket` counts don't start at zero without created timestamp injection. It'd also be nice if the `_sum` and `_count` metrics had zero injection.

---

Curious to know if hiding created timestamp from clients is intentional here, like if this part of the feature is WIP.

**Comment by ArthurSens** [comment]
Hmmmm, interesting. We have `MustNewConstMetricWithCreatedTimestamp` and even an [example](https://github.com/prometheus/client_golang/blob/7fe5d467da977311fbcb2e08f871afbcc86797d3/prometheus/examples_test.go#L659) for it, but I just realize it doesn't cover Histograms.

I'm supportive of adding the same functionality for ConstHistograms and ConstSummaries.
