### ISSUE TITLE
Readme: V2 branch, last update 5 years ago 

### ISSUE THREAD

**Issue by guettli** [prometheus/client_golang#1542]
Readme:

> The v2 development happens in a separate branch for the time being.

This branch is five years old. Please update the readme.

**Comment by bwplotka** [comment]
Thanks for reporting!

So currently we don't plan to develop v2 other than small experiments on potential v2 API inside v1 (!) (see https://github.com/prometheus/client_golang/blob/1a5f005c914eee4a9f0adf5b0fb19007683a6d99/prometheus/vnext.go#L23).

Honestly I would remove the branch or mention to stop confusion.
