### ISSUE TITLE
collected metric process_network_receive_bytes_total counter with unregistered descriptor

### ISSUE THREAD

**Issue by geberl** [prometheus/client_golang#1584]
I just updated the library version from v1.19.1 -> v1.20.0.

I now can't access my service's metrics any more.

```
curl localhost:8888/metrics

An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric process_network_receive_bytes_total counter:{value:456312} with unregistered descriptor Desc{fqName: "process_network_receive_bytes_total", help: "Number of bytes received by the process over the network.", constLabels: {}, variableLabels: {}}
* collected metric process_network_transmit_bytes_total counter:{value:387314} with unregistered descriptor Desc{fqName: "process_network_transmit_bytes_total", help: "Number of bytes sent by the process over the network.", constLabels: {}, variableLabels: {}}
```

Might be in connection with https://github.com/prometheus/client_golang/pull/1555 ?

Is anyone else seeing this?
 
Revert to v1.19.1 fixed it for me.

**Comment by CubicrootXYZ** [comment]
Encountered the same issue when upgrading to `v1.20.0`.

**Comment by geberl** [comment]
Looked a bit deeper, we use `reg := prometheus.NewPedanticRegistry()`, not `reg := prometheus.NewRegistry()`.

https://github.com/prometheus/client_golang/blob/989a6d0a1a2543c2d0d8b9a8c524eced9c81fd3d/prometheus/registry.go#L85

**Comment by zetaab** [comment]
we are hitting this same issue


Got 500 status code 
--

2 error(s) occurred:
* collected metric process_network_receive_bytes_total counter:{value:92659} with unregistered descriptor Desc{fqName: "process_network_receive_bytes_total", help: "Number of bytes received by the process over the network.", constLabels: {}, variableLabels: {}}
* collected metric process_network_transmit_bytes_total counter:{value:125661} with unregistered descriptor Desc{fqName: "process_network_transmit_bytes_total", help: "Number of bytes sent by the process over the network.", constLabels: {}, variableLabels: {}}

**Comment by zetaab** [comment]
I can confirm that the issue is NewPedanticRegistry. I tested here https://github.com/elisasre/go-common/pull/348 with and without it. I think #1555 is the breaking PR

**Comment by timofurrer** [comment]
We are also using the `NewPedanticRegistry` and running into the same issue. This is a breaking change for us coming from v1.19.1.

**Comment by bwplotka** [comment]
Thanks! We will fix promptly and make sure we have the process to not allow that in future.

**Comment by bwplotka** [comment]
Traveling, but quickly checking: Bug is that Describe method does not have those new desc items: https://github.com/prometheus/client_golang/blob/989a6d0a1a2543c2d0d8b9a8c524eced9c81fd3d/prometheus/process_collector.go#L135

To ensure we don't regress more, let's add tests against pedantic registry for all native collectors. Cc @ArthurSens

**Comment by ArthurSens** [comment]
I've created https://github.com/prometheus/client_golang/pull/1587 with 2 commits:

* First one uses `NewPedanticRegistry` in process collector tests.
* Second updates the `Describe()` method adding the new metrics.


Personally, I cannot reproduce this error locally and I've added the first commit hoping that at least the CI would catch it. To my surprise, even in CI the test pass 🤔 

Could someone who can reproduce the bug, try the branch from #1587 ?

**Comment by zetaab** [comment]
@ArthurSens it does fix the issue. Commit https://github.com/elisasre/go-common/pull/349/commits/827df1e4b454e168edd7e6f4ccd2dfa724c5a42a contains v1.20.0 (the CI will fail). And then trying PR #1587 https://github.com/elisasre/go-common/pull/349/commits/a3ab72b92096a9e6b483e03c005a6ffb121434d5 the PR goes through

**Comment by ArthurSens** [comment]
Could you clarify what OS is being used in your CI? https://github.com/elisasre/go-common/blob/76b822e4600d7b6b9a8dec22b1eb62f34fd1ced1/.github/workflows/default.yaml#L14

**Comment by zetaab** [comment]
@ArthurSens ubuntu 20.04 and amd64

**Comment by ArthurSens** [comment]
That's strange, we're also running ubuntu. Ideally we should find a failing test before saying that this fix the issue for sure 😭

**Comment by geberl** [comment]
Working for me in v1.20.1 🎉 
I'm closing this issue now. Thanks for your work @ArthurSens !
