### ISSUE TITLE
TestEmptyLabelSignature

### ISSUE THREAD

**Issue by ardan-bkennedy** [prometheus/client_golang#159]
This test is always failing in our linux environment using go 1.4.2

input := []map[string]string{nil, {}}

var ms runtime.MemStats
runtime.ReadMemStats(&ms)

alloc := ms.Alloc

for _, labels := range input {
	LabelsToSignature(labels)
}

runtime.ReadMemStats(&ms)

if got := ms.Alloc; alloc != got {
	t.Fatal("expected LabelsToSignature with empty labels not to perform allocations")
}

**Comment by fabxc** [comment]
Can you provide some details about your linux environment? Anything special that's explicitly different from regular distributions such as Ubuntu?

Regardless of the cause in your environment, if succeeding of this test is dependent on anything but the implementation it should probably be removed.

**Comment by ardan-bkennedy** [comment]
I did not allocate the box, it comes from our open stack environment. I will try to find out more for you.

This is how we run the tests and we are using go 1.4.2

cd src/github.comcast.com/ventris/kober
GORACE="log_path=stdout" go test -short -bench=Bench* -test.benchmem -timeout 2m -cpu 4 -race -v ./... | tee $WORKSPACE/test.output 
cat $WORKSPACE/test.output | "$WORKSPACE/bin/go2xunit" -fail-on-race=true -output $WORKSPACE/tests.xml
cat $WORKSPACE/test.output | "$WORKSPACE/bin/gobench2plot" > $WORKSPACE/benchmarks.xml

**Comment by ardan-bkennedy** [comment]
I found out information about the machine/VM

CentOS 6.4 and a openstack VM
4 X CPU, 8GB memory

**Comment by fabxc** [comment]
This is no longer a test. It was moved to a benchmark so the allocation efficiency can be verified by developers but doesn't make tests fail based on environment circumstances.
