### ISSUE TITLE
Support for creating multiple registries

### ISSUE THREAD

**Issue by bruth** [prometheus/client_golang#163]
I want to setup multiple endpoints on one host that a Prometheus server can scrape. I want to register a separate set of metrics for each endpoint, but there is only one (?) global registry for registering collectors. Is this correct or am I overlooking something?

**Comment by brian-brazil** [comment]
That's correct, the go client doesn't have that feature yet. #46 tracks this.

**Comment by bruth** [comment]
Got it, thanks.
