### ISSUE TITLE
Extract common exporter functionality into a package

### ISSUE THREAD

**Issue by fabxc** [prometheus/client_golang#166]
As we want to make writing exporters easier with the next version we should provide some helpers to generate a landing page. They are basically copy/paste for the existing exporters.

**Comment by grobie** [comment]
Agreed. @beorn7 just pointed me to this issue during a discussion about extraction common boiler plate from exporters. I'd like to make it easier to write exporters in client_golang by providing a framework which handles a set of common features (landing page, version printing, desc handling (might be solved by #222), common struct layout for descriptions, etc.). I'll follow up with some suggestions once I'm released from my SoundCloud duties.

**Comment by discordianfish** [comment]
@grobie I'd love that. I've probably written dozens of tiny exporters and feel the pain.
Also wondering if we could improve the UX around finding and deploying an exporter. 

For finding maybe some registry you can browse when looking for exporters? They could even get vetted, so you know which one provides the best/most idiomatic metrics.

**Comment by beorn7** [comment]
I'll remove this from the v0.9 milestone. This would definitely be useful to have, but it would go into a separate package anyway and there is little need to delay the 0.9 release for it. If it happens in time, great, but if not, no big deal.

**Comment by beorn7** [comment]
The work in this will happen in https://github.com/prometheus/exporter-toolkit . Closing it here.
