### ISSUE TITLE
Check help string consistency for standard metrics.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#171]
Not only the name, also the help string (and obviously type) of standard metrics exposed by every library (like process_open_fds) should be consistent. There are deviations at the moment, only detected by the pushgateway so far.

Check consistency and fix either here in `client_golang` or in the affected other library.

**Comment by njohns-grovo** [comment]
@beorn7 I started working on this (see the linked PR).  Correct me if I'm wrong, here are the places in which help text is provided by the library

#### client_golang
- https://github.com/prometheus/client_golang/blob/master/prometheus/go_collector.go
- https://github.com/prometheus/client_golang/blob/master/prometheus/http.go
- https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go

#### client_python 
- https://github.com/prometheus/client_python/blob/master/prometheus_client/process_collector.py

#### client_java
- https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/StandardExports.java
- https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/MemoryPoolsExports.java
- https://github.com/prometheus/client_java/blob/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/GarbageCollectorExports.java

**Comment by beorn7** [comment]
Looks good in general. Currently traveling and at Velocity, so in no shape to to pedantic checks.
Any increase in consistency will be a win.

**Comment by brian-brazil** [comment]
In Java it's only StandardExports, the rest are unique to java.

**Comment by beorn7** [comment]
Since the help strings in https://prometheus.io/docs/instrumenting/writing_clientlibs/ are now modeled after client_golang, we are in sync by definition.
