### ISSUE TITLE
Improve the way custom collectors for larger numbers of metrics can be written.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#182]
Examples:
https://github.com/mesosphere/mesos_exporter/blob/master/master.go#L75
https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L91

Is there a better way?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/client_python#custom-collectors is what Python has which is about as short as I think is possible. Given that Go is a bit more verbose, I'd say what we have is likely as good as it gets.

**Comment by beorn7** [comment]
Adding this to the v0.10 milestone because it should be implemented with the updated interfaces of v0.10, if it will be implemented at all.

**Comment by beorn7** [comment]
#222 should cover what can be done here.
