### ISSUE TITLE
Allow narrowing MetricVec.With / MetricVec.WithLabels

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/client_golang#188]
This is similar to what we can do with github.com/prometheus/common/log.

Supposing we define a MetricVec as follows in total:
```go
counter := prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace:   Namespace,
				Subsystem:   "subsys",
				Name:        "counter_total",
				Help:        "sometype of cumulative count",
			},
			[]string{"class", "name", "result"})
```

But I want to use those "class", "name" labels mapped into some other structs in my program which are user-initialized (i.e. I don't know what `class` or `name` will be before runtime, but once initialized they're reasonably constant.

It would be a huge simplication to be able to do something like:
```go
type someStruct struct {
  counter prometheus.CounterVec
}

func NewMyLongExistingStruct(class string, name string, globalCounter CounterVec) *someStruct {
  return &someStruct{
    counter : counter.With(class, name)
  }
}
```

which would retain freedom within the class to assign (potentially arbitrary) result labels. Currently you can't do this unless you narrow to a specific Metric instance.

**Comment by beorn7** [comment]
I'm afraid implementing exactly what you are suggesting would either change a lot in the API or add a lot of noise. However, you can already do what you want in a slightly different way:

```go
type someStruct struct {
    counter prometheus.CounterVec
}

func NewMyLongExistingStruct(class string, name string) (*someStruct, error) {
    counterVec := prometheusNewCounterVec{
        prometheus.CounterOpts{
            Namespace:   Namespace,
            Subsystem:   "subsys",
            Name:        "counter_total",
            Help:        "sometype of cumulative count",
            ConstLabels: prometheus.Labels{"class": class, "name": name},
        },
        []string{"result"},
    }
    if err := prometheus.Register(conterVec); err != nil {
        return nil, err
    }
    return &someStruct{
        counter: counterVec,
    }, nil
}
```

`RegisterOrGet` can be used if your class/name tuples are not unique across the constructor calls.
