### ISSUE TITLE
Concurrency issue in http.go

### ISSUE THREAD

**Issue by miekg** [prometheus/client_golang#189]
The call in https://github.com/prometheus/client_golang/blob/master/prometheus/http.go#L146
```
go computeApproximateRequestSize(r, out, urlLen)
```
creates concurrency issues because it iterates on request's Header map, if (for some reason) you happen to call this function more than once.

**Comment by beorn7** [comment]
The header map is only  read in the function. Is there any code path where the request header map is modified?

**Comment by juliusv** [comment]
@miekg ping

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [client_golang] Concurrency iss..." ]
>@miekg ping

This might be us doing whacky things, while this is being called. We basically
hacked around this, but not using these wrappers (that eventually call this
function) anymore.

Can't guarantee I can find enough time to properly debug this.

Close it?

/Miek

--
Miek Gieben

**Comment by beorn7** [comment]
I'll close it then. Please re-open if you find evidence.
