### ISSUE TITLE
Confusion surrounding MetricsVectors

### ISSUE THREAD

**Issue by abraithwaite** [prometheus/client_golang#193]
As a user, what's the appeal of using metrics Vectors over creating new metrics with ConstLabels and managing them yourself?  They both seem to be about the equivalent amount of work.  Perhaps it's just a docs thing?

**Comment by brian-brazil** [comment]
Vectors are for direct instrumentation, ConstLabels are for custom collectors. If you use either for the other purpose, you'll end up doing more work and likely getting it wrong.

**Comment by beorn7** [comment]
I'm planning to write cookbook-style examples for all of that. But I'll first finish reworking the client in general. Otherwise, I needed to rewrite the examples. :)

There are a lot of subtly different use cases where the one or the other approach might be clearer or more convenient. I'd expect that the XxxVec collectors are way more convenient for most "normal" uses, and you would only start to manage anything yourself as a "power user" (very high performance, where you don't want to pay the lookup cost every time, or dynamic partial specification, other fancy stuff).

**Comment by abraithwaite** [comment]
Please forgive my stupidity, but I still don't understand.  I don't see anything regarding ConstLabels and custom collectors in the docs.  Can you spell out what the implementation differences are between the two?  I read the code and it seems that a vector is just a map of hash(labels) -> metrics.  What does using ConstLabels do which is different from that?

**Comment by brian-brazil** [comment]
Sorry, I meant to say ConstMetrics for custom collectors.

**Comment by matthiasr** [comment]
In a nutshell, _metrics vectors_ when you are consuming "events" (say, HTTP requests) as they come in, annotated with some extra dimensions (say, method and status code). In this case, you are asking the client library to hold the current value for you, modify or increment it, and serve it when requests for metrics come in.

On the other hand, use _custom collectors_ and const metrics when the metric really lives somewhere else, and you're just relaying it through as needed. You don't even want to store the metric value (that way, you completely avoid having to deal with concurrency issues) – just fetch them when you need them from whatever system you are exporting from. For example, the HAProxy exporter also exports metrics about HTTP requests, with methods and status codes, but it does not even handle every single request: just when Prometheus comes around and asks for the metrics, it quickly connects to HAProxy, gets _its_ counter values, and relays them through. It can forget them right afterwards, which it does by letting the ConstMetric go out of scope and be garbage collected.

**Comment by abraithwaite** [comment]
@matthiasr thank you.  Your response helped me understand the differences more clearly.  Not sure how to articulate that distinction in the docs but in my experience most metrics have at least one variable tag which doesn't make sense as part of the metric name.  Perhaps @beorn7's examples rewrite will make it more clear that you should _probably_ be using Vectors if you're not already.

**Comment by brian-brazil** [comment]
Actually in practice the majority of metrics tend not to have labels. If you're finding that most of yours do, then you likely need to add a lot more metrics.

**Comment by beorn7** [comment]
@abraithwaite There was a bit confusion above about ConstMetrics and ConstLabels. All the stuff about custom collectors was meant to be about ConstMetrics.

You understanding is fundamentally right. A XxxVec is "just" a map of hash(labels) -> metrics. If you created each possible metric in the vec beforehand with their labels set as ConstLabels, you could manage them yourself. But that management work is exactly what XxxVec is doing for you (with a fast hash, concurrency safety and everything). As said above, managing it yourself is only worth it in very special use cases.

**Comment by abraithwaite** [comment]
> You understanding is fundamentally right. A XxxVec is "just" a map of hash(labels) -> metrics. If you created each possible metric in the vec beforehand with their labels set as ConstLabels, you could manage them yourself. But that management work is exactly what XxxVec is doing for you (with a fast hash, concurrency safety and everything). As said above, managing it yourself is only worth it in very special use cases.

Neat, thanks.  Our use case is essentially creating new metrics and attaching them to existing structs since we're tracking auxiliary state about them as well.  We're already managing the concurrency of the struct already so going through an additional layer didn't make sense to me.

**Comment by beorn7** [comment]
> Our use case is essentially creating new metrics and attaching them to existing structs since we're tracking auxiliary state about them as well. We're already managing the concurrency of the struct already so going through an additional layer didn't make sense to me.

Once you have the Metric object itself, concurrency is not a problem anymore. What XxxVec is taking care of is the concurrency of retrieving the Metric from the map. The Metric itself will always take care of its own concurrency around updating (e.g. `Inc` for counters, `Observe` for histograms), i.e. all its methods are concurrency-safe. If you are in need for a differently labeled metric for each instance of a struct, instantiating the metric as part of a struct upon its initialization is one of the use cases where you can use const labels for. (You could even have a vector in the struct, with variable and constant labels, if you need additional dimensions within the struct, essentially combining both approaches.)

I would assume @brian-brazil considers that an anti-pattern, but I had enough insightful users asking for it (and used it myself now and then) to support the use case in `client_golang`.

**Comment by brian-brazil** [comment]
> I would assume @brian-brazil considers that an anti-pattern, but I had enough insightful users asking for it (and used it myself now and then) to support the use case in client_golang.

I consider doing it cross-class/file to be a major anti-pattern.

Inside a file it's possibly okay, as you're moving the merging to be inside the client rather than in user code (which is a little annoying to have to do yourself with custom collectors). For direct instrumentation where I've seen the need in Java, you should be caching Childs per-object anyway so there's no benefit - though there's a 3rd party Python library doing something in this space that I'd have to take a look at again.

**Comment by beorn7** [comment]
So perhaps we are on the same page after all. We are talking about different instances of the same struct (i.e. the Go poor-man's version of a class). There is really not much of a need to still involve an overarching vector if every instance of that same struct manages its own metric (including registration upon construction).

**Comment by beorn7** [comment]
I think this is all clarified now.
