### ISSUE TITLE
Provide graphite bridge

### ISSUE THREAD

**Issue by grobie** [prometheus/client_golang#197]
In order to convince people to integrate the prometheus client directly in their project, it would help to have support for a graphite bridge. The Python client already [supports that](https://github.com/prometheus/client_python#graphite).

**Comment by beorn7** [comment]
This depends on https://github.com/prometheus/client_golang/issues/46 , which will separate the registry from exposition, so instead of exposing via HTTP, you can also regularly sent to Graphite.
