### ISSUE TITLE
prometheus.Unregister documentation is incomplete/misleading

### ISSUE THREAD

**Issue by haspeterd** [prometheus/client_golang#205]
Current documentation for promethus.Unregister() states:
```golang
// Unregister unregisters the Collector that equals the Collector passed in as
// an argument. (Two Collectors are considered equal if their Describe method
// yields the same set of descriptors.) The function returns whether a Collector
// was unregistered.
```

If you dig into the code of registry.Unregister, this comment is in the implementation:
```golang
	// dimHashesByName is left untouched as those must be consistent
	// throughout the lifetime of a program.
```

The fact that dimHashesByName is untouched means that if you naively call prometheus.Unregister() expecting that it will remove all traces of the collector, you can still run into issues later if you try to re-register the same collector name with, e.g., a different help string.

This behavior is a significant part of this function's contract, and it should be called out on the public-facing documentation for prometheus.Unregister.

**Comment by beorn7** [comment]
@haspeterd Now that we have discussed the context so meticulously, how about you create a PR that amends the doc comment? ;-)
