### ISSUE TITLE
Is the library usable without Singletons?

### ISSUE THREAD

**Issue by cep21** [prometheus/client_golang#216]
I'm evaluating Prometheus and I would like to not use singletons in my application, but the official Go client uses a registry singleton.  Is it possible to use prometheus without a singleton?

**Comment by brian-brazil** [comment]
That's presently being added, however it is strongly recommend you use the Singleton as otherwise you have to plumb the custom registry through to every every single bit of code (including 3rd party libraries and their transitive dependencies). Just like logging, for instrumentation a global object works out best.

**Comment by cep21** [comment]
>  like logging, for instrumentation a global object works out best.

Different opinions on that I suppose :)

I also wonder about the API: putting channels in the API, the strong use of Interfaces over structs, and forced use of prometheus objects directly.  Did you consider instead a model where users return the datapoints when requested, and the requesters are registered?

In this model,
```
type Collector interface {
	Datapoints() []*prometheus.Datapoints
}
```

can become any object that wants to be measured by prometheus and those objects are given to the http handler that can iterate them and make prometheus metrics out of them

**Comment by brian-brazil** [comment]
It's a bit more complicated than that, #214 if you want to chime in.

Keep in mind that the vast majority of users never have to touch the Collector interface, instead they'll use Gauge/Counter/Summary/Histogram so this is all hidden from them.

**Comment by beorn7** [comment]
Yeah, `client_golang` has a long history and (too) many options have been considered.
#214 will allow you to work without global state, if you want to. I know that many want that desperately, and that's one reason for the change described there.

**Comment by cep21** [comment]
Sounds good.  I read through the task and it's good you're trying to make it more Go like.  My thoughts are generally reflected in http://go-talks.appspot.com/github.com/cep21/go-talks/practical-advice-for-go-library-authors.slide  I worry about forcing users at my company to use prometheus objects directly.  For example, right now we are evaluating and trying many different solutions.  The ideal case is to use regular integers/histograms/etc directly then place them into prometheus or other objects for other systems.  This is what I mean by a collector design vs forced use of prometheus objects directly being more flexible.

**Comment by fabxc** [comment]
If you go as far as maintaining all the state yourself, it sounds like you rather want nothing but an encoder for the exposition format: https://godoc.org/github.com/prometheus/common/expfmt

It still has quite a few assumptions of being used in the general Prometheus context though.

**Comment by cep21** [comment]
I'm not totally sure how to use that package :/  Prometheus isn't as simple as writing out a MetricFamily protocol buffer on a http handler?

**Comment by brian-brazil** [comment]
> The ideal case is to use regular integers/histograms/etc directly then place them into prometheus or other objects for other systems. This is what I mean by a collector design vs forced use of prometheus objects directly being more flexible.

This is an explicit design decision. If you do things as your propose way then you get to reinvent labels, concurrency handling and all the bookkeeping that instrumentation requires. If you use our client library, we take care of all that nitty-gritty for you, and you can still extract it out to talk to some non-Prometheus system.

> I'm not totally sure how to use that package :/ Prometheus isn't as simple as writing out a MetricFamily protocol buffer on a http handler?

That would classify as hard in Prometheus land. You should never have to do that.

**Comment by cep21** [comment]
Thanks for answering my questions so far!

> you get to reinvent ...

That doesn't have to be the case.  You would create generally usable objects for the hard stuff and those objects would implement Collector.

> You should never have to do that.

I agree.  I guess I'm just asking for general advice for my own implementation: is it generally as easy as exposing a MetricFamily on a HTTP handler?  I'm trying to read over https://prometheus.io/docs/instrumenting/exposition_formats/ and it appears that's what I need, but wanted to verify first.

**Comment by brian-brazil** [comment]
> I guess I'm just asking for general advice for my own implementation: is it generally as easy as exposing a MetricFamily on a HTTP handler?

There's subtleties. Implement a Collector using ConstMetrics, and then use the exposition functionality we expose.

**Comment by beorn7** [comment]
You can pick your poison, based on your situation. In the following list, things go from "we don't only re-invent the wheel, we vulcanize our own rubber" to "this is what normal people do":
- Assemble `MetricFamily` protobufs and encode them via the `expfmt` package. The encoded result can be served via HTTP..
- Create the text-format representation by whatever means you want. Can be directly served to the Prometheus server.
- Implement a `Collector` that actively queries whatever existing metrics system you have and collects the metric as Prometheus metrics. https://github.com/prometheus/client_golang/blob/master/prometheus/expvar.go is an example for doing that with the `expvar` metrics.
- Make the structs that carry your internal metric data implement `Collector`. This obviously leaks Prometheus dependency into your existing code, while the previous example doesn't (i.e. expvar is completely ignorant of Prometheus).
- "Normally" instrument your code with our various collectors. That's recommended if you don't have any metrics library yet as it saves you work as Brian said.

Needless to say that real people have gone each of the ways above.

The Prometheus client libraries are "thicker" than usual telemetry libraries as they also help you instrumenting things, and they aim to keep your telemetry data consistent according to the quite involved Prometheus data model.

**Comment by beorn7** [comment]
With #214 merged, this should be resolved. Please reopen if you disagree.
