### ISSUE TITLE
Consider "internal vendoring" in client_golang/prometheus

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#217]
With the current state of the art of vendoring in Go, we could totally vendor "internal" dependencies in client_golang, i.e. those whose identifiers are never exposed in the API. (You could still type-convert to find out about it, like "this implementation of an interface looks like it's coming from that package, but if I cannot type-convert to it"). But that might be better than many external dependencies.

**Comment by beorn7** [comment]
These packages can be internally vendored: 
*  github.com/beorn7/perks/quantile                                    
*  github.com/matttproud/golang_protobuf_extensions/pbutil             
*  github.com/matttproud/golang_protobuf_extensions/testdata           
*  github.com/prometheus/common/expfmt                                 
*  github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg    
*  github.com/prometheus/common/model                                  
*  github.com/prometheus/procfs                                        

These cannot (because we have proto objects in our API):
*  github.com/prometheus/client_model/go                               
*  github.com/golang/protobuf/proto                                    
*  github.com/golang/protobuf/proto/proto3_proto                       
*  github.com/golang/protobuf/proto/testdata                           
*  github.com/golang/protobuf/ptypes/any

**Comment by fabxc** [comment]
That's a lot of dependencies. I recall those being less. Where are all
those proto packages coming from. "testdata" doesn't seem like something
necessary for people importing the regular code.

That said, what's the motivation? Are any of these at risk of being
imported by client lib users in other places with incompatible versions?
In particular
github.com/prometheus/client_golang/internal/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
seems a bit out of hand.

**Comment by beorn7** [comment]
I just took the packages as reported by `govendor`.

Of those we cannot vendor internally, only `github.com/prometheus/client_model/go` and `github.com/golang/protobuf/proto` are used directly by `client_golang`. The other protobuf related packages are used indirectly (via the two former packages).

> That said, what's the motivation? Are any of these at risk of being
imported by client lib users in other places with incompatible versions?

So far, we had no issues reported. The internal vendoring is motivated by reducing the considerable number of dependencies. Internal vendoring seems to be considered "partial OK" by now, but it is not undisputed. Personally, I would also be happy without any vendoring. But I think @fabxc asked me to do the internal vendoring. ;-)

> In particular
github.com/prometheus/client_golang/internal/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
seems a bit out of hand.

Yes, that's because we "manually" vendored that one internally already in prometheus/common. Nobody would ever see that, so I don't think the various layers are really a problem.

But as said, personally I am fine with not vendoring at all. I'm just reacting to requests that asked me to do the internal vendoring.

Opinions?

**Comment by fabxc** [comment]
Yea, it seemed more reasonable to me a while back than it does now. In the
end, those packages show up as separate dependencies in vendoring just like
any other. As a result, if the importing applications uses a package as
well, there's actually more stuff vendored. The chain of internal
vendorings is something I didn't consider at all before. This one makes it
actually seem like a really bad idea as a general method.

So from the present perspective, I'd say let's skip it as long as there are
no known incompatibilities and let's try to reduce the number of deps
general code structure and composability.

**Comment by beorn7** [comment]
@fabxc said:
> Yea, it seemed more reasonable to me a while back than it does now.

OK, then the one strong opinion that made me file this issue has gone away.
I'll close this one as: "We have considered it. Result: We won't do it." But if others would like to speak up, please do so in a timely fashion.

My personal concerns about internal vendoring:

It is kind of like just copying the code, but with various means of intervention by vendoring tools. Those might cause more trouble than it's worth it. In a way, if we really want to copy code, we should just do it (using the "internal" way as we did before). That should only happen for very short code snippets, so nobody will complain about the code bloat.

However, systematically vendoring internal dependencies screws over the following groups of users:
- Those that don't want to vendor. They now have to manually remove the `vendor` directory, as using it is not optional anymore in Go1.7.
- Those that want to do their own vendoring. They depend now on their vendoring tool to find internal vendorings and flatten it properly (which some but not all tools do — that's essentially what I meant when I said "(internal) vendoring is still not solved").

Those that don't care about the code bloat and are happy that the maintainer of a library includes all the needed code for them, are the only ones that are happy.
