### ISSUE TITLE
MetricVec hashing does not deal with collisions

### ISSUE THREAD

**Issue by stevvooe** [prometheus/client_golang#220]
If we look at https://github.com/prometheus/client_golang/blob/master/prometheus/vec.go#L167, we see there is no code to deal with collisions. For example, if two value sets come through that compute the same hash `h`, the incorrect metric will be returned.

Let me know if you want me to send a PR to fix this.

**Comment by beorn7** [comment]
Yes, this is a known issue. I've been pondering for a while how to solve this without performance penalty (in terms of runtime as well as allocations). Ideas are welcome, and PRs, too, but perhaps introduce your idea here first so that we can discuss the impact first.

**Comment by stevvooe** [comment]
It seems odd to require performance if the result is wrong. I'm not sure there is anyway to beat the performance since we will end up having to handle collisions. Is there a specific benchmark you want me to target?

The fix would be a textbook hash map collision resolution algorithm.

My fix would just change the map type from `map[uint64]Metric` to `map[uint64][]Metric` (https://github.com/prometheus/client_golang/blob/master/prometheus/vec.go#L28) and fix up collisions from there. Since these are reasonably rare, this can be a slow path.

The other options is to leverage array types (not slice!) as map keys to leverage goes hash map algorithm:

```
children map[[4]string]Metric
```

We could actually select that type based on the number of labels. It is a big hack, but it would work.

Checkout https://play.golang.org/p/hYi6FvDgj- to see it generated at runtime. With a bench mark, I can try these different methods out.

**Comment by stevvooe** [comment]
I also noticed that label value hashing is susceptible to map range ordering. The only reason this code works is because the map isn't reallocated or changed much but there isn't much guarantee that this _won't_ change. Code is here: https://github.com/prometheus/client_golang/blob/master/prometheus/vec.go#L229.

Once you take a peak at the options, I'll submit a PR that addresses both of these problems.

**Comment by stevvooe** [comment]
Alright, I have a branch that is collision resistant in a way that minimizes performance cost while avoiding new allocations, except in the case of collisions.

This includes a new set of benchmarks purely focused on `MetricVec` label value performance.

Here are the benchmarks:

```
benchmark                                                         old ns/op     new ns/op     delta
BenchmarkMetricVecWithLabelValuesBasic-4                          295           309           +4.75%
BenchmarkMetricVecWithLabelValues2Keys10ValueCardinality-4        851           873           +2.59%
BenchmarkMetricVecWithLabelValues4Keys10ValueCardinality-4        838           889           +6.09%
BenchmarkMetricVecWithLabelValues2Keys100ValueCardinality-4       852           945           +10.92%
BenchmarkMetricVecWithLabelValues10Keys100ValueCardinality-4      1025          1036          +1.07%
BenchmarkMetricVecWithLabelValues10Keys1000ValueCardinality-4     1019          1135          +11.38%

benchmark                                                         old allocs     new allocs     delta
BenchmarkMetricVecWithLabelValuesBasic-4                          0              0              +0.00%
BenchmarkMetricVecWithLabelValues2Keys10ValueCardinality-4        0              0              +0.00%
BenchmarkMetricVecWithLabelValues4Keys10ValueCardinality-4        0              0              +0.00%
BenchmarkMetricVecWithLabelValues2Keys100ValueCardinality-4       0              0              +0.00%
BenchmarkMetricVecWithLabelValues10Keys100ValueCardinality-4      0              0              +0.00%
BenchmarkMetricVecWithLabelValues10Keys1000ValueCardinality-4     0              0              +0.00%

benchmark                                                         old bytes     new bytes     delta
BenchmarkMetricVecWithLabelValuesBasic-4                          0             0             +0.00%
BenchmarkMetricVecWithLabelValues2Keys10ValueCardinality-4        0             0             +0.00%
BenchmarkMetricVecWithLabelValues4Keys10ValueCardinality-4        0             0             +0.00%
BenchmarkMetricVecWithLabelValues2Keys100ValueCardinality-4       0             0             +0.00%
BenchmarkMetricVecWithLabelValues10Keys100ValueCardinality-4      0             0             +0.00%
BenchmarkMetricVecWithLabelValues10Keys1000ValueCardinality-4     1             0             -100.00%
```

Since these are all losses, there is definitely a small performance loss, but it is minimal. I'll do a full benchmark suite check to see if other benchmarks are actually affected, since I built these to exercise several edge cases.

Note that at this time, the benchmarks don't exercise the collision paths. In practice, collisions should be very rare. I'm going to re-tool the tests a little to replace the hash function with something faulty to make sure we are still correct.

**Comment by beorn7** [comment]
Looks great at a first glance. I'll have a proper look once I'm back from my traveling and have caught up with things. Thanks for you work and apologies for the delays in review.
