### ISSUE TITLE
Create new tools for http.Handler instrumentation

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#224]
As mentioned in the doc comment, `InstrumentHandler` has issues beyond repair.
In the promhttp package, new utilities should be provided to instrument handlers and round-trippers in a more specific way.

See #200, #101, #57 for other issues to solve on the way.

**Comment by beorn7** [comment]
https://blog.golang.org/http-tracing and https://github.com/davecheney/httpstat might be useful to look at.

**Comment by orian** [comment]
Hi. I need this, is anyone else working on it? If not, I'll try to work on it.

**Comment by beorn7** [comment]
@stuartnelson3 is, kind of. And it already became apparent how hard this is to get right and how much context is needed. Not sure if it makes any sense at this time to involve somebody who misses that context.
If you are creating something like this anyway, no harm in sharing, and if it fits this library, we'll happily integrate.

**Comment by orian** [comment]
Sure, I understand.

@stuartnelson3 Is this context to read somewhere? Is the current work available somewhere?

**Comment by stuartnelson3** [comment]
That is correct, context was shared with me face-to-face. I'll try to look at this soon, but as is recommended in the library, rolling your own custom handler, at this point, will probably be a much quicker solution.

**Comment by orian** [comment]
Just for others:

 - calculating the size of request is not trivial, the best would be to modify the go http.Server to count it (it's returned anyway during read phase);
 - switching to histogram is easy, the problem may be how to choose bucket sizes;

The links provided by by @beorn7 are about the client tracing and required to modify the `net/http.Transport`
