### ISSUE TITLE
Provide helper to "describe by collect".

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#239]
If the metrics collected by a collector are using the same descriptors over the runtime of a binary, the `Describe` method can be implemented by calling `Collect` and then return all the `Desc`s of the returned metrics.

There are a number of cornercases where this is not possible, so we cannot just do the above by default. However, it can be explicitly used by implementers of Collectors.

**Comment by brian-brazil** [comment]
I think we can&should do the above by default, however it should be disabled by default on custom registries and there should be a way to bypass it on a per-collector basis (e.g. by implementing a no-opDesc).

**Comment by beorn7** [comment]
How would an implementation look like that does "describe by collect" by default?

**Comment by brian-brazil** [comment]
For Go, you'd remove the current Desc from the interface and add a new interface with the Desc. Then based on which interfaces are implemented, you either can auto-collect or use the user-provided Desc.

**Comment by beorn7** [comment]
I suggest to go with a helper function for v0.9 to not change the interfaces right now.
Then we can gather some experience.
Based on the outcome, we can consider the interface change in v0.10, which will change many interfaces anyway and opens up the opportunity for those more invasive changes.

**Comment by brian-brazil** [comment]
I imagine the cases where it won't be okay will be quite rare, so the wins in terms of filtering and ease of use will make up for it.

**Comment by beorn7** [comment]
Note: The suggested change of the interface to make DescribeByCollect implicit if no Describe method exists could still be considered for v0.10. (I'm kind of sceptical right now because it would not be "safe by default", i.e. somebody who naively implements a Collector without Describe would create something that seemingly works but then breaks later in surprising ways. But we can have that discussion when v0.10 is actually being worked on.)
