### ISSUE TITLE
Protobuf-based metricfamilyprocessor doesn't handle target label collisions correctly

### ISSUE THREAD

**Issue by juliusv** [prometheus/client_golang#24]
AFAICS the new protobuf-based extraction processor simply overwrites the target's base labels on a sample if the target sets a conflicting label itself:

https://github.com/prometheus/client_golang/blob/master/extraction/metricfamilyprocessor.go#L76

...whereas the JSON-based processors avoid such collisions by adding an `exporter_` prefix to the conflicting target labels (as specified in https://github.com/prometheus/prometheus/wiki/Automatic-Labels-and-Synthetic-Metrics):

https://github.com/prometheus/client_golang/blob/master/extraction/processor0_0_2.go#L71

This should probably be fixed for the protobuf processor as well.

**Comment by beorn7** [comment]
@juliusv Is that still an issue?

**Comment by juliusv** [comment]
This has been resolved via a series of `MergeLabelIngester`s in the Prometheus server.
