### ISSUE TITLE
Vendor Dependencies

### ISSUE THREAD

**Issue by gsquire** [prometheus/client_golang#264]
When using the `prometheus` package inside the vendor folder, it will not build because it's dependencies are not resolved. Has using a tool like [glide](https://glide.sh) or [govendor](https://github.com/kardianos/govendor) been considered?

Tooling aside, just using the vendor folder would simplify including the `prometheus` package as a dependency in an application.

**Comment by beorn7** [comment]
The client_golang repo is a library, and common practices are to not vendor dependencies of libraries in the library itself.

There is actually a long history of doing this or not doing this or partially doing this in the Prometheus project. The current state is to not do it.
