### ISSUE TITLE
deadlock when labels do not match created metric

### ISSUE THREAD

**Issue by ptone** [prometheus/client_golang#265]
With a NewGaugeVec I had specified one label (label1)

I went back to some old code and simply added an additional label to the usage which was:

<metric>.With(prometheus.Labels{"label1": "foo", "label2": "dummy"}).Set(4.5)

but I forgot to add label2 to the opts.ConstLabels param in creating the GaugeVec

I would have expected this to have some sort of runtime error - but instead the app just silently deadlocks.

**Comment by beorn7** [comment]
The extra label needed to go into the construction as an additional parameter to `NewGaugeVec`, not as an additional constant label.

But in any case, your usage should create an error in https://github.com/prometheus/client_golang/blob/master/prometheus/vec.go#L265, which will subsequently create a panic in https://github.com/prometheus/client_golang/blob/master/prometheus/vec.go#L146. My guess is that your `With` call is in a code path that recovers from a panic (perhaps in the HTTP serving path).

To get a proper error back and process it, use `GetMetricWith`.

**Comment by beorn7** [comment]
I assume the above explains your issue. Please re-open with contrary evidence if not.
