### ISSUE TITLE
Tag v0.8.0 should be 0.8.0

### ISSUE THREAD

**Issue by nvcnvn** [prometheus/client_golang#271]
Not really an issue but I both fan of SemVer and Prometheus and I wish they happy live together forever :)

**Comment by sdurrheimer** [comment]
The version is indeed `0.8.0`, we just prefix this version number in some places (like git tags and docker image tags) to mention that it is in fact a version number and not anything else.
AFAIK SemVer doesn't forbid prefixing with a `v`.
