### ISSUE TITLE
promhttp metrics

### ISSUE THREAD

**Issue by m247suppport** [prometheus/client_golang#276]
Hi,

Just a quick question: I would like to confirm if the metrics (below) provide information just relating to the sub-processes of the httpprom framework only or do they also incorporate metrics for the wider process, or even a mix of both? If it is both, then where might this information be defined? 

go_gc_duration_seconds_sum
go_gc_duration_seconds_count
go_memstats_heap_idle_bytes
go_memstats_sys_bytes
process_resident_memory_bytes
go_memstats_alloc_bytes_total
process_cpu_seconds_total
process_max_fds
go_memstats_alloc_bytes
process_start_time_seconds
process_virtual_memory_bytes
go_memstats_stack_sys_bytes
go_memstats_buck_hash_sys_bytes
go_memstats_stack_inuse_bytes
go_memstats_last_gc_time_seconds
go_gc_duration_seconds
go_memstats_mcache_inuse_bytes
go_memstats_frees_total
go_memstats_heap_inuse_bytes
go_memstats_heap_sys_bytes
process_open_fds
go_memstats_heap_objects
go_memstats_heap_released_bytes
go_memstats_mallocs_total
go_goroutines
go_memstats_mspan_inuse_bytes
go_memstats_mcache_sys_bytes
go_memstats_mspan_sys_bytes
go_memstats_other_sys_bytes
go_memstats_heap_alloc_bytes
go_memstats_lookups_total
go_memstats_gc_sys_bytes
go_memstats_next_gc_bytes

Thanks in advance!

**Comment by beorn7** [comment]
All `go_…` metrics refer to the Go runtime of the whole process. All `process_…` metrics refer to the whole process, too.
