### ISSUE TITLE
time.Since() considered harmful

### ISSUE THREAD

**Issue by kormat** [prometheus/client_golang#280]
In the examples for this library, there's a particular line which depends on `time.Since()` to measure a duration: https://github.com/prometheus/client_golang/blob/master/examples/random/main.go#L74

Unfortunately this uses wall-time, which does not guarantee monotonicity. In the case of a leap second (or other jump in system wall-time), this can cause a panic if for example it is fed into the `Add` method of a metric. That doesn't happen in this particular case, but nonetheless is likely to mislead people into thinking that `time.Since()` (or `t.Sub()`) is a reasonable way to measure a duration (i'm speaking from personal experience :).

Go does not currently expose a monotonic time source in its standard library (though hopefully that will change in 1.9:  https://golang.org/design/12914-monotonic). Until then, i strongly recommend using https://github.com/gavv/monotime instead, which does expose the monotonic time that the golang runtime has access to.

**Comment by beorn7** [comment]
Good to know. We are actually using `time.Since()` in timer.go, too. The result is fed into an Observer, where negative observations are fine but unexpected in this context (breaking the expectation of the `_sum` time series behaving as a counter).

This is something to consider. It will create yet another external dependency, though…

**Comment by brian-brazil** [comment]
I've been (inconsistenly) clamping this to 0 in other client libraries timing functionality. That's good enough IMHO, though may lead to surprises if a user wants to track something other than time that can also produce negative numbers (not that we support that for Summaries).

**Comment by AlekSi** [comment]
You can do nothing and wait for Go 1.9 in first days of August: monotonic time proposal was accepted.

**Comment by beorn7** [comment]
We want to make this package usable with older Go versions, too. Depending how critical we see this, we should either still fix it for older Go versions or recommend Go 1.9 for exactly that reason.

**Comment by beorn7** [comment]
1.9 is almost there.

What do people think? Should we add an external dependency, guarded by a build flag for 1.8 and earlier?
Or should we keep things simple and assume people will use 1.9+ if they care about monotonic time?

**Comment by AlekSi** [comment]
Simpler is better.

**Comment by grobie** [comment]
Agreed.

**Comment by brian-brazil** [comment]
Saying 1.9 sounds good to me.
