### ISSUE TITLE
Process start time varies over time on some systems

### ISSUE THREAD

**Issue by juliusv** [prometheus/client_golang#289]
On some machines I'm working with, the exported `process_start_time_seconds` as read from `/proc/<pid>/stat` varies ever-so-slightly over time, even without the process having a restart. This breaks alerting on e.g. `changes(process_start_time_seconds[30m]) > 3` to alert if there have been more than 3 restarts within the last 30 minutes.

We should probably only read the process start time from `/proc/<pid>/stat` once and cache it for the remainer of the process runtime.

**Comment by grobie** [comment]
Sounds like a bug you should file against procfs :p

**Comment by juliusv** [comment]
@grobie I was considering that at first as well. Do you think the caching should happen there? Maybe it's too low level (just file accesses + interpretations of contents) to cache it there already? Not sure.

**Comment by grobie** [comment]
I think getting clarification on the behavior would be good in either way.
Wonder if it's a bug or something else.

Have you checked the stat file manually and can confirm the different time
values? Just to rule out any parsing / type conversion issues (can't
imagine though).

Maybe there is also a different way to get that info.

**Comment by juliusv** [comment]
@grobie I couldn't check the `stat` file directly yet because I don't have access to the machine. However, I'm pretty sure it must be at fault. The process start timestamp *mostly* stays the same on those machines, but only the last couple of digits drift over time.

**Comment by juliusv** [comment]
@SuperQ has ssh access to these machines and could check if the actual contents of `/proc/<prometheus-pid>/stat` changes over time.

@SuperQ on one of the GitLab Prometheus machines in question, could you run this for a couple of hours and share the result?

```
$ while [ 1 ]; do cat /proc/$$/stat >> /tmp/stat.out; sleep 600; done
```

**Comment by juliusv** [comment]
Sorry, I meant `/proc/$(pgrep prometheus)/stat`, corrected in the comment above.

**Comment by SuperQ** [comment]
I've captured a couple days of data.  I will share it with you via google drive.

**Comment by juliusv** [comment]
Interestingly, the process start time field in @SuperQ's provided output does indeed not fluctuate. Looking at how the final start time is constructed, https://github.com/prometheus/procfs/blob/master/proc_stat.go#L169, the other culprit could be the boot time, as read from `/proc/stat`.

@SuperQ would you be up for running doing the same with that file for me? :)

```
$ while [ 1 ]; do grep btime /proc/stat; sleep 600; done
```

**Comment by juliusv** [comment]
Yep, I think the boot time reporting must be broken, as `node_boot_time{fqdn=~"prome.*"}` also gives me slightly varying boot times over time. You can see the boot time drift over the last 2 weeks here:

![boot_time_drift](https://cloud.githubusercontent.com/assets/538008/24606982/09d66c56-1870-11e7-8b70-1c993e4cfcf4.png)

Would still be good to verify that indeed the `/proc/stat` output is changing.

**Comment by SuperQ** [comment]
I can confirm the problem in `/proc/stat`.

```
$ sort btime.log | uniq -c
      5 btime 1489415595
     73 btime 1489415596
     78 btime 1489415597
     36 btime 1489415598
```

**Comment by grobie** [comment]
-.-

Alright, I think we should still try to get an explanation for this
behaviour from kernel/procfs people and also check for an alternative
reliable source.

Otherwise given systems don't really reboot in 1 second (especially not for
timestamps in the past), we should be able write a workaround for that in
procfs.

**Comment by grobie** [comment]
@SuperQ what's the biggest jump between two consecutive reads?

**Comment by SuperQ** [comment]
@grobie I was only sampling every 60s.  I did some quick spot checking in the prometheus data (scrape interval 15s). The worst case node is drifting about 100s per hour.  I don't see any big jumps.

**Comment by grobie** [comment]
Thanks! I'll move the workaround discussion to prometheus/procfs once back
at a laptop.

**Comment by brian-brazil** [comment]
Is the worst node having NTP issues?

**Comment by grobie** [comment]
Oh, I wasn't considering that the boot time might not be stable, but makes
sense as you could move it into the future otherwise. I guess we have to
rule out this isn't a gitlab infrastructure issue first.

**Comment by SuperQ** [comment]
I checked ntpd, it claimed to have a synced peer, but offset was listed as 430s.

I've restarted the ntp on the node to see if that helps.

I've also correlated this to a new specific type of VM instance.

**Comment by SuperQ** [comment]
Sorry, the previous statement was incorrect, the offset is 430ms, so not a big deal.

**Comment by grobie** [comment]
The boot time is completely stable on Brian's DO(?) box:
http://demo.robustperception.io:9090/graph?g0.range_input=3d&g0.expr=changes(process_start_time_seconds%5B3d%5D)&g0.tab=1&g1.range_input=1h&g1.expr=changes(node_boot_time%5B3d%5D)&g1.tab=1

**Comment by SuperQ** [comment]
Yup, I had a couple other Prometheus users check their clusters and found no problems.  This seems isolated to a specific cloud provider VM hypervisor and/or kernel version combination.  I will open a ticket with the cloud provider tomorrow.
