### ISSUE TITLE
Support for querying metadata on the client

### ISSUE THREAD

**Issue by andrestc** [prometheus/client_golang#290]
I've noticed the client is missing methods to fetch for [series metadata](https://prometheus.io/docs/querying/api/#querying-metadata), namely: `GET /api/v1/label/<label_name>/values` and `GET /api/v1/series`. Any particular reason the client isn't exposing those (i noticed it even has the `epLabelValues` and `epSeries` consts)?

I can contribute those since I'll need them anyway.

**Comment by juliusv** [comment]
@andrestc Pretty sure the only reason they're missing because nobody got to that yet - so a PR to add it would be very welcome!

**Comment by beorn7** [comment]
I think both are implemented by now.
Please re-open if not.
