### ISSUE TITLE
Why CancelableTransport?

### ISSUE THREAD

**Issue by arvenil** [prometheus/client_golang#292]
https://github.com/prometheus/client_golang/blob/5636dc67ae776adf5590da7349e70fbb9559972d/api/prometheus/api.go#L71

Why?

```
// CancelableTransport is like net.Transport but provides
// per-request cancelation functionality.
type CancelableTransport interface {
	http.RoundTripper
	CancelRequest(req *http.Request)
}
```

It doesn't seem to be used anywhere and it brakes compatibility `http.RoundTripper does not implement prometheus.CancelableTransport (missing CancelRequest method)`. `Transport` for client is just an implementation of `RoundTripper` interface and now I can't pass custom transport that implements only `RoundTripper`. If `CancelRequest` was used, fine, but it doesn't seem to be even used. 
Also `CancelRequest` on `Transport` is deprecated.

**Comment by grobie** [comment]
Implemented before go1.7 where CancelRequest wasn't deprecated and the http package didn't yet support canceling requests by passing a context. For now you need to wrap your roundtripper in another one implementing the CancelRequest.

The rewrite of the API package in #291 will remove the custom transport.
