### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by AmandaHassoun** [prometheus/client_golang#293]
While trying to use this exporter, https://github.com/promqueen/maillog_exporter, I encounter the following errors:

src/github.com/prometheus/client_golang/prometheus/registry.go:398: syntax error: unexpected range, expecting {
src/github.com/prometheus/client_golang/prometheus/registry.go:512: non-declaration statement outside function body
src/github.com/prometheus/client_golang/prometheus/registry.go:513: non-declaration statement outside function body
src/github.com/prometheus/client_golang/prometheus/registry.go:514: syntax error: unexpected }

Any idea on what is causing this?

**Comment by grobie** [comment]
You're using a very old golang version. I think `for range ...` was
introduced in go1.4. What version of golang do you use (you can use `go
version`)?

**Comment by AmandaHassoun** [comment]
Maybe you're right, I'm using version 1.2.1
