### ISSUE TITLE
how to query a single metric

### ISSUE THREAD

**Issue by reachlin** [prometheus/client_golang#294]
I'd like to query a counter added in my code for scrape just use curl:
```
	queryIndexCounter = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "prom2graphite_query_index",
		Help: "Index on Prometheus metrics",
	})
```
the counter is showed at the bottom of: curl http://myclient/metrics
but i ONLY want to query the counter itself, i tried: 
```
curl http://myclient/metrics?lable=prom2graphite_query_index
curl http://myclient/metrics/prom2graphite_query_index
```
none of above works

**Comment by grobie** [comment]
Such filtering isn't and won't be supported by client libraries. You can
use standard tools to filter on your own

curl -s http://myclient/metrics | grep prom2graphite_query_index

**Comment by brian-brazil** [comment]
That's planned actually, it's only in the Python client currently. Syntax will be `?name[]=`

**Comment by beorn7** [comment]
This is tracked in #135 .

**Comment by tangle329** [comment]
@beorn7   Can you please provide some example for this issue use curl?  Thanks
