### ISSUE TITLE
Idle metric series are never timed out

### ISSUE THREAD

**Issue by dansiemon** [prometheus/client_golang#296]
We are using the Prometheus Go client library to instrument an application that can occasionally see a large increase in the number of series for a given metric. That is, the possible values for one of the labels gets large for a short while.

After this happens, this large number of series stay in the client lib output forever even though they never see activity again. This increases the size of the Prometheus metrics response and also causes extra work for our downstream Influx server.

To work around this, we currently restart the application which obviously removes the 'idle' metric series.

Does it make sense for a timestamp to be stored in each metric which is updated for every change and have a background Goroutine which looks for 'idle' metric series and deletes them?

**Comment by brian-brazil** [comment]
This doesn't make sense as it's not how metrics instrumentation is intended to be used. Time series optimally should exist from when the process starts until it ends.

If a metric has such high cardinality that it's causing you problems at this level then you'll have problems with it in Prometheus too. I'd suggest removing that particular label from your metric.

**Comment by beorn7** [comment]
Yeah, we definitely don't want to remove those automatically. On the contrary, in the ideal case, you will pre-populate all possible label values, cf. #190 .

In your code, you can delete metrics individually with https://godoc.org/github.com/prometheus/client_golang/prometheus#MetricVec.Delete , or you can reset the whole vector with https://godoc.org/github.com/prometheus/client_golang/prometheus#MetricVec.Reset . But as Brian said, your really should check if you are perhaps having an abusive label there.

**Comment by dansiemon** [comment]
Thanks for the feedback. In our use case we're tracking metrics on a per-IP address basis where the set is usually reasonable but in certain situations can spike for a short time - typically with a mis-configuration.
