### ISSUE TITLE
where is the instance label defined (can it be overridden ?)

### ISSUE THREAD

**Issue by thechile** [prometheus/client_golang#297]
Hi, I'm using a exporter that in turn uses this library. For the metrics i received it always has labels like `{instance="10.32.38.15:9121",job="prometheus"}`. Rather than use something like `ConstLabels` to add another label with `os.Hostname()` i was hoping that changing the value of `instance` label would be easy but i can't figure out how this is done. Can someone confirm how this can be done please ?

Thank you.

**Comment by brian-brazil** [comment]
Please ask usage questions on https://groups.google.com/forum/#!forum/prometheus-users

https://www.robustperception.io/controlling-the-instance-label/
