### ISSUE TITLE
promhttp handlers panic with "metric partitioned with non-supported labels" when providing a ConstLabel

### ISSUE THREAD

**Issue by bracki** [prometheus/client_golang#299]
The [example](https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#example-InstrumentHandlerDuration) for the promhttp handlers mention adding a `ConstLabel {"handler": "some_handler"}`.
When you do this, `checkLabels` will panic. I think it would make sense to not look at the `ConstLabel` when checking for labels. Otherwise you have to encode the handler name into the metric names to get sensible metrics for your handlers.

**Comment by beorn7** [comment]
Oops, yeah, our hacky check for labels doesn't handle the recommended ConstLabels properly.

Will have to improve...

**Comment by beorn7** [comment]
It should now work as expected.
