### ISSUE TITLE
Is the lock granularity's too large ?

### ISSUE THREAD

**Issue by 1046102779** [prometheus/client_golang#301]
why lock a set of children([]metricWithLabelValues), not lock children(metricWithLabelValues)?
![image](https://cloud.githubusercontent.com/assets/20457624/25893696/6504875e-35ab-11e7-913b-cc7eca0e1c94.png)

**Comment by beorn7** [comment]
I don't understand the question. Could you provide a code example how you would do it differently?

**Comment by beorn7** [comment]
No follow-up received. Closing.
