### ISSUE TITLE
Please make a new release / tag

### ISSUE THREAD

**Issue by AlekSi** [prometheus/client_golang#306]
There are a lot of changes since v0.8.0: https://github.com/prometheus/client_golang/compare/v0.8.0...master

**Comment by beorn7** [comment]
Releases in client_golang are pretty lightweight as there are no binaries built. You can just build from head if you want the new changes.

The next release will be 0.9, and the roadmap is documented as a milestone, you can follow it here: https://github.com/prometheus/client_golang/milestone/1

**Comment by AlekSi** [comment]
I posted some backstory here: https://github.com/prometheus/client_model/issues/18.

**Comment by beorn7** [comment]
I would like to stick to the roadmap as described by the https://github.com/prometheus/client_golang/milestones

From your background story https://github.com/prometheus/client_model/issues/18, I conclude that we are dealing with a bigger issue here than just releasing a new client_golang version. Closing here to not have that discussion fragmented over many GitHub issues.
