### ISSUE TITLE
Add SettableCounter type

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/client_golang#309]
In previous versions of the golang client, Counter() types exposed "Set" and "Reset" methods to allow changing their values arbitrarily. This was incredibly useful when proxying a counter from some other free-wheeling process or external source, which might rollover between Prometheus scrapes but was otherwise definitely a counter.

I would like to propose that this functionality be re-exposed in the library as a SettableCounter type with attendant warnings in the documentation about the implications of its use.

**Comment by brian-brazil** [comment]
You should use a ConstMetric for this use case, rather than direct instrumentation.
