### ISSUE TITLE
Registry wide labels?

### ISSUE THREAD

**Issue by SamiHiltunen** [prometheus/client_golang#310]
Hey,

Is it possible to assign labels to registries? What I'd like to have, is that I register a metric on the registry and this metric would then have the constant labels that were assigned to the registry. This would be useful for assigning labels that should be attached to every metric like for example 'host' or 'instance_id'. Currently it doesn't seem to be possible to assign labels to metrics other except for when creating the metrics. In some cases, I do not control the metric creation but I can supply a registry which to register the metrics on. 

Is this possible or would you be open for this kind of feature?

**Comment by brian-brazil** [comment]
This is an anti-pattern, instance/host information should come from service discovery. Not the target itself.

Also, see https://www.robustperception.io/exposing-the-software-version-to-prometheus/
