### ISSUE TITLE
promhttp: Provide a sane instrumented handler

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#316]
Similar to the (by default) instrumented `prometheus.Handler`, a `promhttp.InstrumentedHandler` should be provided. The problem is to find sane defaults. The old one was questionable in various ways.

**Comment by beorn7** [comment]
Just to avoid misunderstandings: This is about the attempt to provide a sanely instrumented handler for serving metrics (usually via the `/metrics` endpoint). There will be no attempt to re-create the old `prometheus.InstrumentHandler`. The whole point of providing the individual middlewares was that no sane way could be found to provide a "one size fits it all" way to instrument a handler in general.

**Comment by beorn7** [comment]
Discussing this issue with @grobie , we dug out again the old problem of currying metric vecs. See #320 for a take and how it helps making the handle instrumentation with custom labels more streamlined.

**Comment by beorn7** [comment]
Result from a straw poll on prometheus-developers@:

- Most of the needs for metrics about the scrape are served well by the scraping Prometheus server itself. Evidence: No other Prometheus client library provides automatic instrumentation of the /metrics endpoint like client_golang, and nobody ever has asked for it.
- The only exception is if you want to know how heavily a monitored target is hit, possibly by multiple scrapers. Thus, we will add convenience instrumentation for a request counter and an in-flight gauge, called `promhttp_metric_handler_requests_total` and `promhttp_metric_handler_requests_in_flight`.
- This will only be provided for the default registry without any other configuration option (i.e. the only function to add will be `InstrumentedHandler()` as the instrumented equivalent of `Handler()`. Any more advanced cases will have to be spelled out explicitly using the provided middlewares.

**Comment by brian-brazil** [comment]
SGTM

> promhttp_metric_handler_requests_in_flight

In my blog posts and the Python client I've tended to call this _in_progress_. _active_ also seems somewhat common.

**Comment by brian-brazil** [comment]
I was thinking a little about the in_flight/in_progress metric. I'm not sure it's that useful as you'd have to have a long-ish scrape at with the just the right alignment to spot another scraper. A quantile-less summary for the latency would be better to get an idea of how heavy the request load is, and would also give us the request rate.

**Comment by beorn7** [comment]
The latency of a scrape can be monitored on the side of the scraping Prometheus server.

On the other hand, I had at least one case where a monitored target got overwhelmed by overlapping scrapes (which spawned #179 ).

**Comment by beorn7** [comment]
Since the existing middleware is already called `InstrumentHandlerInFlight` and the `_in_progress` has only been used in examples, I would like to revert to `promhttp_metric_handler_requests_in_flight` for consistency.
