### ISSUE TITLE
Expose Go version in new default metric

### ISSUE THREAD

**Issue by juliusv** [prometheus/client_golang#328]
As per https://github.com/prometheus/prometheus/issues/2566, it would be good to add a new default metric that exposes the Go version.

@brian-brazil Since we probably don't want to use the sample value to reflect the Go version, but a label, I kind of dislike the idea of redundantly calling both the metric `go_version` and calling the label `version` too. Should we do `go_info{version="..."}` and leave it open for other metadata in the future?

**Comment by beorn7** [comment]
Fixed by #329
