### ISSUE TITLE
How can I set timestamp to metric?

### ISSUE THREAD

**Issue by odg0318** [prometheus/client_golang#330]
Hi.

I want to set timestamp to some metrics. In my usage, I gather previous metrics(1 or 2 days ago) and save them with the time. It seems like that it is not supported now and I know that the feature is supported in prometheus exposition format.(https://prometheus.io/docs/instrumenting/exposition_formats/)
```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```

I will wait for great response.

**Comment by juliusv** [comment]
There's https://github.com/prometheus/client_golang/issues/187 out to allow and implement this for `ConstMetric`s (which are mostly used in exporters for proxying existing third-party state). I don't think there's a plan to allow setting custom timestamps for normal instrumentation, as that makes less sense and you have less scrape-time hook control there. So I'm closing this in favor of the existing issue.

**Comment by odg0318** [comment]
Thanks!

**Comment by wingsofovnia** [comment]
https://godoc.org/github.com/prometheus/client_golang/prometheus#NewMetricWithTimestamp
@odg0318
