### ISSUE TITLE
govendor breaks: pkg1 registers, pkg2 serves promhttp, pkg3 increments metrics 

### ISSUE THREAD

**Issue by therealplato** [prometheus/client_golang#331]
I want to declare metrics in one package, host the endpoint in another package, and invoke the metrics in a third package. I could not see my metrics on the endpoint when I used `kardianos/govendor` but they work when I use `golang/dep`.

Can anyone explain what broke ?

A repro case can be found at https://github.com/therealplato/missing-prom-metrics; the `master` branch has broken code with govendor and `dep` branch has working code with `dep`. Code organization details follow...

---

I call `prometheus.MustRegister(PromRequestStatusIncoming)` in the `init()` block of the `metrics` package.

I register the `promhttp` handler and listen in the `snitch` package, which used `govendor` for vendoring prometheus.

I invoke `metrics.PromRequestStatusIncoming...Inc()` in the `service` package.

Expected behavior:
After incrementing a metric, it is visible at the metrics endpoint.

Actual behavior:
After incrementing a metric, it does not appear at the metrics endpoint.

**Comment by brian-brazil** [comment]
> I want to declare metrics in one package, host the endpoint in another package, and invoke the metrics in a third package.

As a more general point, metrics should usually be defined and used in the same file. Defining across packages is unheard of. In this case you should probably instrument at your router, not in each handler.

I see nothing wrong with your code. This is likely an issue with your vendoring tool, make sure you vendor everything.

**Comment by therealplato** [comment]
@brian-brazil thx for the reply. I agree that vendoring is at fault. I'm hoping to understand exactly what broke with my govendor attempt.

re: defining across packages,  
I want to increment `http_status_incoming_total` with various parameters across dozens of different services in a monorepo. Each has its own codebase, vendor folder and binary.
Packaging the metrics that are identical across all services seems much more maintainable than keeping dozens of service-specific files in sync. Why is that unheard of?

The router is similarly in a package that provides promhttp and healthcheck endpoints that are identical across all services. Any other HTTP behavior by the services uses an unrelated Server and port.

**Comment by therealplato** [comment]
On my master branch, `snitch.go` ends up with an instance of `github.com/therealplato/missing-prom-metrics/snitch/vendor/github.com/prometheus/client_golang/prometheus`. The other code resolves it to a different vendoring path.

I hadn't realized the vendored `promhttp` was importing the vendored `prometheus` and affecting the state of the metrics.

thx @keegancsmith

**Comment by brian-brazil** [comment]
> I'm hoping to understand exactly what broke with my govendor attempt.

Usually the issue is that you haven't vendored every single dependency. We've seen this before in other contexts.

> I want to increment http_status_incoming_total with various parameters across dozens of different services in a monorepo. Each has its own codebase, vendor folder and binary.

If they're in different places in the codebase, then they're different metrics and thus should have different metric names. Here though what you really want is to instrument this at the http router, which you can then share between applications.
