### ISSUE TITLE
promhttp: do not ignore error log by default

### ISSUE THREAD

**Issue by v2e4lisp** [prometheus/client_golang#334]
I noticed that in the current implementation of promhttp, error logs are ignored if no logger object is specified. IMHO Using builtin log package to print error message would probably be a more reasonable default behaviour.

ref: https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/http.go#L176-L178

**Comment by beorn7** [comment]
The idea here is that libraries should not log on their own (even if it is the logger from the standard library), unless requested to do so. From all I know, that's common practice in the Go ecosystem.

Also, the default behavior is that errors are reported in the HTTP response, so they are not ignored by default.

Error handling went through many iterations of discussions with many people, so I'm fairly confident the current way is the best (or let's say the least bad) way of doing it. Thus, I'll close this. If you have more evidence to present that the current behavior should be changed, please add them here and I'll re-open.
