### ISSUE TITLE
Handle multiple calls to registry.Register() graceful

### ISSUE THREAD

**Issue by discordianfish** [prometheus/client_golang#34]
Hi,

I just realized (after quite some time debugging) that I can't just call registry.Register() multiple times with the same metric name. I expected this to be idempotent but that doesn't seem to be the case. More over, the behavior is quite surprising: All metrics just become stale, although calling Set() for a metric is still working fine - it's just not updating the exposed state.

As a example, this is a fix to not call Register() multiple times in my docker-exporter:

https://github.com/discordianfish/docker-exporter/commit/778cbb9a39b555fea812011bd25c0a42ebcc24d7

Before that, all metrics were stale after the first iteration. Now it seems to work fine.

**Comment by beorn7** [comment]
Yes.
