### ISSUE TITLE
Push the simple and random examples to docker hub

### ISSUE THREAD

**Issue by dlespiau** [prometheus/client_golang#347]
It'd be nice to be able to install those two examples with docker invocations so both an instrumented daemon and prometheus can be started this way. This would allow a full end to end example with two `docker run` and with a config file bound mounted, which seems fairly minimal.

The labels could be:
- `prometheus/example-golang-simple`
- `prometheus/example-golang-random`

I can prepare a PR building the docker images, but would be good to know if people are happy with the idea.

**Comment by beorn7** [comment]
I don't feel strongly. @discordianfish does this make sense?

**Comment by discordianfish** [comment]
Sounds good!

**Comment by bergquist** [comment]
Whats the state on this? I would love to use those images in our Grafana dev environment. 
So far I can only find the simple example https://hub.docker.com/r/prom/client_golang_examples_simple/

**Comment by beorn7** [comment]
See discussion on https://github.com/prometheus/client_golang/pull/348 . It looks we need to implement what was suggested last in the discussion on that (already merged) PR. I wanted to do it, but I have to admit I have way too many things on my plate that are much more important.
Happy to accept anything that improves things.
