### ISSUE TITLE
Reset() functions for Histogram{,Vec}

### ISSUE THREAD

**Issue by jim-minter** [prometheus/client_golang#351]
I think it would be convenient for the Histogram and HistogramVec to each have a Reset() function, just like, say, Gauge and GaugeVec have.

My use case is: I want to report the spread of durations of active jobs.  Once a job has terminated, I don't want to include it in the histogram any more.  Currently, in my Collect() function, I construct a new Histogram and run through my jobs calling Observe() for each.  If Histogram had a Reset(), I could reuse the Histogram object each time around instead of having to construct a new one.

**Comment by beorn7** [comment]
I don't quite understand. Any `...Vec` type has a `Reset()` method, which always does the same: _Reset deletes all metrics in this vector._

What exactly are you fishing for here?

**Comment by beorn7** [comment]
No follow-up received. Closing.
