### ISSUE TITLE
bridge.go:185:11: cannot assign 1 values to 2 variables

### ISSUE THREAD

**Issue by nim-nim** [prometheus/client_golang#352]
+ pushd prometheus/graphite
+ GOPATH=/builddir/build/BUILDROOT/golang-github-prometheus-client-0.9.0-0.5.git353b8c3.fc28.llt.x86_64/usr/share/gocode:/usr/share/gocode
+ go test
# _/builddir/build/BUILD/client_golang-353b8c3f3776541879f9abfd8fa8b1ae162ab394/prometheus/graphite
./bridge.go:185:11: cannot assign 1 values to 2 variables
FAIL	_/builddir/build/BUILD/client_golang-353b8c3f3776541879f9abfd8fa8b1ae162ab394/prometheus/graphite [build failed]

Using :
  go-compilers-golang-compiler.x86_64 1-14.fc27                                                                                                   
  golang.x86_64 1.9-1.fc28                                                                                                                        
  golang-github-beorn7-perks-devel.noarch 0-0.12.git4c0e845.fc27                                                                                  
  golang-github-prometheus-client-model-devel.x86_64 0.0.3-0.4.git6f38060.fc28.mllt                                                               
  golang-github-prometheus-common-devel.noarch 0-0.9.git195bde7.fc27                                                                              
  golang-github-prometheus-procfs-devel.noarch 0-0.19.gitfcdb11c.fc27                                                                             
  golang-bin.x86_64 1.9-1.fc28                                                                                                                    
  golang-bitbucket-kardianos-osext-devel.noarch 0-0.18.git9b883c5.fc27                                                                            
  golang-bitbucket-ww-goautoneg-devel.noarch 0-0.13.git75cd24fc2f2c.fc27                                                                          
  golang-github-Sirupsen-logrus-devel.noarch 0.8.4-9.fc27                                                                                         
  golang-github-bugsnag-bugsnag-go-devel.noarch 1.0.4-8.fc27                                                                                      
  golang-github-bugsnag-panicwrap-devel.noarch 1.1.0-0.6.gitaceac81.fc27                                                                          
  golang-github-davecgh-go-spew-devel.noarch 1.1.1-0.2.gita476722.fc28.mllt                                                                       
  golang-github-julienschmidt-httprouter-devel.noarch 1.1-8.fc27                                                                                  
  golang-github-matttproud-protobuf-extensions-devel.noarch 1.0.0-5.fc28.llt                                                                      
  golang-github-pmezard-go-difflib-devel.noarch 0-0.9.git792786c.fc28                                                                             
  golang-github-prometheus-client_golang-devel.noarch 0.7.0-9.fc27                                                                                
  golang-github-stretchr-objx-devel.noarch 0-0.12.git1a9d0bb.fc28                                                                                 
  golang-github-stretchr-testify-devel.noarch 1.1.4-1.fc28.mllt                                                                                   
  golang-golangorg-net-devel.noarch 0-0.40.git1c05540.fc28                                                                                        
  golang-golangorg-text-devel.noarch 0-0.21.git3bd178b.fc28                                                                                       
  golang-googlecode-goprotobuf-devel.noarch 0-0.30.git24f28ae.fc28                                                                                
  golang-src.noarch 1.9-1.fc28

**Comment by beorn7** [comment]
See #336 . It might be that your package provider does not yet provide packages that are sufficiently up-to-date.
