### ISSUE TITLE
Support fasthttp

### ISSUE THREAD

**Issue by krisdioles** [prometheus/client_golang#356]
So, currently there is no way (or is it?) to implement this lib to [fasthttp](https://github.com/valyala/fasthttp). Is there any plans to support it? Or how to contribute?

**Comment by metalmatze** [comment]
What exactly are you trying to accomplish with fasthttp that this lib shouldn't be able to do?

**Comment by beorn7** [comment]
I don't have experience with fasthttp. But the interface is clearly defined here. Similar to the `promhttp` package, you could create a `promfasthttp` (which doesn't even need to be in the same repo). You only need something like `HandlerFor`. As you can see in https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/http.go , it's not really a lot of code.

**Comment by krisdioles** [comment]
So I have trouble exposing `/metrics`  on services that uses fasthttp instead of net/http.

 Anyhow I already succeeded on creating the `HandleFor` equivalent for fasthttp and I have tested `/metrics` served by fasthttp on my dev side and it worked. 

My question is, should I code that on my side or should I code that on this repo? So that others that want to use this client on fasthttp can use it. I am sorry I am new in contributing.

**Comment by beorn7** [comment]
I would suggest to keep it simple and create a package in a repository you own. For users, it's really not a big difference between `import "github.com/prometheus/client_golang/prometheus/promfasthttp"` and `import "github.com/prometheus/client_golang/krisdioles/promfasthttp"`. We can link your package from the doc here to give people a pointer. At this time, I'm not a fan of tightly coupling `promfasthttp` with the packages here and thus take an additional maintenance burden. Should it turn out at some point that the world is really using only `net/http` and `fasthttp` and nothing else, we can take a raincheck if having both here makes sense.

**Comment by krisdioles** [comment]
Ok thanks for your replies and explanation. Closing this.

**Comment by gaby** [comment]
@beorn7 Any chance of taking a 2nd look at this after 5 years?

I'm one of the maintainers for https://github.com/gofiber/fiber which is based on `fasthttp`. I'm in the process of integrating a middleware for `prometheus` but in the current state we would need to convert each fasthttp request to net/http which adds a ton of overhead.

I noticed @krisdioles has an implementation of promfasthttp here https://github.com/prometheus/client_golang/compare/main...krisdioles:client_golang:fasthttp but it is probably outdated by now.

**Comment by bwplotka** [comment]
Yup, as have been said here: https://github.com/prometheus/client_golang/issues/356#issuecomment-338387700 -- there are many HTTP framework around, but not really popular ones (compared to std one).

One option would be to use some interfaces (or generics) for more generic version of promhttp, but those might defy the point of fast HTTP (there is some overhead for interfaces and generics).

I would say let's collaborate (e.g. by copying promhttp and tailor for fasthttp) on separate Go module and repo first (we could put it in prometheus-community GitHub org). I would say  also a decent place for it would be actually in https://github.com/valyala/fasthttp repo too if @valyala (or other fasthttp maintainers) would be up for it 🤗
