### ISSUE TITLE
client_golang/prometheus/value.go:Add not need use mutex ？

### ISSUE THREAD

**Issue by zhanglp92** [prometheus/client_golang#358]
When I concurrent running program, has some wrong. I don‘t use metex with my code.

I think locks should be added here.

code: github.com/prometheus/client_golang/prometheus/value.go
func (v *value) Add(val float64) {
	for {
		oldBits := atomic.LoadUint64(&v.valBits)
		newBits := math.Float64bits(math.Float64frombits(oldBits) + val)
		if atomic.CompareAndSwapUint64(&v.valBits, oldBits, newBits) {
			return
		}
	}
}

**Comment by metalmatze** [comment]
I think this is an issue for https://github.com/prometheus/client_golang/pull/359.

**Comment by beorn7** [comment]
As mentioned in #359, the code here is already goroutine-safe.
