### ISSUE TITLE
Consider using https://github.com/NYTimes/gziphandler for compression

### ISSUE THREAD

**Issue by tinytub** [prometheus/client_golang#366]
I have use client_golang to implement a subservice like pushgateway.
Every 30s scrape 500k - 700k line metrics from one subservice.
And it seems gzip cause very high cpu usage.
![image](https://user-images.githubusercontent.com/1871460/35047362-a954c596-fbd4-11e7-9047-6851010fd5ae.png)

With this large data, gzip didn't make the request much more quick

curl -w %{time_connect}:%{time_starttransfer}:%{time_total} -I -H 'Accept-Encoding: gzip' http://k4637v:6060/metrics
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 4935721
Content-Type: text/plain; version=0.0.4
Date: Wed, 17 Jan 2018 14:25:26 GMT

0.002:8.412:8.413                                                                                                               

curl -w %{time_connect}:%{time_starttransfer}:%{time_total} -I  http://k4637v:6060/metrics
HTTP/1.1 200 OK
Content-Length: 70412653
Content-Type: text/plain; version=0.0.4
Date: Wed, 17 Jan 2018 14:25:52 GMT

0.002:10.068:10.068

**Comment by beorn7** [comment]
We are using the normal way of the Go standard library to server gzip'd HTTP content. At least that's our intention.

Do you think we are doing something wrong here? If not, this would be an upstream issue of the Go standard library. I would assume, though, that gzip'ing just takes that much CPU. If you don't like compression, you can disable it in HandlerOpts: https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts

**Comment by beorn7** [comment]
Closing this for lack of response. Please respond with more information if you think this still needs to be addressed on our side.

**Comment by bobrik** [comment]
Similar issue: https://github.com/prometheus/blackbox_exporter/issues/270

**Comment by beorn7** [comment]
I guess this would boil down to trying out https://github.com/NYTimes/gziphandler . Reopening and adjusting the title.

**Comment by dswarbrick** [comment]
@beorn7 The nytimes gziphandler is actually pretty straightforward, and I'm not sure if it warrants adding as a dependency. I did some brief experiments last week with pooled gzip writers, and whilst it was an improvement (about 10% CPU time reduction), it was also a bit underwhelming. Clearly there are other areas for improvement.

**Comment by beorn7** [comment]
@dswarbrick Thanks for sharing your concerns.

**Comment by glefloch** [comment]
@beorn7 Can I start working on this?

**Comment by beorn7** [comment]
Sure. But remember to add some kind of benchmark so the improvement can be clearly demonstrated. As @dswarbrick said, adding a dependency is alway a burden and should have a noticeable value in return. Depending on how involved the code is, it might also make sense to implement the pooled gzip handler here in this repo.

**Comment by dswarbrick** [comment]
@glefloch You can find my experimental code in https://github.com/dswarbrick/client_golang/commit/89b83d0a236e9b99c303e11188ad683995d851a3
It's still a bit rough around the edges and of course a WIP, but you can probably get a feel for the direction I was headed with it. I intended to implement the gzip wrapper as HTTP middleware, to decouple it from the HTTP handler where all the magic happens.

**Comment by bboreham** [comment]
`sync.Pool` discards the things it is holding on to at each full GC.  So you will only benefit from pooling the gzip writer if your GC interval is way higher than the scrape interval.  Not that common, in my experience.

**Comment by dswarbrick** [comment]
@bboreham What kind of traffic volume are basing that assumption on? I am scraping approximately 1000 targets every 30s, so on average 33 targets per second.

**Comment by beorn7** [comment]
However, this is about the "client" side, i.e. the monitored target. Even if the server performs many scrapes, each individual target only sees a few scrapes per minute, usually. Thus, taking a gzip writer from a sync pool will be _more_ expensive in the regular case. Only in benchmark scenarios where you scrape very often you will see a gain.

**Comment by dswarbrick** [comment]
@beorn7 I should have been clearer. In the context of the blackbox issue (https://github.com/prometheus/blackbox_exporter/issues/336), I would have ~33 http requests per second hitting blackbox_exporter from some Prometheus instance. Here I think it most definitely makes sense to use pooled gzip writers for the HTTP response that blackbox sends.

**Comment by beorn7** [comment]
I see.
In that case, it might make sense. But is the GC load really generated by allocating the gzip writer?
I'd say the recent optimizations in prometheus/common/expfmt are more important. I have to revise what I said in https://github.com/prometheus/blackbox_exporter/pull/373 .

**Comment by glefloch** [comment]
I started benchmarking the uses of `sync.Pool`, and there seems to be an improvement of almost 46% going from `312412 ns/op` to `167013 ns/op`. I am going to work on benchmarking the NYTimes Gzip handler. 
Regarding the flag, I'm going to add it. Should I add a flag to disable the compression or a flag to disable compression ?

**Comment by beorn7** [comment]
Note that a benchmark essentially runs a scrape as frequently as possible, which is not the situation in real life (although, as we have seen above, there could be quite a few scrapes on the blackbox exporter as many different probes go through it).

I don't understand your question about the flag. client_golang/prometheus is a library. It must not have any flags. It's done via https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts , and where the compression is disabled there or not is a decision of the application using client_golang/prometheus . The application _could_ make this configurable for the user via a command line flag.

**Comment by glefloch** [comment]
You right I concerning the flag, there is nothing to do. This is already available.

**Comment by bboreham** [comment]
> But is the GC load really generated by allocating the gzip writer?

Yes, the gzip compressor allocates buffers in the tens of KB each time you make a new one.

But surely in this set-up where one process is scraped 33 times a second it should be returning a tiny amount of data so should not bother compressing it.

**Comment by brian-brazil** [comment]
> But surely in this set-up where one process is scraped 33 times a second it should be returning a tiny amount of data so should not bother compressing it.

That would be the case for the blackbox exporter, but not so much the snmp exporter.

**Comment by bboreham** [comment]
And is the snmp exporter another case where the GC interval is way higher than the scrape interval?

**Comment by beorn7** [comment]
We went for using a gzip.Writer from a sync.Pool after all, see #482 (which also, as a byproduct, introduces streaming exposition and removes the intermediate bytes.Buffer, which was there either because we thought it helps performance (which it does not) or because we really wanted to provide a content-length (which is not really important and obviously preventing streaming exposition)). It's at least not harming the usual low frequency scrape case, and it can only become better the higher the scrape frequency becomes.

Research suggests that including the dependency on the NYTimes gzip handler will not provide much additional improvement.
