### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by anicething** [prometheus/client_golang#371]
..\..\prometheus\client_golang\prometheus\promhttp\instrument_client.go:86:41: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:61:36: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:129:45: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:157:39: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:192:40: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:265:17: v.CurryWith undefined (type *prometheus.CounterVec has no field or method CurryWith)
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:268:7: undefined: prometheus.ObserverVec
..\..\prometheus\client_golang\prometheus\promhttp\instrument_server.go:269:17: v.CurryWith undefined (type prometheus.Collector has no field or method CurryWith)

**Comment by matthiasr** [comment]
I think you are developing against a new version of the client library, but you actually are using an older one. `go get -d -u` an update any vendored versions of the library.

**Comment by jeppojeps** [comment]
Sorry but I don't understand what do you mean, I have performed the command you suggest but my output is the same

**Comment by beorn7** [comment]
`ObserverVec` and `CurryWith` were introduced recently. The file instrument_server.go is also recent and refers to them, but the library files the compiler is looking at are older (perhaps in a `vendor` folder?).

This is a Go development question. It doesn't really make sense to discuss this in a GitHub issue. I recommend to seek help from your preferred source of Go support.
