### ISSUE TITLE
Make `process_…` metrics work on MS Windows

### ISSUE THREAD

**Issue by maxtar** [prometheus/client_golang#376]
All process metrics doesn't provided in windows.
I've wrote exporter for our system and couldn't find metrics started from `process_`. After that I moved exporter to linux server and all these metrics were appeared in prometheus server.

**Comment by beorn7** [comment]
Yeah, that's a know issue, but undocumented. We should definitely document that the process collector currently only works on OSs that have a proc filesystem, i.e. where https://github.com/prometheus/procfs works.
It should be relatively straight forward to wire in MS Windows support. Pull requests welcome. :o)

We needed another processCollect method (see https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go#L113 ), which could then be set [here](https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go#L90). Currently, just none is set if procfs cannot be found.

**Comment by beorn7** [comment]
We have just documented the not so satisfying state of affairs. It would still be great if somebody could write code for the process collector that works on MS Windows. We could leave this issue open to fish for a contribution.
