### ISSUE TITLE
Must Describe at least one gauge

### ISSUE THREAD

**Issue by lookfirst** [prometheus/client_golang#380]
Prometheus is **awesome**. Thank you for creating it.

I've [built a library](https://github.com/blockassets/prometheus_helper) that enables me to take a Struct and dynamically convert it into a bunch of `Gauges` and `GaugeVec's`. I do all this through reflection and it makes it super easy to [build](https://github.com/blockassets/litecoinpool_exporter).[new](https://github.com/blockassets/bwpool_exporter).[exporters](https://github.com/blockassets/cgminer_exporter) very quickly...

During the development, I discovered that if I don't add at least one metric to my collector when the `Collector.Discover()` method is called, the Registration process [gives me an error](https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L295).

The thing is that I add all my `GaugeVec` descriptors during runtime in the `Collector.Collect()` method because I'm dynamically creating them from the JSON that is returned from my API calls. Typically they are the result of processing a `map[string]interface{}`. I could do all my Gauges at runtime as well. 

But what happens when I don't even need a Gauge? There are obvious work arounds, I can add a ['Bogus' Gauge](https://github.com/blockassets/bwpool_exporter/blob/master/bwpool/poolData.go#L8) to my Struct or I could just add some random one myself. But this is obviously ugly.

I guess my question is, why the hard requirement?

**Comment by beorn7** [comment]
The question is a bit loaded, but your needs will essentially be covered by #47 (check the very last updates to the isse), which I'll tackle soon (TM). (But really, should be within weeks.)

**Comment by lookfirst** [comment]
@beorn7 Apologies. I don't mean it to be loaded.

**Comment by beorn7** [comment]
I have to apologize. I picked the wrong wording. I meant "this question has a lot of historical context and has already stirred up a good deal of discussion".

Do you agree that #47 covers your needs?

**Comment by lookfirst** [comment]
@beorn7 Your comment here: https://github.com/prometheus/client_golang/issues/47#issuecomment-239821104 

I'm a fan of the 'nothing' approach.
