### ISSUE TITLE
promhttp: Sanitize method to ALLCAPS

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#387]
`sanitizeMethod` is currently sanitizing methods to lower-case. However, is is way more common to use all-caps. See also [the RFC](https://tools.ietf.org/html/rfc7231#section-4.3 uses all-caps).

As we are breaking everything with 0.10 anyway, let's rectify this and sanitize to all-caps, using the [constants in the Go http package](https://golang.org/pkg/net/http/#pkg-constants).

**Comment by metalmatze** [comment]
But isn't it way more common in Prometheus metrics to just lowercase everything?

**Comment by brian-brazil** [comment]
For the metric and label names yes, there's not that convention on label values. In general you want what the underlying data is.

**Comment by beorn7** [comment]
I looked around a bit and found that most people use upper-case for HTTP method names in a Prometheus label _value_. Except, of course, they use the client_golang tooling. Looking at the RFC and the constants in the Go http package, it really looks that the lower-casing (introduced very early in the history of client_golang) was a mistake.

**Comment by metalmatze** [comment]
Alright. I guess this change seems good then.
Thanks for the clarification! :ok_hand:

**Comment by beorn7** [comment]
It _is_ a breaking change and is therefore in the v0.10 milestone.

**Comment by beorn7** [comment]
Fixed in https://github.com/prometheus/client_golang/tree/dev-0.10
