### ISSUE TITLE
JSON() method for Value while querying

### ISSUE THREAD

**Issue by pramodhkp** [prometheus/client_golang#390]
Hi, 

Would it be a good idea to add a `JSON()` method to the `Value` type here[1]? It'll be helpful when querying using the API client. 

[1] https://github.com/prometheus/common/blob/master/model/value.go

**Comment by brian-brazil** [comment]
You can use Go's standard JSON marshalling and unmarshalling functionality, there's no need for the library to add anything. That library is also internal, and there are no guarantees around it.

**Comment by beorn7** [comment]
Closing here for two reasons:
1. What @brian-brazil said.
2. The proposed change would be in  https://github.com/prometheus/common , not in this repo.

@pramodhkp: if you disagree with @brian-brazil, please open an issue against  https://github.com/prometheus/common or, even better, discuss things first on the [developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).
