### ISSUE TITLE
Query string with Label

### ISSUE THREAD

**Issue by AlexandrSemak** [prometheus/client_golang#391]
Hi All,

Can we specify function `Query(ctx context.Context, query string, ts time.Time) (model.Value, error)` query string with label ?
for getting metrics from specific job

**Comment by juliusv** [comment]
@AlexandrSemak You can include a label selector in the `query` string already, like `my_metric{job="myjob"}`.

You can also use `Series(ctx context.Context, matches []string, startTime time.Time, endTime time.Time) ([]model.LabelSet, error)` to get all series matching a set of matchers.

**Comment by AlexandrSemak** [comment]
@juliusv Yes thanks you it works

Maybe it's help somebody(for example)
```
	metrick := `http_requests_total{job="` + r.URL.Path[1:] + `"}`

	conf := api.Config{
		Address:      address,
		RoundTripper: api.DefaultRoundTripper,
	}
	client, err := api.NewClient(conf)
	if err != nil {
		fmt.Printf("Error while creating api.NewClient %s", err)
	}
	testTime := time.Now()
	api := v1.NewAPI(client)
	q, _ := api.Query(context.Background(), metrick, testTime)
```
