### ISSUE TITLE
[BUG] Escaped characters doesn't work with pushgateway

### ISSUE THREAD

**Issue by silence44** [prometheus/client_golang#396]
I'm using the latest stable version v0.8.0

I wan't to push some data to pushgateway with label that contains slash "/".
```Go
   myCollector = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: "my_namespace",
		Name:      "my_collector",
		Help:      "my_help",
    })
    prometheus.MustRegister(myCollector)
    myCollector.Set(111)

    grouping = map[string]string{}
    grouping["my_key"] = "test%2Ftest" //encoded variant of test/test		

    err := push.AddCollectors(
	"my_job",
	grouping,
	"http://localhost:9091",
	valueCollector,
    )
```

Expected result: 
Data successfully pushed

Actual result:
I got an error: unexpected status code 400 while pushing to http://localhost:9091/metrics/job/my_job/my_key/test%2Ftest: odd number of components in label string /my_key/test/test

**Comment by brian-brazil** [comment]
This https://github.com/prometheus/pushgateway/issues/97

**Comment by beorn7** [comment]
Closing as it is tracked in https://github.com/prometheus/pushgateway/issues/97 .
