### ISSUE TITLE
unable to build project - type match issue in summary.go

### ISSUE THREAD

**Issue by kcameron1973** [prometheus/client_golang#397]
I am trying to use this to build https://github.com/RobustPerception/nrpe_exporter and it requires client_golang but it is failing: 
# github.com/prometheus/client_golang/prometheus
/usr/lib/golang/src/github.com/prometheus/client_golang/prometheus/summary.go:325: cannot use s.objectives (type map[float64]float64) as type float64 in argument to quantile.NewTargeted

Any suggestions?

**Comment by grobie** [comment]
It appears you're using a very old verison of the quantile package in your GOPATH. The package has been changed to not longer use a simple float64 in January 2015. Try updating the dependency with `go get -u github.com/beorn7/perks/quantile`.

**Comment by kcameron1973** [comment]
Thanks for the quick response, that did the trick.

Kevin
