### ISSUE TITLE
Document stop-the-world implication of the Go collector and thus the default registry for older Go versions

### ISSUE THREAD

**Issue by gwik** [prometheus/client_golang#403]
Hi,

The `GoCollector` which is registered by default in the default registry calls[1] `runtime.ReadMemStats` which has the side effect of stopping the world[2] (releasing all the running threads to the OS...).
Obviously this can have a negative impact on performance.
The main problem is you can't opt out from this if you use the default registry, since the collector is registered in the default registry on package init.
A workaround is to have a package that registers a new default registry in init and import it before everything else in your main binary, but it doesn't feel sane and you have to get the other stats from a different collector that doesn't call `runtime.ReadMemStats`.

[1] https://github.com/prometheus/client_golang/blob/master/prometheus/go_collector.go#L273
[2] https://github.com/golang/go/blob/eb4f33243ece5874d2690c4b9bc72cb47f8da772/src/runtime/mstats.go#L457

**Comment by brian-brazil** [comment]
What version of Go are you using? As of 1.9 it takes less than 25us: https://go-review.googlesource.com/c/go/+/34937

**Comment by beorn7** [comment]
Yeah, this is definitely a known issue, and I vaguely remembered that we discussed at least documenting it. I guess the existence of this issue proves that we should document it.

I'll change the issue title accordingly.

However, providing yet another default registry with no go collector is not the way to go. The whole idea of a global default registry is to cater simple cases in a simple way. Making the default registry configurable defeats that purpose. Or on other words: You either have a really simple program that is happy with the default settings. Then you go with the global default registry. Or you do something more involved. Then you use the local custom registry and have all knobs to turn.

A default registry without memstats collection would only cater for the following triply special use-case where all of the following is true:
1. You are using an old Go version (where memstats collection is expensive).
2. Your program is performance-sensitive that the stop-the-world on scrape (usually only a few times per minute!) matters.
3. Despite being performance sensitive in the above way, it is _not_ complex enough to require a custom registry anyway.

**Comment by bakins** [comment]
@gwik You can unregister the Go collector by adding `prometheus.Unregister(prometheus.NewGoCollector())` to your application.
