### ISSUE TITLE
[feature request] Provide ability to update multiple independent counters/gauges/vectors using single function

### ISSUE THREAD

**Issue by baryluk** [prometheus/client_golang#411]
It is common to want to update multiple metrics atomically. Another reason is also that multiple different counters and gauges might require doing complex and similar precomputations, that should be shared for minimizing code size, improving locality and performance.

```golang
x := promauto.NewGauge(...)
y := promauto.NewGauge(...)

MonitoringCallback(x, y, func() error {
  z := ComputeSomethingExpensiveUsingComplexCode()
  x.Set(z.X())
  y.Set(z.Y())
  // This doesn't fully provide atomicity, but is reasonable start.
}, MonitoringCallbackOpts{...})
```

So this is like `NewGaugeFunc` but applies to a set of variables (counters/gauges/vectors). Each variable would only be allowed to be associated with single monitoring callback.

**Comment by beorn7** [comment]
That's the same use case as #410. The same explanation applies here.

**Comment by baryluk** [comment]
That was kind of the point of my issue. To provide a easy to use helper functions to create generic collectors of this kind. I believe (supported by years of using borgmon in C++, and observing others people code) this is common enough to justify having solution in library, and not make people reinvent it again and again with ad-hoc interfaces and structs around.

**Comment by beorn7** [comment]
If you really want to implement your pattern above, you could still do it in a `Collect` method. I see little overhead compared to your suggested layout.

However, after having written (and having seen the world writing) a lot of code of that style, the conclusion in the community was that the `NewConstMetric` pattern makes way more sense in general then creating fully fledged metric objects that you `Set` on collect. (Note that we deliberately removed the `Set` method from the `Counter` after that. It's only use was to mirror values calculated somewhere else during collections, but it breaks the counter semantics in direct instrumentation.)

Again, I would like to refer you to the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) if you want to open up a discussion about your feature request. In a GH issue, you are only talking to a limited audience, and later people will rarely find the discussion in a closed issue and start it over again.

**Comment by baryluk** [comment]
Ok, thank you for your explanation.
