### ISSUE TITLE
too restrictive invalid characters for metric name

### ISSUE THREAD

**Issue by neeral** [prometheus/client_golang#418]
I'd like to understand the logic in `bridge.go:replaceInvalidRune(rune)`. It seems to be very restrictive. In particular, you can't have `-` in the metric name, which is common in our use case. Another pain point is `.` are disallowed. The use case we have is for the `prefix`. It seems that only a single top-level prefix is supported. A multi-level prefix would be useful.

To give some background, we're using the bridge to convert stats from from one application to graphite format. We already have a lot of graphite metrics which are already arranged with prefixes.
e.g. An example is `node-name.service.metric_name`. Note the node name has a `-`, and `node-name.service` is a prefix.

I'm happy to help contribute to making this change, as long as there wasn't a technical reason why it wasn't done in the first place.

**Comment by simonpasquier** [comment]
The metric names have indeed some restrictions which are documented here: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

It is very unlikely that this will change in the near future. What people usually do is to  replace the unsupported characters (for instance `.` to `:`).

**Comment by brian-brazil** [comment]
This is about the Graphite bridge, which does not have to follow those rules.

**Comment by beorn7** [comment]
First of all: Whatever comes from a Prometheus metric name or a Prometheus label name cannot have `.` or `-` anyway. It simply cannot be produced by the Prometheus instrumentation as those characters would be invalid in Prometheus. A different story are the label _values_, where Prometheus allows all UTF-8 characters, but Graphite doesn't. I _guess_ the `replaceInvalidRune` was meant to conservatively not allow anything that would not work for Graphite. Via Prometheus labels, you could sneak in `.` and `-` for sure into the resulting Graphite metric name. (Note that `.` is used as a separator between the Graphite name components that have been label pairs on the Prometheus side.)

@stuartnelson3 wrote the bridge. He might know a rationale why he was so restrictive here.

Without further context, I would assume we could allow all characters that are legal in Graphite metric names. Possibly without the `.` if we want to create a clear mapping from Prometheus label pairs to Graphite name components (e.g. if a `.` appears in the Graphite metrics name, it should always be a label-pair separator but not coming from a label value).

**Comment by brian-brazil** [comment]
> Without further context, I would assume we could allow all characters that are legal in Graphite metric names.

I believe that varies based on the implementation and at times the underlying filesystem. In Python I do no sanitisation of the prefix, as I see it as at that point you are the end user/sysadmin and know what your Graphite can handle.

https://github.com/prometheus/client_python/blob/master/prometheus_client/bridge/graphite.py#L15 is what I use the sanitise the rest.

**Comment by beorn7** [comment]
Makes sense to me. I think, Brian's regexp just allows `-` in addition to what is allowed right now.

So how about adding `-` as a valid character but leave out the `.` with the reasoning given by Brian and myself above? And yeah, we could just let people pick their own poison by not sanitizing the prefix.

@neeral @stuartnelson3 does that make sense to you?

**Comment by neeral** [comment]
Yes, this would meet my use case. I'll send out a PR on this.

**Comment by beorn7** [comment]
PR is in. I'll declare this fixed. Please follow up if you see anything missing or a need to solve it in a different way.
