### ISSUE TITLE
Include testing package

### ISSUE THREAD

**Issue by brancz** [prometheus/client_golang#422]
Within the Kubernetes project there have lately been multiple instances where people wanted to test metric exposition. At one point @fabxc and I extracted testing code from the node-exporter (if I recall correctly) to [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/2e30678a4d4d055ce13a095c2ec8d14eef353570/pkg/collectors/testutils/testutils.go) where it has been extremely helpful. Now there are other components such as the [Kubernetes nginx-ingress-controller](https://github.com/kubernetes/ingress-nginx/pull/2726#issuecomment-401816568) and the [Kubernetes project itself](https://github.com/kubernetes/kubernetes/pull/65632) that want to vendor/re-use that package. I felt that naturally a testing package would fit into the client library, so I'd like to see what everyone thinks regarding adding this or a package like this to this project.

@beorn7 @brian-brazil @grobie

**Comment by brian-brazil** [comment]
The python/java clients have getSampleValue: http://prometheus.github.io/client_java/io/prometheus/client/CollectorRegistry.html#getSampleValue-java.lang.String- for unit testing.

**Comment by beorn7** [comment]
I like the idea of a testing package (and #58 has been on the plate forever…).

How about you create a PR with the testutil package as you would like to see it, and then we discuss details on the PR?

**Comment by beorn7** [comment]
Let's track this is #58 to avoid issue duplication.
