### ISSUE TITLE
go get github.com/prometheus/client_golang/prometheus have some error

### ISSUE THREAD

**Issue by lizhi16** [prometheus/client_golang#431]
I use "go get" to get prometheus, but I get some error:

github.com/prometheus/client_golang/prometheus/registry.go:452: syntax error: unexpected range, expecting {
github.com/prometheus/client_golang/prometheus/registry.go:454: syntax error: argument to go/defer must be function call
github.com/prometheus/client_golang/prometheus/registry.go:456: syntax error: unexpected range, expecting {
github.com/prometheus/client_golang/prometheus/registry.go:459: syntax error: unexpected }
github.com/prometheus/client_golang/prometheus/registry.go:463: non-declaration statement outside function body
github.com/prometheus/client_golang/prometheus/registry.go:464: non-declaration statement outside function body
github.com/prometheus/client_golang/prometheus/registry.go:529: non-declaration statement outside function body
github.com/prometheus/client_golang/prometheus/registry.go:530: non-declaration statement outside function body
github.com/prometheus/client_golang/prometheus/registry.go:531: syntax error: unexpected }

I check the code, but I think there are not grammar error. So how to solve these error? Thanks!

**Comment by beorn7** [comment]
This looks like you are using a very old go version. Which one are you using? (Hint: run `go version`.)

**Comment by hangyan** [comment]
@beorn7 @lizhi16  This seems related to go version, I'm using go 1.9.7 and still encounter this. I have checked this issue https://github.com/grpc/grpc-go/issues/2095. and solve it. It's the version of protobuf package. @beorn7 Is there a way to auto-correct this?

**Comment by beorn7** [comment]
The errors above have nothing to do with the protobuf package. They come from a `for` statement without mentioning a variable, cf. https://golang.org/doc/go1.4#forrange . These errors will occur if you use Go 1.3 or earlier. I don't know how you get those errors with Go 1.9. I can only assume that a Go 1.3 or earlier compiler snug in somehow and is trying to compile your code.

**Comment by beorn7** [comment]
Assuming this is resolved. Closing.

**Comment by beorn7** [comment]
@osallou I think you need to update your dependencies, in particular github.com/golang/protobuf/proto.

Try running
```
go get -u github.com/golang/protobuf/proto
```

On a more general note, a closed GitHub issue about a different problem is really the worst place to seek advice. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
