### ISSUE TITLE
Mock time for simulations

### ISSUE THREAD

**Issue by jayunit100** [prometheus/client_golang#436]
I'd like to 'mock' time for simulations that are using prometheus.

As a workaround, im currently using push gateways, and graphing a time variable as a separate timeseries.  

Any suggestions on how i can rig the prometheus clock, itself (either via client or server), to have synthetic times (i.e i want to do something like this) 

```
for {
  simulator.IncrementByDay() // this call takes 50 milliseconds or so.
  prometheus.IncClock(24*time.Hour)
  time.Sleep(500*time.Millisecond)
}
```

**Comment by beorn7** [comment]
I'm not sure I understand what you are shooting for.

If you need to backfill a Prometheus TSDB with historical (and/or mock) data, that would be a question for the Prometheus server developers.

This question sounds general and overarching enough (could be a usage question if there is a way, could be a feature request discussion if there is none) that I would recommend to use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or perhaps even the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) to ask your question and, if needed, start a discussion about the necessary features to be added.

**Comment by beorn7** [comment]
Assuming this is being dealt with on those other channels. Closing.
