### ISSUE TITLE
go1.11rc1 modules

### ISSUE THREAD

**Issue by icholy** [prometheus/client_golang#442]
Looks like the `v1` directory name is messing with go module's semantic import versioning.

**Note:** I'm working outside of the `GOPATH`

**main.go**
``` go
package main

import (
	_ "github.com/prometheus/client_golang/api/prometheus/v1"
)

func main() {}
```

**commands**
``` sh
go get golang.org/x/build/version/go1.10rc1
go1.10rc1 download
go1.11rc1 mod init prom_thing
go1.11rc1 build
```

**output**
``` text
go: finding github.com/prometheus/client_golang/api/prometheus latest
go: finding github.com/prometheus/client_golang/api latest
build prom_thing: cannot find module for path github.com/prometheus/client_golang/api/prometheus/v1
```

**Comment by icholy** [comment]
Related: https://github.com/golang/go/issues/25007

**Comment by beorn7** [comment]
@krasi-georgiev could you have a look?

**Comment by krasi-georgiev** [comment]
go modules is  a hot topic now so that one would be interesting :smile: 

@icholy a PR is welcome and I will review or can have a look when I clear some pending bugs and PRs.

**Comment by icholy** [comment]
@krasi-georgiev I think the package name has to change to something other than `v1`. Something like `promv1`

**Comment by icholy** [comment]
@krasi-georgiev see https://github.com/golang/go/issues/27102#issuecomment-414529875
Can we add a v0.9.0 tag?

**Comment by krasi-georgiev** [comment]
yep I think that would work.

@beorn7 any objections to if I add the v0.9.0 tag?

**Comment by beorn7** [comment]
v0.9 is not yet ready. If people need a tag, you could add v0.9.0-pre2. See README.md for a more general discussion of demands to tag one way or the other.

**Comment by krasi-georgiev** [comment]
`vgo` requires semver so v0.9.0-pre2 wouldn't work.

@beorn7 what if we add v0.8.1 ? not 100% accurate since this indicates bug-fixes and the current master  probably has some breaking changes, but it is a goo middle ground.

**Comment by krasi-georgiev** [comment]
just checked the semver format  and  we can use `0.9.0-alpha` .  vgo should understand that.

**Comment by beorn7** [comment]
Note that there is already `0.9.0-pre1`.

**Comment by beorn7** [comment]
You can follow the progress here: https://github.com/prometheus/client_golang/milestone/1
Those few issues are being worked on.

Note that pre-1.0 semver essentially means nothing. Please read https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-stability-and-your-favorite-go-dependency-management-tool for details.

Meta-note: The fluidity of dependency management tools has been proven again because we are now talking about vgo and not dep anymore…

Meta-meta-note: v0.9 would probably be ready already if I didn't have to invest my time into this kind of discussions again and again.

**Comment by krasi-georgiev** [comment]
@beorn7 IIUC you are against `0.9.0-alpha` or `0.8.1` ?

**Comment by beorn7** [comment]
I'm not against those, my note above was about the existence of the `0.9.0-pre1` tag, and it would be nice to keep consistency. Unfortunately, `0.9.0-pre1` is not semver compatible, but `0.9.0-pre.1` would be.

So how about tagging the current state as `0.9.0-pre.2`? We could even add a `0.9.0-pre.1` at the same position as `0.9.0-pre1` to be even more consistent.
Would that work?

**Comment by beorn7** [comment]
Note that we namespace the version tags with `v…`.

So suggestion would be to add a `v0.9.0-pre.1` at the position of the current `v0.9.0-pre1` tag and add a `v0.9.0-pre.2` tag at the current tip.

**Comment by krasi-georgiev** [comment]
posted a comment so lets wait and see
https://github.com/golang/go/issues/27102#issuecomment-414990651

**Comment by icholy** [comment]
@krasi-georgiev @beorn7 go modules only understand `v0.0.0` format. You can't add any prefixes or suffixes. https://github.com/golang/go/wiki/Modules#modules

**Comment by beorn7** [comment]
OK, then let's just work on getting 0.9.0 done ASAP.

**Comment by icholy** [comment]
@beorn7 in the case that 0.9.0 isn't ready before the Go 1.11 release, would you consider tagging the 0.9.0 early and then just tagging (what should be 0.9.0) as 0.10.0?

**Comment by beorn7** [comment]
Once the Go community has settled on a dependency management system, I'll surely consider anything to support it. By now, everything that came along went away again or is as of now still marked as experimental. I have consistently communicated the roadmap for this repo, and I don't want to lightheartedly confuse a potentially large number of people to satisfy early adopters of the next experimental dependency management system.

**Comment by krasi-georgiev** [comment]
yes I agree lets wait a bit.

**Comment by icholy** [comment]
> Once the Go community has settled on a dependency management system, I'll surely consider anything to support it.

@beorn7 I get that you've probably been annoyed by people trying to push you to adopt/support dep (which sucks), but at this point, go modules are pretty much set in stone as the official solution. They're not going away. I understand your hesitance though.

**Comment by krasi-georgiev** [comment]
anyway all that said I think we have an agreement here with the other maintainers that shouldn't yet make any changes yet just to satisfy vgo.

@icholy  As a workaround can just use a commit hash for now.

**Comment by icholy** [comment]
@krasi-georgiev that's what I'm doing. Btw, go modules works in tandem with vendoring. The long term plan is to have a module registry like https://docs.gomods.io/

**Comment by krasi-georgiev** [comment]
Thanks that was a nice read! 
Next step is to have this is as part of github or any other free proxy for FOSS projects.

**Comment by krasi-georgiev** [comment]
@icholy since you can use the commit hash and there are still free pending things for the 0.9 are you ok to close this and will revisit if needed later.
