### ISSUE TITLE
Create a public, configurable Registry.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#46]
For testing purposes and for advanced configuration (and possibly other uses), we want a public Registry interface with the possibility of plugging together implementations that behave according to the user's requirements (error handling, which standard metrics to export, http instrumentation, exposition - which might or might not be via HTTP, ...).

The Registry interface should be lean, possibly with parts of the functionality delegated to other interfaces or even modules (HTTP serving and/or instrumentation, Pushgateway handling, ...).

Currently, there is only one global registry, and it is not exposed to the user. It is used only via global convenience methods. We want to avoid a further explosion of the number of those functions. The good news is that for as long we support the existing functions, we can change everything behind it at will. Basic idea is to keep the existing convenience functions (with the option of deprecating those that are not used a lot), while providing advanced functionality via a more elegant but also more complex to use API (where you create a Registry implementation first that is configured to your needs and then register metrics there and decide about HTTP exposition and such). For inspiration, see https://github.com/prometheus/client_golang/pull/38 (code and discussion).

The convenience functions to keep are:
- `EnableCollectChecks`
- `UninstrumentedHandler`
- `Handler`
- `InstrumentHandler`
- `InstrumentHandlerFunc`
- `InstrumentHandlerWithOpts`
- `InstrumentHandlerFuncWithOpts`
- `PanicOnCollectError`
- `Push`
- `PushAdd`
- `SetMetricFamilyInjectionHook`
- `Unregister`
- `Registe`
- `RegisterOrGet`
- `MustRegister`
- `MustRegisterOrGet`

**Comment by beorn7** [comment]
@tsenart Lest we forget...

**Comment by tsenart** [comment]
:-)

**Comment by abustany** [comment]
That would be really convenient to eg. set ConstLabels on all metrics that are implicitly exposed, for example the "number of goroutines" and "gc stats" ones. Right now I don't see any way to alter those (the inject hook can apparently only be used to inject new metrics).

**Comment by brian-brazil** [comment]
> That would be really convenient to eg. set ConstLabels on all metrics that are implicitly exposed

You're looking for relabelling on the prometheus side, see http://prometheus.io/docs/operating/configuration/#target-relabeling-relabel_config

**Comment by abustany** [comment]
but then I'd need one target group per instance (I was thinking of per-instance ConstLabel set at program start)? We use file_sd at the moment, since EC2 discovery is not available yet (+ we need to SSH tunnel to get to the instances), would there then be a way to set per-host labels in there?

**Comment by brian-brazil** [comment]
> We use file_sd at the moment, since EC2 discovery is not available yet (+ we need to SSH tunnel to get to the instances), would there then be a way to set per-host labels in there?

Yes, that's the purpose of SD. EC2 SD should be available soon, see https://github.com/prometheus/prometheus/pull/1085

We generally recommend having the prometheus be on the same network to and talk directly to exporters.

**Comment by DBarney** [comment]
has there been any progress on this?

**Comment by fabxc** [comment]
@beorn7 just started working on it.

**Comment by tsenart** [comment]
:tada:

**Comment by filippog** [comment]
hi,
has there been progress on this? thanks!

**Comment by beorn7** [comment]
I work on it whenever I find time.

**Comment by iigorr** [comment]
Any news on this?

**Comment by beorn7** [comment]
Only the need to respond to nags delays the work on this right now. :)

**Comment by totallyunknown** [comment]
I would like to sponsor this issue if it's get done soon and merged into master. Is that a way we can go? How much effort is necessary to get this done done?

**Comment by beorn7** [comment]
The effort of transferring the mental state of this into another person is higher than doing it myself. I really just need some quietness to finish the coding, e.g. no disturbance by the need to update this issue. ;-)

**Comment by totallyunknown** [comment]
Is there a way how I can speed up this process with real $$$?

**Comment by beorn7** [comment]
Thanks for the offer, but no.

There will be a PR real soon.

**Comment by roman-vynar** [comment]
Great progress, thanks 👍
