### ISSUE TITLE
Max Counter Value

### ISSUE THREAD

**Issue by ramonberrutti** [prometheus/client_golang#463]
Hi, Counter are using uint64 (max value: 18446744073709551615)
I want to count the msg that I send by a Microservice, Now send 25M per Minute, yes. I know that I need so many years to overflow, but what happend if I overflow the counter?

**Comment by ramonberrutti** [comment]
I found the answer: https://github.com/prometheus/client_golang/blob/master/prometheus/counter_test.go#L168

**Comment by ramonberrutti** [comment]
after some test, I get that the value overflow and return to 0 without error.
`package main

import (
	"fmt"
	"sync/atomic"
)

var a uint64 = 18446744073709551608

func main() {
	for {
		num := atomic.AddUint64(&a, uint64(1))
		fmt.Println(num)

		if num == 10 {
			break
		}
	}
}`

Output:
`18446744073709551609
18446744073709551610
18446744073709551611
18446744073709551612
18446744073709551613
18446744073709551614
18446744073709551615
0
1
2
3
4
5
6
7
8
9
10`

**Comment by beorn7** [comment]
Yeah, sure, that's how normal integers behave. The Prometheus counter would behave in the same way if you incremented only by integer values. It would, however, return severely rounded value even before it overflows (as the actual value in the Prometheus exposition format is represented by an IEEE float64, even if the value is internally saved as a uint64). After the overflow, it would indeed start to count at 0 again, but that's fine, as the Prometheus data and processing model deals with counter resets. (The most common reason for a counter reset is, of course, a binary being restarted. uint64 overflows happen rarely in practice.)
