### ISSUE TITLE
Allow more flexible metric exposition.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#47]
With the current state of affairs, a collector has to know exactly the names of the metrics (including the label names for each) it will expose. The only way around that is the SetMetricFamilyInjectionHook function. However, it requires the user to assemble a dto.MetricFamily protobuf, i.e. it is very low-level.

Two approaches come to my mind (which we might want to implement both):

(1) A "prefix" registration: A collector can register a whole namespace (by prefix, could be simply implemented by putting "prefix*" as the name in the descriptor). It would still register for a fixed set of label names. That registration would disallow any other registration matching the prefix. With this approach, full consistency can still be guaranteed. The planned scrape of selected metrics would be a bit more expensive as we have to call the collector whenever a metric is requested that matches the prefix, but that's fundamentally unavoidable if we have dynamic metric names.

(2) An "unchecked" registration: A collector is allowed to collect _anything_ (possibly with the restriction on a name prefix aka namespace). Since metrics with any label set could be collected, consistency guarantees are gone. This would be similar to the SetMetricFamilyInjectionHook, but on a higher level, i.e. the user can collect normal Metric implementations and does not have to bother with low-level protobufs.

**Comment by beorn7** [comment]
@brian-brazil Does that match your requirements?

**Comment by beorn7** [comment]
@grobie @discordianfish You had a use-case for that in the HAProxy expoter, didn't you?

**Comment by brian-brazil** [comment]
That sounds good. I'd suggest combining 1) and 2) by allowing an empty prefix.

Is there any way to let the collector know which names are being requested? That could allow it optimise if if needs to (e.g. if this was ever added for the JMX exporter, you'd definitely want that).

**Comment by beorn7** [comment]
Definitely allow empty prefixes, but that's not automatically a combination of 1 and 2. 1 enforces a fixed set of label names, while 2 allows leaves it to the responsibility of the user to create consistent label name sets (i.e. the same metric name only ever having the same set of label names). In other word: The difference between 1 and 2 is not 'prefix or not' but 'fixed set of label names or not'. Both solution will deal with prefixes including the empty prefix.

Currently no plans to give the Collector a list of names to collect. That would require the collector to replicate logic that currently is (and has to remain) in the registry. So far, I would simply call all the collectors that _could_ expose a metric of the requested name, and then filter them before returning them over the wire. If you want to avoid needless collector calls, you must register collectors that have only one descriptor with a fully-qualified name (i.e. non-prefix).

**Comment by brian-brazil** [comment]
> 1 enforces a fixed set of label names

With 1) different metrics that are exported may need different sets of labels (e.g. haproxy_exporter has some metrics without labels and some with), but within a given metric it should be consistent.

> you must register collectors that have only one descriptor with a fully-qualified name (i.e. non-prefix).

A key use case of exporting selected metrics is speed so you can scrape them far more often. I'd want the ProcessCollector for example to not go counting the open file descriptors if I'm only looking for process_cpu_seconds_total. I think this sort of thing should be possible for advanced users.

**Comment by beorn7** [comment]
I see, you are talking about collect-time checks. With (1), I'm still shooting for "static" registration-time checks. The latter exposes errors earlier and allows to skip collect-time checks (-> better performance). To re-phrase once more: (1) still allows registration-time checks, (2) depends on collect-time checks (if enabled with `EnableCollectChecks` at all, otherwise you just collect anything).

About the scrape by metric name: Good point, but unfortunately requires an extension of the Collector interface.

Anyway, all of this is not announcement critical, so we can think about thoroughly once the more pressing issues are resolved.

**Comment by brian-brazil** [comment]
I think for registration time checks, all we can practically do is avoid metric name collisions. We can rely on the main Gauge/Counter/Summary implementations to ensure sane labels, and for highly custom collectors it'll have to be up to the collector.

**Comment by discordianfish** [comment]
:+1: Right now we're cheating at several places:
- https://github.com/prometheus/graphite_exporter/blob/master/main.go#L173
- https://github.com/prometheus/collectd_exporter/blob/master/main.go#L214

**Comment by beorn7** [comment]
After some playing around, I tend towards an "all or nothing" approach:

Either you have a well behaved Collector that returns exactly the Descs compatible with the Metrics returned during collection (in which case successful registration guarantees consistent metrics at scrape time) or you don't (in which case it is entirely your own responsibility to collect consistent metrics – inconsistent metrics won't be exposed, though, but result in an error at scrape time). Any attempts to be smart (as pondered above, e.g. prefix registration or something) have diminishing returns. You will be able to catch a few things, but you have to be prepared to handle errors at scrape time anyway.

So my proposal now is: If a collector returns _no Desc at all_ (i.e. just returns from the Describe method without doing anything) is rubberstamped for collecting anything. Registration will always succeed, and even pedantic checks will not complain about Metrics with non-registered Descs. (But if the complete scrape results in inconsistent metrics, an error is still created and handled according to the configured error handling, see https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerErrorHandling .)

I believe this is in line with @brian-brazil 's ideas. Let me know if you have any objections to this approach (which is easy to implement and non-breaking, so we could still do something more sophisticated later without any harm done). Otherwise, I'll implement it soon (tm).

**Comment by brian-brazil** [comment]
That sounds about right.

To be clear, if a collector reports some Descs but not all that'll still be okay? We may aswell get what safety checking we can (taking an example from Java, two JMX collectors in the same registry is a mistake that should be caught).

**Comment by beorn7** [comment]
My plan is to still check all Collectors that do return Descs against each other, even if "rubberstamp" Collectors are registered with the same registry.

**Comment by drawks** [comment]
> Otherwise, I'll implement it soon (tm). - @beorn7 

As we approach the anniversary of this issue I'm curious if any progress has been made on these changes?

**Comment by beorn7** [comment]
It's on my plate, and has high priority.
