### ISSUE TITLE
prometheus ValueType for Summary and Histogram support

### ISSUE THREAD

**Issue by richgrove** [prometheus/client_golang#470]
I am using the OpenCensus to define the prometheus type data like: 
```
	view.Register(
		&view.View{
			Name:        "asset_num",
			Description: "number of registered assets",
			Measure:     registeredAssetCount,
			Aggregation: view.Sum(),
		},
	)
```
Here asset_num is the Sum prometheus type defined in the OpenCensus prometheus.   When this metric is exported from the prometheus/go_client, it emits the "untyped" value.   Inside the library, the value.go only defines:
```
const (
	_ ValueType = iota
	CounterValue
	GaugeValue
	UntypedValue
)
```
Does this library support the Summary and Histogram types?  How does this work with the OpenCensus prometheus?   Thanks in advance.

**Comment by beorn7** [comment]
Those constant to determine metric types are only used in The `NewConstMetric` function (see https://godoc.org/github.com/prometheus/client_golang/prometheus#NewConstMetric ). They have nothing to do with the metric types supported by the library. The Prometheus `Summary` and `Histogram` are supported by this library. (But note that they might mean something else than somewhere else, cf. https://prometheus.io/docs/practices/histograms/ ).

If you have further questions, please ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). For usage questions, the mailing list makes more sense than a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

We use GitHub issues for bugs and to track the implementation of new features.
