### ISSUE TITLE
Please expose body when handling HTTP errors in the v1 package

### ISSUE THREAD

**Issue by porridge** [prometheus/client_golang#479]
The code [here](https://github.com/prometheus/client_golang/blob/93edea3/api/prometheus/v1/api.go#L332-L335) does not expose body on encountering an HTTP error. This makes it hard to troubleshoot issues such as a typo in the prometheus server address when using an HTTP proxy. In that case the proxy returns a helpful message in the HTTP error response body, but this library does not propagate this back.

One way to resolve this would be to add a `Detail` field to the [Error type](https://github.com/prometheus/client_golang/blob/93edea3/api/prometheus/v1/api.go#L71) and fill it with the stringified body [here](https://github.com/prometheus/client_golang/blob/93edea3/api/prometheus/v1/api.go#L472-L475).

**Comment by beorn7** [comment]
@krasi-georgiev this one is for you again... :o)

**Comment by porridge** [comment]
Hmm, I'm pretty sure it does return a body if a proxy returns a 500
response.

czw., 11 paź 2018, 18:25 użytkownik Krasi Georgiev <notifications@github.com>
napisał:

**Comment by porridge** [comment]
I mean I hacked the code a little and checked that it does.

czw., 11 paź 2018, 18:30 użytkownik Marcin Owsiany <marcin@owsiany.pl>
napisał:

**Comment by krasi-georgiev** [comment]
Maybe it depends on the golang version, I checked the go 1.11 implementation. 
Could you try go 1.11 as well and let me know.

**Comment by krasi-georgiev** [comment]
one other option is to try with error assertion.

`if ok != err.(*url.Error) ....`

**Comment by krasi-georgiev** [comment]
> I mean I hacked the code a little and checked that it does.


just to confirm when you are testing you should test that error is not nil and at the same time the body does contain what you are after..

**Comment by porridge** [comment]
I did use 1.11 :-)

czw., 11 paź 2018, 18:36 użytkownik Krasi Georgiev <notifications@github.com>
napisał:

**Comment by porridge** [comment]
Let me try and send you a test case tomorrow.

czw., 11 paź 2018, 18:52 użytkownik Marcin Owsiany <marcin@owsiany.pl>
napisał:

**Comment by porridge** [comment]
@krasi-georgiev Please take a look at https://github.com/porridge/client_golang/commit/5b54e790335dcc5c4a1999a6d572be5960bef9eb

In that case I'm serving a 500 right at the destination server, while this request is for the case of 500 being returned by the proxy, but the mechanics are exactly the same.

**Comment by krasi-georgiev** [comment]
what you are suggesting is reasonable. PR is welcome. 
Maybe even add it to 
`Msg:  fmt.Sprintf("response code:%d, body:%s", resp.StatusCode,body),`

**Comment by porridge** [comment]
Sometimes the body is long and useless, so I would be reluctant to add it
to msg unconditionally.

But I will try to come up with something.

pt., 12 paź 2018, 10:04 użytkownik Krasi Georgiev <notifications@github.com>
napisał:
