### ISSUE TITLE
Provide conventional way to retrieve metric values 

### ISSUE THREAD

**Issue by kofalt** [prometheus/client_golang#486]
Sometimes an observed metric is useful internally. I was surprised to see that it wasn't very straightforward to retrieve the current value from a declared Metric variable.

Gauge & etc are already concurrency safe, so it wouldn't make any sense to store the value a second time. But because their state vars are not package-exported (rightfully so), it's not as easy as just calling the same [Float64frombits](https://github.com/prometheus/client_golang/blob/f30f428035633da15d00d3dfefb0128c5e569ef4/prometheus/gauge.go#L125) stuff that's used internally.

I think this is the easiest way right now to pull a metric's value back out:

```go
store := new(dto.Metric)

SomeGauge.Write(store) # this call could fail, while the internal float-fetch cannot!

Println("The gauge is reading", *store.Gauge.Value)
```

It would be nice to just have `Gauge.Get() float64` and equivalents instead.

**Comment by beorn7** [comment]
This is deliberate. The only situation in which you should ever retrieve the value is for tests. For that, there is https://godoc.org/github.com/prometheus/client_golang/prometheus/testutil#ToFloat64

Prometheus metric types are optimized for fast updates, not for fast reads. (If you look at the Histogram implementation, you can see that. While Counter and Gauge are fast to reads from at the moment, that will change once Go offers access to core-local variables.) In short, we do not want to add a method to an interface that we discourage from using as we don't want to provide a library for concurrency-safe variables (that library is `sync/atomic`). If you need to read from a value internally that also happens to be a metric, it is recommended to track in with normal Go means and then expose it to Prometheus with https://godoc.org/github.com/prometheus/client_golang/prometheus#NewGaugeFunc or https://godoc.org/github.com/prometheus/client_golang/prometheus#NewCounterFunc .

I'm closing this issue as this was discussed multiple times over the past years. If you want to revisit that discussion, the best place is the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) as this touches more than just client_golang.

**Comment by icamys** [comment]
I was looking for this feature several times during the last couple of years. After finally understanding and accepting the fact that the client is designed only to **expose** existing metrics, I found a solution that works for me (thanks to @beorn7). Below I provide an example of code that allows reading values and use them as metrics at the same time.

```golang
// ==========
// File stats.go

type Stats struct {
    TotalPackets uint64
}

var stats *Stats

func init() {
    stats = &Stats{
        TotalPackets: 0,
    }

    prefix := "my_prom_prefix_"

    // MustRegister must be called only once, otherwise you will get duplicate metrics registration error
    prometheus.MustRegister(prometheus.NewCounterFunc(
        prometheus.CounterOpts{
            Name: prefix + "total_packets",
            Help: "The total number of packets received",
        },
        func() float64 {
            return float64(atomic.LoadUint64(&stats.TotalPackets))
        }))
}

func GetStats() *Stats {
    return stats
}

// ==========
// File main.go

var stats = GetStats()

// Increment value
atomic.AddUint64(&stats.TotalPackets, 1)

// use value in tests
assert.Equal(t, uint64(0), uint64(stats.TotalPackets), "packet count != 0")
```
