### ISSUE TITLE
Feature: Expose a request path label in the `http_request_*` metric by default

### ISSUE THREAD

**Issue by zephinzer** [prometheus/client_golang#491]
Currently, metrics are exposed as:

```
http_request_duration_microseconds{handler="users",quantile="0.5"} 401.237
...
http_request_duration_microseconds{handler="users",quantile="0.5"} 652.793
...
http_request_duration_microseconds{handler="users",quantile="0.5"} 652.793
```

I would like to add on to this by also allowing for a `path` label to be added so that each route does not need to be manually instrumented with a handler name. I'm proposing that the default collection should result in:

```
http_request_duration_microseconds{handler="users",path="/users/logout",quantile="0.5"} 401.237
...
http_request_duration_microseconds{handler="users",path="/users/login",quantile="0.5"} 652.793
...
http_request_duration_microseconds{handler="users",path="/users/status",quantile="0.5"} 652.793
...
# other examples I think would be useful
http_requests_total{code="200",handler="users",path="/users/status",method="get"} 3
promhttp_metric_handler_requests_total{path="/some/other/endpoint",code="200"} 2
promhttp_metric_handler_requests_total{path="/another/endpoint",code="500"} 0
promhttp_metric_handler_requests_total{path="/yet/another/endpoint",code="503"} 0
```

This could be done by adding `r.URL.Path` to the labels creation as a `path` label.

I'm new to Golang but would be happy to attempt this with some guidance!

Any opinions?

**Comment by stuartnelson3** [comment]
That was our concern. Some users could be putting user IDs or some other non-bounded set of data in the path, so we decided to avoid potentially destroying our users' prometheus servers.

**Comment by beorn7** [comment]
Prometheus itself would suffer. The TSDB of Prometheus has a very low price per sample (usually between one and two bytes) but a much much higher price per serios (kilobytes). Thus, your server would explode.

I'm not suggesting to use a 3rd party package. All the tools you need are included in client_golang. You should just not use the convenience-middlewares but the usual instrumentation primitives as described in the [linked video](https://youtu.be/HkEZ1LJ7kzQ?t=617).

**Comment by zephinzer** [comment]
cool, thanks for the advice on the potential effects on tsdb @beorn7! I gave it a watch and have managed to get up my own middleware to do something like what I was requesting for, am closing this-

but if anyone else is looking for such a convenience middleware despite the above warnings, I've published it at [https://github.com/zephinzer/ezpromhttp](https://github.com/zephinzer/ezpromhttp)!

**Comment by pavelpatrin** [comment]
I have a case, when to provide request path as a label is enough useful: gRPC Gateway server which is registered by `RegisterXxxHandlerServer()` call. It is impossible to produce metrics with gRPC middlewares, they are not called.

**Comment by ptman** [comment]
Go http.ServeMux now sets r.Pattern, which is a much better candidate than the path to avoid cardinality explosion
