### ISSUE TITLE
New Vector type that combines Histogram & Summary

### ISSUE THREAD

**Issue by sylr** [prometheus/client_golang#493]
Hi,

I wanted to create an histogram and a summary of the same data and therefore using the same base fqdn but client_golang won't let me because the `_sum` & `_count` of both the `histogram` and `summary` would have the same name.

So I wanted to know if could have a new type combining those two Vectors which would only generate one `_sum` and one `_count` along the `{quantile}`s and the `_bucket`.

```
XX = prometheus.NewHistogramSummaryVec(
    prometheus.HistogramSummaryOpts{
        Namespace: "azure_api",
        Subsystem: "",
        Name:      "call_duration_seconds",
        Help:      "Azure API calls durations in seconds",
        Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.95: 0.005, 0.99: 0.001},
        BufCap:     50000,
        MaxAge:     10 * time.Minute,
        Buckets:   []float64{0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50, 1.0, 2.0},
    },
    []string{},
)
```

As we are at it shouldn't `summary` & `histogram` vectors be made more consistant ? e.g. :

```
# HELP azure_api_call_duration_seconds_quantile Quantiles of Azure Batch API calls durations in seconds over last 10 minutes or last 50000 observations
# TYPE base_name_quantile summary
azure_api_call_duration_seconds_quantile{...,eq="0.99"} x
azure_api_call_duration_seconds_quantile{...,eq="0.95"} x
...
# HELP azure_api_call_duration_seconds Histograms of Azure Batch API calls durations in seconds
# TYPE azure_api_call_duration_seconds histogram
azure_api_call_duration_seconds_bucket{...,le="0.01"} x
azure_api_call_duration_seconds_bucket{...,le="0.02"} x
azure_api_call_duration_seconds_bucket{...,le="0.03"} x
...
azure_api_call_duration_seconds_bucket{...,le="+Inf"} x
azure_api_call_duration_seconds_sum{...} x
azure_api_call_duration_seconds_count{...} x
```
Regards.

**Comment by sylr** [comment]
@beorn7 can I have your thoughts about this ?

**Comment by beorn7** [comment]
To make this work, we would need to introduce a new metric type, not only here in client_golang, but throughout the Prometheus ecosystem. Actually, by now this would be an issue of OpenMetrics. Thus, if you really wanted to get this added, you would need to file an issue in https://github.com/OpenObservability/OpenMetrics .

In the meantime, I recommend to simply have two separate metrics with a slightly different name as a work around.

**Comment by beorn7** [comment]
Also, if you wonder why the text format is as it is, I recommend to read https://github.com/OpenObservability/OpenMetrics/blob/master/markdown/protobuf_vs_text.md and https://docs.google.com/presentation/d/1WUSerlBAB6I6jz6Vo3d6VScCgMk7eOrTCOCJZIcjnyc/edit?usp=sharing .

In short: Yes, the text format representations of histograms and summaries are weird in various aspects, they were not meant to be used "in production" in that way, but as things happen, they are what they are now.

OpenMetrics is the project in charge of standardizing a common metrics exposition format. Prometheus doesn't intend to change things on its own. Should OpenMetrics include a combined Summary/Histogram, a future version of client_golang would certainly support it.

Thus, as before, I think this should be an issue in https://github.com/OpenObservability/OpenMetrics
