### ISSUE TITLE
[Feature Request] Support PromQL in HTTP API

### ISSUE THREAD

**Issue by ihac** [prometheus/client_golang#507]
Hi, thanks for your work on Prometheus and its HTTP API.
Currently I'm using HTTP API to query metrics from Prometheus server. I wonder whether it is possible to integrate PromQL into HTTP API, so that users'll be able to get what they want just by using a raw PromQL expression, without doing selection/aggregation on their own.

**Comment by beorn7** [comment]
I'm not quite sure what you are shooting for.

The HTTP API of the Prometheus server _is_ using PromQL. The `query` parameter of a `/api/v1/query` or `/api/v1/query_range` request is PromQL, and those endpoints are also supported in the client for the API. Soo https://prometheus.io/docs/prometheus/latest/querying/api/#expression-queries and https://godoc.org/github.com/prometheus/client_golang/api/prometheus/v1#API for details.

**Comment by ihac** [comment]
Thanks @beorn7 
I thought the `query` parameter only support the metric name. I tried using PromQL expressions in `query` and it did work. Sorry that I was unfamiliar with Prometheus' API.
I'll close this issue.
