### ISSUE TITLE
Timer.ObserveDuration should returned the observed duration

### ISSUE THREAD

**Issue by eklitzke** [prometheus/client_golang#509]
The following usage example is given in the docs:
```go
func TimeMe() {
    timer := NewTimer(myHistogram)
    defer timer.ObserveDuration()
    // Do actual work.
}
```

I find that I typically want to also emit durations in log statements. Therefore it would be useful if `ObserveDuration()` returned the observed duration (probably as a `time.Duration`, but I could see a case being made for the value as a `float64`), which would allow code like the following:

```go
func TimeMe() {
    timer := NewTimer(myHistogram)
    defer func() { log.Printf("finished in %f seconds", timer.ObserveDuration().Seconds()) }()
    // Do actual work.
}
```

**Comment by beorn7** [comment]
Sounds like a convenient and reasonable thing to do. And easy to implement. :o)
