### ISSUE TITLE
feature: get descriptor attributes functions 

### ISSUE THREAD

**Issue by greenpau** [prometheus/client_golang#516]
To ease the documentation of exporters, I read descriptors in the following way:

```
        fmt.Fprintf(os.Stdout, "| Metric | Description | Labels |\n")
        fmt.Fprintf(os.Stdout, "| ------ | ------- | ------ |\n")
        e := &exporter.MyMetric{}
        metrics := make(chan *prometheus.Desc, 100000)
        e.Describe(metrics)
        close(metrics)
        for metric := range metrics {
            m := metric.String()
            fmt.Fprintf(os.Stdout, "%s\n", m)
        }
        os.Exit(0)
```

That yields:

```
| Metric | Description | Labels |
| ------ | ------- | ------ |
Desc{fqName: "net_node_up", help: "Is node up and responding to queries (1) or is it down (0).", constLabels: {}, variableLabels: [node]}
```

I could parse out relevant parts to get `fqName`, `help`, etc. However, I would love to have helper functions.

Here, at https://github.com/prometheus/client_golang/blob/master/prometheus/desc.go#L169, there is `String()` function.

I propose adding the following "public" functions:

* GetName()
* GetHelp()
* GetLabels()

I can submit a PR for it. Worth it?

**Comment by beorn7** [comment]
Thanks for your thoughts.

Descs are up for a major rehaul in the upcoming v0.10, see #222. I would prefer to not try to make the current Descs more sophisticated at this point, just to break everybody anyway in a few months. Depending on the exact new way Descs will be handled, accessors as you suggest might be something we could add, or they might become not needed (if, for example, a Desc is created by an Opts struct whose fields are exported anyway). Cannot really say at the moment, as the design is still evolving.

**Comment by beorn7** [comment]
I'll close this now, but it will be taken into account when working on #222.

**Comment by greenpau** [comment]
@beorn7 , actually i made it prettier and. More useful here. 
https://github.com/ovnworks/gobgp_exporter/blob/master/pkg/gobgp_exporter/metric_table.go

This way it could be integrated as help.

**Comment by beorn7** [comment]
Many thanks. I'll keep it in mind.
