### ISSUE TITLE
TestCounterAddLarge fails on some architectures

### ISSUE THREAD

**Issue by xnox** [prometheus/client_golang#530]
```
s390x:
=== RUN   TestCounterAddLarge
--- FAIL: TestCounterAddLarge (0.00s)
	counter_test.go:178: valBits expected 18446744073709551616.000000, got 0.000000.
	counter_test.go:181: valInts expected 0, got 18446744073709551615.

ppc64el:
=== RUN   TestCounterAddLarge
--- FAIL: TestCounterAddLarge (0.00s)
	counter_test.go:178: valBits expected 18446744073709551616.000000, got 0.000000.
	counter_test.go:181: valInts expected 0, got 18446744073709551615.

arm64:
=== RUN   TestCounterAddLarge
--- FAIL: TestCounterAddLarge (0.00s)
	counter_test.go:178: valBits expected 18446744073709551616.000000, got 0.000000.
	counter_test.go:181: valInts expected 0, got 18446744073709551615.
```

Otherwise passes on `amd64 i386 armhf`. Not sure if this is indicative of a 64-bit issue on the niche arches.

Version 0.9.0-1

**Comment by beorn7** [comment]
Ooops, yeah, well possible. I'll need to think about it. Input welcome…

**Comment by xnox** [comment]
Let me see if a2facc3074da810dcfc1d6251e03964fd80bce9d fixes this first.

**Comment by xnox** [comment]
So that test case fails in current master tip, and in the original commit it was introduced in on ppc64el.....

I wonder if you are not expecting 128bit precision on ppc64el for example. I think I will patch that test case out for now in ubuntu.

**Comment by beorn7** [comment]
Finally got to think about this. I think it's just a slightly different way how integers too large to be represented precisely with a float64 are converted. I'm going to create a PR that should make things cleaner and more robust.
