### ISSUE TITLE
promhttp: Consider a metric for HTTP exposition errors

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#543]
There are cases where an error won't or cannot be sent as an HTTP response with the appropriate status code (examples: `ContinueOnError` as configured error handling, #542 ). While those problem should be caught be logs, it is better if alerts can be set up for those problems. Thus, `promhttp` should add an error counter as a metric.

**Comment by brian-brazil** [comment]
Could we remove ContinueOnError?

One thing to consider is that OpenMetrics requires an explicit eof marker, so this won't be a problem there.

**Comment by beorn7** [comment]
It's in active and meaningful use at several places, most prominently the node exporter (where otherwise dropping an ill-advised file for the textfile collector can bring down your complete host-based monitoring).
