### ISSUE TITLE
Allow retrieving the descriptor of a metricVec

### ISSUE THREAD

**Issue by gebn** [prometheus/client_golang#547]
I'm writing a new exporter which exposes a labelled counter. It would be really useful to be able to access the underlying descriptor for sending in the custom collector's `Describe()` method. The descriptor is created when `NewCounterVec()` is called, but only stored within each metric, meaning it is necessary to resolve a single time series from the vector to access a descriptor, which seems messy.

I think this would look like adding a `Desc() *Desc` method to `*metricVec` returning the descriptor for the vector, similar to how it currently is for a `Metric`. If this sounds sane, and there isn't already a better way of doing it, I'm happy to create a PR.

**Comment by beorn7** [comment]
Since `CounterVec` itself implements `Collector`, you can simply call `yourCounterVec.Describe(descChan)`.

Or am I missing something?

**Comment by brian-brazil** [comment]
Hmm, if you're writing an exporter you usually want MustNewConstMetric rather than NewCounterVec and friends.

**Comment by gebn** [comment]
You’re both quite right, this is a completely invalid thing to want to do. The `CounterVec` was for direct instrumentation of the collector itself and I was wrongly trying to send its descriptor down the channel passed to `Describe()`. I am indeed using `ConstMetric` for the indirect parts, thanks to the video of your [talk](https://youtube.com/watch?v=KXq5ibSj2qA) at PromCon ‘17 @brian-brazil!

Even when I tried a workaround (using `WithLabelValues()` to force the vector to give me a metric I could call `Desc()` on), the validation on `Describe()` caught it saying an identical descriptor had already been registered.

What a great library - making it hard to do the wrong thing, even when you push back!
