### ISSUE TITLE
Opt-out mechanism for compiling process_collector.go

### ISSUE THREAD

**Issue by carlpett** [prometheus/client_golang#549]
On Google App Engine, importing `syscall` is not allowed, which leads to being unable to compile the ProcessCollector.

 I've locally patched this by splitting it into different files up so the bare minimum (`ProcessCollectorOpts` and `NewProcessCollector`) are exposed when `+build !linux appengine`, or the existing file when `+build linux,!appengine`.

Would this patch be accepted/interesting? Or are there better ways to accomplish this?

**Comment by beorn7** [comment]
Do I understand correctly that it is the import of the `syscall` package that causes an compile error an app engine?

In that case, it should certainly be protected by a build tag. But that change would be in https://github.com/prometheus/procfs/blob/master/internal/util/sysreadfile_linux.go , i.e. in a different repo.

**Comment by beorn7** [comment]
NB: That touches a discussion we had earlier: Should the user of the `procfs` package decide if the hosting platform is supporting it and thus importing it or not, or should the `procfs` package itself decide about it? Currently, the latter is implemented, e.g. on MS Windows, the `procfs` package compiles but `procfs.NewStat()` always returns an error. To stay consistent with that pattern, the `procfs` can do the same for appengine as a platform.

**Comment by carlpett** [comment]
Yes, that is correctly understood. And yes, putting a build constraint on `sysreadfile_linux.go` seems like a much neater solution than what I did. Apparently I spent too little time looking at how it works. I'll do a PR on that repo. Thanks!

As for the larger discussion, to my mind the current approach seems reasonable. How would it work instead, and is there reason to believe the other approach would be better?

**Comment by beorn7** [comment]
I think it's matter of taste: Is the procfs package a package that just works on (non-appengine) Linux and must not be used elsewhere? Or is it a package that you can use anywhere, but it will only give you limited or even no information at all on incompatible platforms? In the former case, the user has to decide if it is appropriate to use the package. In the latter case, the logic of the suitability of the package is baked into the package itself.

I tend to consider the latter (and current) way more useful. It also allows partial functionality (e.g. some BSD that might have a proc filesystem but will only support some of the features known from Linux).
