### ISSUE TITLE
Get rid of Makefiles?

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#55]
They shouldn't be required anymore...

**Comment by juliusv** [comment]
Beware, the Makefile and tutorial at http://prometheus.github.io/docs/introduction/getting_started/ were just expanded by @brian-brazil to enable a smoother tutorial experience (e.g. not requiring a Go setup). So I'm not sure whether we should still get rid of it.

**Comment by beorn7** [comment]
That's for the example targets... yeah, good point, they should still work without a Go installation.

**Comment by brian-brazil** [comment]
I'd argue that everything should work without a Go installation, and that builds shouldn't pick up local versions of libraries either (which may require a go get -u).

**Comment by beorn7** [comment]
Having looked at the Makefile, it is actually in quite good shape. Closing...
