### ISSUE TITLE
prometheus/promhttp: scrape authentication

### ISSUE THREAD

**Issue by greenpau** [prometheus/client_golang#550]
At times, it may be necessary to secure access to an exporter. One way of doing it is firewalling. Another way is implementing token authentication.

Recently, I worked on an exporter where I implemented token authentication.

Here is a section explaining the mechanics https://github.com/greenpau/network_exporter#security-first and some code:

- https://github.com/ovnworks/gobgp_exporter/blob/master/pkg/gobgp_exporter/auth.go#L25-L66
- https://github.com/ovnworks/gobgp_exporter/blob/baaf7fa35f9a4c548bbf8bcf799a61a9c3681a93/pkg/gobgp_exporter/http_summary.go#L25-L29

Next, I started thinking about making it a part of this package. I was thinking that the below function is the best place to incorporate authentication:

https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/http.go#L92

Question: do you think it is a good idea and worth implementing?

**Comment by brian-brazil** [comment]
The current plan of record is to offer TLS and basic auth, which is in progress. There's no plan to support other or non-standard authenthication mechanisms.

**Comment by greenpau** [comment]
> The current plan of record is to offer TLS and basic auth, which is in progress.

@brian-brazil , when is the basic auth will be available?

**Comment by beorn7** [comment]
IIUC, the plan is to first implement TLS in node_exporter (see https://github.com/prometheus/node_exporter/pull/1277 ). I don't know any pointer to basic auth work in progress.

Depending on how it goes there, we can put a generalized solution in some package. 

At the moment, I don't think it will go into `promhttp` as that package is only about providing a handler to serve Prometheus metrics via HTTP. Any authentication should be done outside of that handler.

I actually don't think it should go anywhere into prometheus/client_golang at all as the implementation will be used for other HTTP serving endpoints in the Prometheus ecosystem as well (Prometheus API, Alertmanager, …). I would think prometheus/common is a better place.

But we'll see once that prototypical implementation in node_exporter is done. To avoid confusion and misdirected expectations, I'm closing this issues for now.
