### ISSUE TITLE
Improve performance WRT mutexes

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#56]
Will sync.atomic help? Investigate.

**Comment by brian-brazil** [comment]
Related: https://github.com/prometheus/client_java/blob/master/benchmark/README.md

The java client manages 12-17ns per Counter increment.

**Comment by beorn7** [comment]
Now we are down to below 10ns for setting a Gauge. Yay!

The two main uses of mutexes left are for vectors and for summaries. I don't see a way around them for the former, but if performance matters, the metric object can be retrieved once, and then all the updates can be performed on the metric directly. That has always been well documented.

Summaries are anyway inherently slow because they are doing so much more. Perhaps there is a slow optimization potential (using some channel based approach), but it would be complex and can only shave off a few percent if at all.

Closing this.
