### ISSUE TITLE
Add "storage.Warnings" to api client

### ISSUE THREAD

**Issue by jacksontj** [prometheus/client_golang#560]
Prometheus has added warnings to the HTTP API -- as it stands today this client doesn't parse/return those warnings. This should simply be adding the warnings return to:

- Query()
- QueryRange()
- Series()

Assuming this is non-controversial I can definitely submit a PR with this feature.

**Comment by krasi-georgiev** [comment]
I am not familiar what are these warning for and how should these be handled. Can you add a bit more context with links to the docs or code.

**Comment by jacksontj** [comment]
These warning were added in https://github.com/prometheus/prometheus/pull/4832 so now the API response includes a warning section which is crucial to have, since it now is a way to annotate a failure to read a remote read endpoint. Personally it seems like a messy solution to the problem, since you now have to check error and warning and if you care about data completeness either is a failure... But unfortunately it was added upstream so the client (imo) should support it.

**Comment by krasi-georgiev** [comment]
Yep it makes sense to add here so I am happy to review a PR. 

> Personally it seems like a messy solution to the problem,

I am just curious, what would you consider a better solution?

**Comment by jacksontj** [comment]
> I am just curious, what would you consider a better solution?

These remote-reads are also errors, so IMO they should be treated as such. If prom wanted to make *some* errors be ignored that would have been a better option IMO. As it stands today if you have a warning in the response its unclear if the data you have is authoritative or not (if you asked for data only in the cache range vs outside of the cache range). If the data is still authoritative a warning isn't useful, if it isn't then its an error (as the result is *wrong* since it is missing data). IMO no need for warnings.

A more understandable use of warnings would be for prom to add warnings about specific matchers taking too long or matching too many series, but this add for remote_read seems wrong.

**Comment by brian-brazil** [comment]
Only local storage is critical, we don't want to take out monitoring because a clustered storage system is down.

**Comment by jacksontj** [comment]
> Only local storage is critical, we don't want to take out monitoring because a clustered storage system is down.

I don't disagree, what I'm saying is that the storage layers there should be more configurable. If the user wants remote_read errors to be fatal they should be-- and those errors would be errors (in the regular error return). If they don't want them to be fatal, they wouldn't be errors (meaning nothing returned to the client). It seems odd to add an entire new return type `warnings` which is actually just `[]error` just for this very specific use-case.

But, as I said before: 

> it was added upstream so the client (imo) should support it.
