### ISSUE TITLE
JSON Unmarshaling of large responses is excessively expensive

### ISSUE THREAD

**Issue by jacksontj** [prometheus/client_golang#565]
This is basically the same issue as https://github.com/prometheus/prometheus/issues/3601 and https://github.com/prometheus/prometheus/pull/3536

The current api client here uses the base `encoding/json` which is both slow and memory inefficient. For large responses it can generate garbage >10x the size of the response data. So, ideally we'd use a better (read: faster) json library. Upstream prom uses json-iter -- so presumably we'd do the same here?

Thoughts @krasi-georgiev

**Comment by krasi-georgiev** [comment]
Yep that sound good. PR is welcome.
