### ISSUE TITLE
Regression on wrappers that implement push

### ISSUE THREAD

**Issue by cviecco** [prometheus/client_golang#574]
I found a regression on: 
1173d734050af725504a9b2fbe93bff0b16f1b53

Go version
go version go1.12.5 linux/amd64

OS:
Centos 7:  kernel 3.10.0-957.5.1.el7.x86_64

Overall Code around:
This is around a logger package that wraps the http handler for filtering certain urls.
https://github.com/Symantec/keymaster/blob/master/cmd/keymasterd/logFilter.go
This has also been wrapped by a instrumentation wrapped used to generate access logs for the service

Panic Message:
2019/05/14 00:13:32 http2: panic serving 10.180.95.26:54345: runtime error: invalid memory address or nil pointer dereference
goroutine 88 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010040, 0xc000052faf, 0xc0001ab080)
	/usr/local/go/src/net/http/h2_bundle.go:5651 +0x16b
panic(0xb655c0, 0x13bc160)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/prometheus/client_golang/prometheus/promhttp.newDelegator(0xd25820, 0xc0000e4000, 0x0, 0x14119a0, 0x7fa2b8e7b2e8)
	/home/camilo_viecco1/go/src/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go:228 +0x18e
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xd25820, 0xc0000e4000, 0xc000204400)
	/home/camilo_viecco1/go/src/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:99 +0x6d
net/http.HandlerFunc.ServeHTTP(0xc000282450, 0xd25820, 0xc0000e4000, 0xc000204400)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x140ad20, 0xd25820, 0xc0000e4000, 0xc000204400)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
main.(*logFilterType).ServeHTTP(0xc000290b00, 0xd25820, 0xc0000e4000, 0xc000204400)
	/home/camilo_viecco1/git/keymaster/cmd/keymasterd/logFilter.go:52 +0x79
github.com/Symantec/keymaster/lib/instrumentedwriter.(*LoggingHandler).ServeHTTP(0xc000290b20, 0xd26320, 0xc000010040, 0xc000204400)
	/home/camilo_viecco1/go/src/github.com/Symantec/keymaster/lib/instrumentedwriter/instrumentedWriter.go:189 +0x375
net/http.serverHandler.ServeHTTP(0xc000295a00, 0xd26320, 0xc000010040, 0xc000204400)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc00011c700, 0xc000295a00, 0xd26320, 0xc000010040, 0xc000204400)
	/usr/local/go/src/net/http/server.go:3323 +0x8d
net/http.(*http2serverConn).runHandler(0xc0001ab080, 0xc000010040, 0xc000204400, 0xc0003cc2e0)
	/usr/local/go/src/net/http/h2_bundle.go:5658 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5392 +0x4f4
 
This is triggered when the metrics path is being called.
2019/05/14 00:13:32 http2: panic serving 10.XXX.XXX.XXX:54345: runtime error: invalid memory address or nil pointer dereference
goroutine 88 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010040, 0xc000052faf, 0xc0001ab080)
	/usr/local/go/src/net/http/h2_bundle.go:5651 +0x16b
panic(0xb655c0, 0x13bc160)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/prometheus/client_golang/prometheus/promhttp.newDelegator(0xd25820, 0xc0000e4000, 0x0, 0x14119a0, 0x7fa2b8e7b2e8)
	/home/camilo_viecco1/go/src/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go:228 +0x18e
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xd25820, 0xc0000e4000, 0xc000204400)
	/home/camilo_viecco1/go/src/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:99 +0x6d
net/http.HandlerFunc.ServeHTTP(0xc000282450, 0xd25820, 0xc0000e4000, 0xc000204400)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x140ad20, 0xd25820, 0xc0000e4000, 0xc000204400)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
main.(*logFilterType).ServeHTTP(0xc000290b00, 0xd25820, 0xc0000e4000, 0xc000204400)
	/home/camilo_viecco1/git/keymaster/cmd/keymasterd/logFilter.go:52 +0x79
github.com/Symantec/keymaster/lib/instrumentedwriter.(*LoggingHandler).ServeHTTP(0xc000290b20, 0xd26320, 0xc000010040, 0xc000204400)
	/home/camilo_viecco1/go/src/github.com/Symantec/keymaster/lib/instrumentedwriter/instrumentedWriter.go:189 +0x375
net/http.serverHandler.ServeHTTP(0xc000295a00, 0xd26320, 0xc000010040, 0xc000204400)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc00011c700, 0xc000295a00, 0xd26320, 0xc000010040, 0xc000204400)
	/usr/local/go/src/net/http/server.go:3323 +0x8d
net/http.(*http2serverConn).runHandler(0xc0001ab080, 0xc000010040, 0xc000204400, 0xc0003cc2e0)
	/usr/local/go/src/net/http/h2_bundle.go:5658 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5392 +0x4f4

Is there any simplified code for trying to reproduce this? How else can I help on issue reporuction?

**Comment by beorn7** [comment]
I guess #576 fixed this.

**Comment by cviecco** [comment]
yes it did.

**Comment by beorn7** [comment]
And thanks again for noticing and fixing.
