### ISSUE TITLE
Why the API does not leverage the reflection

### ISSUE THREAD

**Issue by larytet** [prometheus/client_golang#575]
For example, 

I could call prometheus.NewCounter for all fields of a structure and save a few lines of initialization code. For example 

Given a structure 
```Go
var statistics struct {
  CacheHit prometheus.Counter // `name:CacheHit;comment:Number of times the data was found in the cache`
}
```

I could just do 
```Go
RegisterPrometheusCounters(&statistics)
````

Where RegisterPrometheusCounters() is 
```Go
var reStructureTag = regexp.MustCompile(`(?m)name:(\S+);comment:(\S+)`)
func RegisterPrometheusCounters(data interface{}) {
	fmt.Printf("Registering prometheus counters\n")
	v := reflect.ValueOf(data).Elem()
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		vfield := v.Field(i)
		tag := string(field.Tag)
		fieldComment := ""
		fieldName := field.Name
		if len(tag) == 0 {
			tag = fieldName
		}

		if match := reStructureTag.FindStringSubmatch(tag); match != nil {
			fieldName = match[1]
			fieldComment = match[2]
		}

		newCounter := prometheus.NewCounter(prometheus.CounterOpts{
			Name: fieldName,
			Help: fieldComment,
		})
		vfield.Set(reflect.ValueOf(newCounter))
		prometheus.Register(newCounter)
		fmt.Printf("\t%v\n", field.Name)
	}
}
```

**Comment by beorn7** [comment]
Have you had a look at https://godoc.org/github.com/prometheus/client_golang/prometheus/promauto ?

It appears to me your helper function will essentially transform the multi-line `...Opts` initialization into a one liner that requires a tag of a certain format.

While I could see the appeal of your helper function in certain situations, I don't think we should have it in the client library itself. The benefit is essentially a bit of syntactic sugar, while we lose compile-time checks, and we add the burden of reflection (meant in terms of readability and clarity – performance doesn't play a role here).

To quote from https://go-proverbs.github.io/ :
- Clear is better than clever.
- Reflection is never clear.

**Comment by larytet** [comment]
Typically I have between 50 to 100 debug counters per process. Without this small helper my initialization code would be quite large.

**Comment by beorn7** [comment]
I see how it will cut down the line count. But semantically, it doesn't simplify your code.
You are trading a more compact syntax against less checkability by the compiler. (For example, if you mistype `CounterOpts{ Naame: "foobar }`, the compiler will notice. If to mistype  the tag like `// naame:foobar`, you'll only notice during runtime.)

Plus what I said above about being judicious with the complexity and “magic” of reflection. I'd say that the typical Go mindset wouldn't consider reducing syntactic line count as a good reason to use reflection.

Your helper might make sense in your situation, but I don't think we should put something like this in the official client library. I hope you'll understand.

**Comment by larytet** [comment]
Just in case anyone finds it here is the package https://github.com/larytet-go/prometheus-golang
