### ISSUE TITLE
Request context is overridden in instrumented http clients

### ISSUE THREAD

**Issue by shturec** [prometheus/client_golang#580]
It is quite common for golang http clients to make use of the `context` package. Example use cases are to halt stalled requests or shutdown appropriately for example. When an application uses the `github.com/prometheus/client_golang/prometheus` package to instrument an http client for metrics, it expects the transport wrappers to preserve the behavior and state of the wrapped client.   

However, what happens with a request context set before the instrumentation of the client is that it gets [replaced by the default root context](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go#L216)  and that makes quite of a difference:
```
r = r.WithContext(httptrace.WithClientTrace(context.Background(), trace))
```
From the [golang docs](https://golang.org/pkg/net/http/#Request.WithContext): 
"WithContext returns a shallow copy of r **with its context changed to ctx.**"

The effect is that if you created a context with, for example, `context.WithTimeout` and set it to a `http.Client` (`client.WithContext(ctx)`), and then instrument the client, for example as suggested [here](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client_test.go#L107-L186), and then send requests to a server that is slow enough to trigger timeout, the timeout will never occur.

What is expected instead is that the [`InstrumentRoundTripperTrace`](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go#L136) function respects existing request context, if any.

All findings are wrt [`v0.9.2`](https://github.com/prometheus/client_golang/blob/v0.9.2/prometheus/promhttp/instrument_client.go) and [`master`](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_client.go).

**Comment by beorn7** [comment]
Thanks for the report.

I assume this is only an issue with the `InstrumentRoundTripperTrace` function. Please let me know if that's not true.
