### ISSUE TITLE
missing "/targets/metadata" in the "api/prometheus/v1/api.go"

### ISSUE THREAD

**Issue by YaoZengzeng** [prometheus/client_golang#587]
The "/targets/metadata" is useful when trying to know all the metrics of a target.

I'd like to contribute if it's necessary :)

**Comment by beorn7** [comment]
I'll leave it to @krasi-georgiev to make the call.

**Comment by krasi-georgiev** [comment]
@YaoZengzeng sure, please open the PR , ping me and I will have a look.
