### ISSUE TITLE
Errors using go get

### ISSUE THREAD

**Issue by hopkins-space** [prometheus/client_golang#592]
I am doing a
go get -u github.com/prometheus/client_golang/prometheus

Which I assume pulls from the master branch and I am getting these errors

../../../go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:129:15: undefined: procfs.NewStat
../../../go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:169:19: p.NewStat undefined (type procfs.Proc has no field or method NewStat)
../../../go/src/github.com/prometheus/client_golang/prometheus/process_collector.go:188:21: p.NewLimits undefined (type procfs.Proc has no field or method NewLimits)

Let me know if you need more info.

Thanks.

**Comment by sbramin** [comment]
Related to https://github.com/prometheus/procfs/pull/162

**Comment by sbramin** [comment]
Related to https://github.com/prometheus/procfs/pull/162

**Comment by BlizzTom** [comment]
Confirmed with Go Dep as well.

**Comment by beorn7** [comment]
Would not have happened if prometheus/procfs had version tags... :o)

I guess we can just pin to a commit in go.mod.

**Comment by pgier** [comment]
Created https://github.com/prometheus/procfs/pull/168 to hopefully resolve this.
I agree we need version tags in procfs, I'll work on creating those.
I thought go.mod is already pinned to a specific procfs version?

**Comment by peterbourgon** [comment]
Not all consumers are module-aware.

**Comment by pgier** [comment]
I've re-added the three required functions to procfs and also added a v0.0.1 tag for the pre-refactored code.

**Comment by peterbourgon** [comment]
Works now, thanks!

**Comment by beorn7** [comment]
Go Modules are only locked to versions by default. Locking to a specific commit has to happen explicitly.
