### ISSUE TITLE
api/V1 Query signature changed

### ISSUE THREAD

**Issue by verdverm** [prometheus/client_golang#602]
The following function signature change broke a lot of downstream users code. This is in the case that they rely on go getting `github.com/prometheus/client_golang/api/prometheus/v1` (not using dependency management tool).

https://github.com/prometheus/client_golang/pull/599/files#diff-4f30009d9ef316a0175312cc1739f05fR233

Does an API change like this deserve a `github.com/prometheus/client_golang/api/prometheus/v2` ?

**Comment by beorn7** [comment]
Yeah, sorry for that.

The `v1` in the path is referring to the version of the Prometheus HTTP API, not the version of the API _client_ code. Thus, adding a `v2` directory would be very confusing.

Versioning the client code is a different thing. It will happen soon for this repo (v1 to be released possibly today, would will allow the major-version handling that Go Modules provides.) However, the API client is still very experimental and will still be marked as such, even while the rest of this repo will follow semver very soon. It is a misfit that the API client shares fate with the exposition client in the same repo. That decision was made long ago before dependency without considering the consequences for dependency management (and, to be fair, back then there was no established way of dependency management to use as a guideline).

We might separate out the API client one day or go down the rabbit hole of a multi-module repo. Most likely, we'll one day simply include it in the semver semantics. But for now, you have to live with the status quo of the occasional breaking change. You have to lock your vendoring to a certain commit if you want to use the old-style function signature.

Sorry again…

(@krasi-georgiev please chime in if there is anything to add. I'll close this for now.)

**Comment by krasi-georgiev** [comment]
nothing to add, quite unfortunate indeed, and I would also advise locking to specific commit for now.
