### ISSUE TITLE
Wrapped Register does not play well with AlreadyRegisteredError

### ISSUE THREAD

**Issue by lukedirtwalker** [prometheus/client_golang#605]
We use abad2d1bd44235a26707c172eab6bca5bf2dbad3 but I checked the code and the problem is still in 1335ef46bddd1cb120c21240851f292904aa91f6

*Problem:* If you register something in a wrapped register it can't be recovered from an AlreadyRegisteredError

```go
        // set default registry
        labels := prometheus.Labels{"foo": "bar"}
	reg := prometheus.NewRegistry()
	prometheus.DefaultRegisterer = prometheus.WrapRegistererWith(labels, reg)
	prometheus.DefaultGatherer = reg

	g := prometheus.NewGauge(prometheus.GaugeOpts{
		Name:        "mygague",
		Help:        "Help for the gauge",
	})
```
Now check for already registered error according to example in GoDoc
```go
	if err := prometheus.Register(g); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			g = are.ExistingCollector.(prometheus.Gauge)
		} else {
			panic(err)
		}
	}
```
Result: `Panic msg="interface conversion: *prometheus.wrappingCollector is not prometheus.Gauge: `

The user of the API has no possibility to cast to wrappingCollector and extract the underlying collector.

So either the doc should discourage the usage of `AlreadyRegisteredError` when using a wrapped registry or we should make the underlying collector somehow accessible.

**Comment by beorn7** [comment]
Thanks for the catch. I'll think about it if we can unwrap the original collector.
