### ISSUE TITLE
Add support for timestamped metrics in NewGaugeVec

### ISSUE THREAD

**Issue by TriAnMan** [prometheus/client_golang#616]
Currently timestamped metrics as proposed by NewMetricWithTimestamp() breaks all usage flow, expected from NewGaugeVec() and other similar methods.
Actually a timestamped metric feels like something not incorporated into a main library usage flow at all.

**Comment by beorn7** [comment]
That's deliberate. What you call the “main library usage flow” is probably what we usually call “direct instrumentation”. For that, you should never set a timestamp explicitly.

The use case for setting a timestamp is if you mirror already existing metrics data from another system. That's done with `NewConstMetrics` and friends, and that's where the `NewMetricWithTimestamp` helper kicks in.

**Comment by TriAnMan** [comment]
Hmm... For my mind it'n not a client library's responsibility to force use cases of an underlying framework. I think that a client library's purpose is to facilitate usage of an underlying framework, am I wrong?
So Prometheus digests timestemped metrics, why do the library has to limit an ability to provide them?
For my case, I think that it will take less effort to produce a metrics page without this library than figure out the way to do this page with it (I have already spent a day trying to do this).

I understand that Prometheus was built to deal with metrics, but it's powerful and fascinating query language drives me to find a way to make queries on event related metrics. Events in contrast have a strong bound with timestamps. I'm OK with loosing some of events when they are converted into metrics, but I really don't want to lose timestamps.

**Comment by beorn7** [comment]
> For my mind it's not a client library's responsibility to force use cases of an underlying framework. I think that a client library's purpose is to facilitate usage of an underlying framework, am I wrong?

I wouldn't go as far as calling something wrong or right. It's more like what's the design philosophy of a library or a whole ecosystem, and what is aligned with it and what is not. Among the Prometheus developers, there is a strong believe that the Prometheus client libraries should make it easy to use Prometheus in the intended way and make it hard or even impossible to do things in the wrong way.

> So Prometheus digests timestemped metrics, why do the library has to limit an ability to provide them?

The timestamps are meant for federation and for mirroring metrics from other systems. The former is implemented in the Prometheus server itself and not the concern of a client library. The latter is fully supported by the client libraries through the const-metric mechanism.

Of course, we can never completely rule out that there is one very special use case out there which is again different. I'm in general in favor of providing power users with the sharp tools (big warning sign attached), but not if it makes the usual use cases harder. The current Go client library is already quite complex to handle (so complex that several people have created more lightweight libraries with a subset of features) that I don't want to add features for which relevant use cases are extremely rare (if they exist at all). 

I also fully acknowledge that one client library cannot cover all use cases equally well. The Prometheus exposition format is simple enough that creating your own library for a special use case is a viable option (and has happened in real life, e.g. in kube-state-metrics). Even "library-less" exposition is a thing (e.g. just use your languages variety of printf to create that one line of Prometheus text format directly – back in the days when the Prometheus server still supported the protobuf format, you could even use the raw protobuf types, a feature that might come back one day).

Finally, speaking of events: Prometheus is really really really extremely bad as an event-logging system. I can only recommend to use another system for that. There are many, and they have nice query languages, too. But if you really want to shoehorn Prometheus into it, you should still be able to use the const metrics for it.

This kind of discussion, BTW, is way better suited for the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). We use GH issues mainly to track bugs and feature requests. Discussions about feature requests are fine as long as they deal with just this repo specifically or with the way to implement them. However, if a discussion touches overarching principles of Prometheus, or if it is more about how to use the client library, it's better to have it on the mailing list, where more people are available to chime in and more people will benefit from it.

Thus, I'm closing this issue now. Feel free to open a thread on the mailing list if you have more questions. Should the discussion result in the conclusion that we need a new feature in the library, we can re-open this.
