### ISSUE TITLE
Windows API change on GetCurrentProcess is breaking the lib

### ISSUE THREAD

**Issue by alexvaut** [prometheus/client_golang#642]
On windows 10, just get the last release: 
> go get github.com/prometheus/client_golang/prometheus/promauto
> C:\...\github.com\prometheus\client_golang\prometheus\process_collector_windows.go:78:9: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values

It seems related to this change: https://github.com/golang/sys/commit/2dccfee4fd3e23e10ba17b9d696cf2388c28764b
There are other lib broken because of this change: https://github.com/golang/go/issues/34461

go version go1.12.4 windows/amd64

**Comment by zshearin** [comment]
ran into same problem - #643 fixes

**Comment by anjiawei1991** [comment]
same problem. 

I think upgrade the dependency `golang/x/sys` in this module and remove the err can fix it
