### ISSUE TITLE
release version using prometheus/common@0.7.0

### ISSUE THREAD

**Issue by TimSatke** [prometheus/client_golang#649]
`prometheus/common@0.7.0` uses `sirupsen/logrus@1.4.2`, which resolves `(CVSS 5.9) Vulnerability due to usage of golang.org/x:crypto:0.0.0-20180904163835-0709b304e793` (sirupsen/logrus#1035).

**Comment by brian-brazil** [comment]
I don't believe this repo actually uses that code.

**Comment by beorn7** [comment]
golang.org/x/crypto/ssh/terminal.IsTerminal is the only code logrus 1.2.0 uses in the crypto package.
I don't see how the vulnerability will affect this function. 

Furthermore, client_golang isn't using the `log` packages in prometheus/common, which is the only one there using logrus.

**Comment by beorn7** [comment]
There will be a release in the not to far future, but I don't see any reason to cut a security fix now.
