### ISSUE TITLE
Please add link to godocs in the github repo description

### ISSUE THREAD

**Issue by jeffwidman** [prometheus/client_golang#656]
Can you add a link to https://godoc.org/github.com/prometheus/client_golang in the repo description?

For example, see how https://github.com/pallets/flask does it

Just makes it super quick to find the godocs from the repo

**Comment by beorn7** [comment]
That's already there. It's the "godoc reference" badge.

**Comment by beorn7** [comment]
In my experience, that badge is fairly common. But if you get lost, this repo is so popular, it's even listed among the "popular packages" on the https://godoc.org landing page. :o)

**Comment by jeffwidman** [comment]
That's fine, I was certainly able to find via Google, I simply posted as I was more used to this kind of thing in other projects... and not just python-based, others as well.

Not a big deal.
