### ISSUE TITLE
Regression: unregistering "builtin" collectors stopped working with 1.2.0

### ISSUE THREAD

**Issue by costela** [prometheus/client_golang#662]
This simple test case showcases the problem:
```go
func TestRegisterUnregisterCollector(t *testing.T) {
	col := prometheus.NewGoCollector()

	reg := prometheus.NewRegistry()
	reg.MustRegister(col)
	reg.Unregister(col)
	if metrics, err := reg.Gather(); err != nil {
		t.Error("error gathering sample metric")
	} else if len(metrics) != 0 {
		t.Error("should have unregistered metric")
	}
}
```
This passed up to v1.1.0, but fails on v1.2.0 (and master).

The calculation of collectorID got changed in 1.2.0 and the same change was not applied to unregistering. PR follows shortly.

**Comment by beorn7** [comment]
Ouch. Thanks for spotting.

Perils of code duplication. But with #663, there will be a test.

**Comment by costela** [comment]
Happy to help! :)

**Comment by beorn7** [comment]
v1.2.1 coming.
