### ISSUE TITLE
glide install fails for xxhash/v2

### ISSUE THREAD

**Issue by Allkoman** [prometheus/client_golang#673]
I'm using golang version 1.13.4 with glide to manage my go package, but I can not install prometheus/client_golang because 

[ERROR]	Error scanning github.com/cespare/xxhash/v2: cannot find package "." in:
	/Users/username/.glide/cache/src/https-github.com-cespare-xxhash/v2

Not like this [issue](https://github.com/prometheus/client_golang/issues/661), update golang version can not help me.  according to [cespare/xxhash](https://github.com/cespare/xxhash/issues/30) , I set my GO111MODULE=on, but I can not install...

**Comment by beorn7** [comment]
I assume that Glide cannot deal with the `v2` path suffix. But I don't know any details about Glide. Perhaps somebody who knows glide better could chime in.

I'd assume it's something that has to be fixed on the side of Glide.

**Comment by Allkoman** [comment]
thx fo the help, I changed my project to use  `go mod vendor` ...

**Comment by Allkoman** [comment]
just say goodbye to glide and using go mod vendor

this works for me in my k8s

```
export GO111MODULE=on && go mod init && go mod vendor
```
