### ISSUE TITLE
Suggest to modify the parameters

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#675]
func NewConstMetric(desc *Desc, valueType ValueType, value float64, labelValues ...string)
func MustNewConstMetric(desc *Desc, valueType ValueType, value float64, labelValues ...string)

Suggest: change labelValues `...string`  to []string,

 Personally think that it is easier to use.

**Comment by beorn7** [comment]
I guess there will always be people leaning towards one side or the other.

In any case, changing it would be a breaking change for one of the most frequently used Go packages. That's a big price for such a small (and disputed) effect.

(Also note that these functions will look very different in v2 of the library, see #222 .)
