### ISSUE TITLE
For loop ?

### ISSUE THREAD

**Issue by sylr** [prometheus/client_golang#676]
I'm not sure to understand why this code is enclosed in a for loop.

https://github.com/prometheus/client_golang/blob/333f01cef0d61f9ef05ada3d94e00e69c8d5cdda/prometheus/histogram.go#L284-L290

Is there some atomic "magic" that requires it ?

**Comment by beorn7** [comment]
It's explained in this classical masterpiece: https://www.youtube.com/watch?v=1V7eJ0jN8-E

Very short version: If this happens concurrently, the compare in `CompareAndSwapUint64` can fail and the whole thing has to be retried.

In general, we don't use GH issues for questions. The [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) is a much better place for this kind of questions. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
