### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#680]
prometheus pull /metrics:

result: unexpected EOF

**Comment by beorn7** [comment]
Could you provide more details? When did this happen? What did you do? What versions were you using? Where is the "result" from?

**Comment by fcddk** [comment]
I have found the cause of the problem.
I add the / metrics interface to my service and expose it to prometheus pull monitoring metrics.
if use the code of version v1.2.1, it is no problem.

**Comment by fcddk** [comment]
The version of the code in question only contains two dirs, push and promhttp, and I can't yet determine which version it belongs to.
But I use the old version of the code to implement my / metrics interface. I can still get the monitoring data through the curl method and I don't see any illegal format errors.
eg:
# HELP cpu_percentage CPU usage.
# TYPE cpu_percentage gauge
cpu_percentage{account="xxx",availableZone="cn-north-3",endpoint="10.110.18.101",localIp="10.110.18.101",region="cn-north-3",resource_id="ecs5577006791947779410",resource_name="6",service="agent-manager",tenant_id="3",type="gauge"} 42.46374970712657

**Comment by fcddk** [comment]
`# HELP cpu_percentage CPU usage.
# TYPE cpu_percentage gauge
cpu_percentage{account="wushuai",availableZone="cn-north-3",endpoint="10.110.18.101",localIp="10.110.18.101",region="cn-north-3",resource_id="ecs5577006791947779410",resource_name="6",service="agent-manager",tenant_id="3",type="gauge"} 42.46374970712657`

**Comment by fcddk** [comment]
I am curious where the differences appear.

**Comment by beorn7** [comment]
I still don't understand what the problem was, but if it is solved for you with the current version, I'll close this.
