### ISSUE TITLE
This product includes software developed at SoundCloud Ltd. (http://soundcloud.com/)

### ISSUE THREAD

**Issue by liuyuan10** [prometheus/client_golang#681]
I see in NOTICES it says:
This product includes software developed at
SoundCloud Ltd. (http://soundcloud.com/).

This is pretty vague. Can we make it clear

- what library is it?
- what license is it?

From existing information I can't make sure if I can use prometheus/client_golang freely.

**Comment by beorn7** [comment]
The whole code is licensed under Apache 2.0. See https://github.com/prometheus/client_golang/blob/master/LICENSE . It doesn't matter who developed the code, the license stays the same. Your only obligation is to include the NOTICE file if you redistribute the code (as described in the license).
