### ISSUE TITLE
Compilation error when building for certain platforms

### ISSUE THREAD

**Issue by a-robinson** [prometheus/client_golang#69]
I'm experimenting with using this library to instrument the core components of [Kubernetes](https://github.com/GoogleCloudPlatform/kubernetes), and have found that it breaks compilation for a couple of the platforms that we target: linux/arm and linux/386 (although to be honest I'm not sure why we build for 386). I may be able to work around the issue within Kubernetes by fixing some unneeded dependencies, but wanted to separately report the issue in case it's not just due to my ineptitude.

This is the exact error I see:
Godeps/_workspace/src/github.com/prometheus/client_golang/prometheus/process_collector_procfs.go:40: p.NewStat undefined (type procfs.Proc has no field or method NewStat)

For context, we've vendored in client_golang and its dependencies using go dep with the most recent versions from github as of last Friday. For more context, [here's a PR](https://github.com/GoogleCloudPlatform/kubernetes/pull/4272) in which I attempt to add a couple metrics to the Kubernetes API server. You can reproduce the test of whether it builds on all platforms by running [build/release.sh](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/build/release.sh) without the change I have that removes linux/arm and linux/386 from the list of target platforms.

I can help look into this if it's of interest to you, but without looking into it much I have no immediate guess at what the problem is.

**Comment by grobie** [comment]
Hey @a-robinson, thanks for the report. The built-in process collector (metrics about your client's cpu, memory, fd, etc. usage) unfortunately has a cgo dependency. Please have a look at the PR #68 which addresses your described issue as well. I just merged it into master. Golang automatically disables cgo during cross-compilation.

Can you please try master and see if that fixes your issue? It comes to the expense that you won't have the default `process_*` metrics for your client if you cross-compile.

**Comment by a-robinson** [comment]
Wow, very impressive timing @grobie. PR #68 does fix the issue :)

And we don't even lose the `process_*` metrics on our amd64 builds, which is where it really counts. Thanks!
