### ISSUE TITLE
cannot find package "github.com/cespare/xxhash/v2

### ISSUE THREAD

**Issue by samr13** [prometheus/client_golang#690]
../../github.com/prometheus/client_golang/prometheus/desc.go:22:2: cannot find package "github.com/cespare/xxhash/v2" in any of:
        /usr/local/go/src/github.com/cespare/xxhash/v2 (from $GOROOT)
        /go/src/github.com/cespare/xxhash/v2 (from $GOPATH)

**Comment by beorn7** [comment]
You are probably using an obsolete Go version. See README.md: "This library requires Go1.9 or later. The minimum required patch releases for older Go versions are Go1.9.7 and Go1.10.3."

**Comment by samr13** [comment]
I was using in docker. Used new version of go and not seeing this issue
