### ISSUE TITLE
Why does testutil.ToFloat64() use channels/goroutines?

### ISSUE THREAD

**Issue by jeffwidman** [prometheus/client_golang#691]
While poking through the source of [`ToFloat64`](https://godoc.org/github.com/prometheus/client_golang/prometheus/testutil#ToFloat64) I noticed it's using channels / goroutines:
https://github.com/prometheus/client_golang/blob/d2ead25884778582e740573999f7b07f47e171b4/prometheus/testutil/testutil.go#L74-L109

Why? 

Why not simply take a metric / collector as input, and then do the protobuf serialization / deserialization in the main thread?

Is the purpose of adding channels/goroutines to protect against something or to improve performance somehow?

**Comment by beorn7** [comment]
The intention here is to act on the `Collector` interface. And that interface, for better or worse, requires a channel as the parameter. The next major version of this library will change that, see #228. But until then, I guess we are stuck with it here.

This is definitely not to improve performance, on the contrary, sadly…

**Comment by jeffwidman** [comment]
Gotcha, thank you!
