### ISSUE TITLE
exemple for _build_info metric

### ISSUE THREAD

**Issue by finkr** [prometheus/client_golang#693]
Many people implement prometheus exposition format, but don't provide `....build_info` metric like this:

    # HELP node_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which node_exporter was built.
    # TYPE node_exporter_build_info gauge
    node_exporter_build_info{branch="HEAD",goversion="go1.12.5",revision="3db77732e925c08f675d7404a8c46466b2ece83e",version="0.18.1"} 1

(with initial [commit](
https://github.com/prometheus/node_exporter/commit/3171f404f42457ede68e84cfbee5fd8b8ccff29f) as in https://github.com/prometheus/node_exporter/pull/176).

It would be nice to provide an example and document it.

**Comment by beorn7** [comment]
Note that there is https://github.com/prometheus/common/blob/master/version/info.go . It is just a bit too specific to a particular way of building binaries to be a fit here in client_golang.

The general practice of providing a `build_info` is not specific to the Go instrumentation client. It should be documented on https://prometheus.io (which it currently is not, AFAICS).

Once you know, you want that metric, it's essentially just following the already existing [example for GaugeFunc](https://godoc.org/github.com/prometheus/client_golang/prometheus#example-GaugeFunc):
```Go
if err := prometheus.Register(prometheus.NewGaugeFunc(
    prometheus.GaugeOpts{
        Name:        "fooapp_build_info",
        Help:        "A metric with a constant '1' value labeled by version, revision, branch, and goversion from which fooapp was built.",
        ConstLabels: prometheus.Labels{
            branch:    info.Branch,
            goversion: info.GoVersion,
            revision:  info.Revision,
            version:   info.Version,
        }
    },
    func() float64 { return 1 },
)); err == nil {
    fmt.Println("GaugeFunc 'goroutines_count' registered.")
}
```

Or even simpler with `promauto`:
```Go
promauto.NewGaugeFunc(
    prometheus.GaugeOpts{
        Name:        "fooapp_build_info",
        Help:        "A metric with a constant '1' value labeled by version, revision, branch, and goversion from which fooapp was built.",
        ConstLabels: prometheus.Labels{
            branch:    info.Branch,
            goversion: info.GoVersion,
            revision:  info.Revision,
            version:   info.Version,
        }
    },
    func() float64 { return 1 },
)
```

The first version could be added as another example to the [existing one](https://godoc.org/github.com/prometheus/client_golang/prometheus#example-GaugeFunc). Would that be helpful?

**Comment by beorn7** [comment]
I have updated the common/version package to use `NewGaugeFunc`, and in #697 I have added a pointer to that code.
