### ISSUE TITLE
metric.go: Documentation error

### ISSUE THREAD

**Issue by MMulthaupt** [prometheus/client_golang#694]
In [metric.go](https://github.com/prometheus/client_golang/blob/master/prometheus/metric.go#L83), I believe it should say "Metrics with the same fully-qualified name must *not* have the same label names". Compare with [registry.go](https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L293), where it says "fqName + constLabel combination unique".

**Comment by beorn7** [comment]
I think the doc as is is correct.

Note that [metric.go](https://github.com/prometheus/client_golang/blob/master/prometheus/metric.go#L83) refers to the label _names_, while [registry.go](https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L293) refers to the labels as a whole, including the label _values_.

Or in other words: the label names _must_ be the same while the label values _must_ be different.

**Comment by MMulthaupt** [comment]
You are correct; I read that wrong. Closing.
