### ISSUE TITLE
Go mod: client_golang/common interdependencies

### ISSUE THREAD

**Issue by fcharlie** [prometheus/client_golang#701]
Recently I found a problem while writing exporter using `prometheus/client_golang`. 

To put it simply：

`github.com/prometheus/client_golang@v1.3.0` requires`github.com/prometheus/common@v0.7.0`

`github.com/prometheus/common@v0.7.0` requires`github.com/prometheus/client_golang@v1.0.0`

`github.com/prometheus/client_golang@v1.0.0` requires `github.com/prometheus/common@v0.4.1`

`github.com/prometheus/common@v0.4.1` requires `github.com/prometheus/client_golang@v0.9.1`

Fortunately, `github.com/prometheus/client_golang@v0.9.1` does not use the golang module, so this dependent game will not continue.

Because I didn't research it in depth, I don't know what the consequences will be, but when using modules, the two modules should reduce interdependence. If there are interdependencies, they should be synchronized in time.

`go mod graph|grep 'github.com/prometheus/common'`

 
<pre><font color="#2ECC71"><b>➜  </b></font><font color="#1ABC9C"><b>bizarre</b></font> <font color="#3498DB"><b>git:(</b></font><font color="#E74C3C"><b>master</b></font><font color="#3498DB"><b>)</b></font> go mod graph|grep &apos;github.com/prometheus/common&apos;       
private/url/my/project <font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0
github.com/prometheus/client_golang@v1.3.0 <font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/alecthomas/template@v0.0.0-20190718012654-fb15b899a751
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/alecthomas/units@v0.0.0-20190717042225-c3de453c63f4
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/go-kit/kit@v0.9.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/go-logfmt/logfmt@v0.4.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/golang/protobuf@v1.3.2
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/julienschmidt/httprouter@v1.2.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/matttproud/golang_protobuf_extensions@v1.0.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/mwitkow/go-conntrack@v0.0.0-20161129095857-cc309e4a2223
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/pkg/errors@v0.8.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/prometheus/client_golang@v1.0.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/prometheus/client_model@v0.0.0-20190129233127-fd36f4220a90
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 github.com/sirupsen/logrus@v1.4.2
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 golang.org/x/sys@v0.0.0-20190422165155-953cdadca894
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 gopkg.in/alecthomas/kingpin.v2@v2.2.6
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.7.0 gopkg.in/yaml.v2@v2.2.2
github.com/prometheus/client_golang@v1.0.0 <font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/alecthomas/template@v0.0.0-20160405071501-a0175ee3bccc
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/alecthomas/units@v0.0.0-20151022065526-2efee857e7cf
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/beorn7/perks@v0.0.0-20180321164747-3a771d992973
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/go-kit/kit@v0.8.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/go-logfmt/logfmt@v0.3.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/go-stack/stack@v1.8.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/gogo/protobuf@v1.1.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/golang/protobuf@v1.2.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/julienschmidt/httprouter@v1.2.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/kr/logfmt@v0.0.0-20140226030751-b84e30acd515
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/matttproud/golang_protobuf_extensions@v1.0.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/mwitkow/go-conntrack@v0.0.0-20161129095857-cc309e4a2223
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/pkg/errors@v0.8.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/prometheus/client_golang@v0.9.1
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/prometheus/client_model@v0.0.0-20180712105110-5c3871d89910
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/prometheus/procfs@v0.0.0-20181005140218-185b4288413d
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 github.com/sirupsen/logrus@v1.2.0
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 golang.org/x/net@v0.0.0-20181114220301-adae6a3d119a
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 golang.org/x/sys@v0.0.0-20181116152217-5ac8a444bdc5
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 gopkg.in/alecthomas/kingpin.v2@v2.2.6
<font color="#E74C3C"><b>github.com/prometheus/common</b></font>@v0.4.1 gopkg.in/yaml.v2@v2.2.1
</pre>

**Comment by brian-brazil** [comment]
I guess we might want to consider moving expfmt over here sooner rather than later, and finishing the elimination of common/model.

**Comment by beorn7** [comment]
> Because I didn't research it in depth, I don't know what the consequences will be,

I think there is no practical consequence. The dependency resolver just finds the most recent of the required versions and uses it.

> but when using modules, the two modules should reduce interdependence.

Yes, that would be good in general. Circular dependencies are bad.

> If there are interdependencies, they should be synchronized in time.

I'm not sure if that's possible. We cannot change two different git repos atomically. To make each change consistent, they have to happen one after another.

**Comment by beorn7** [comment]
> I guess we might want to consider moving expfmt over here sooner rather than later, and finishing the elimination of common/model.

Ironically, both packages were moved from here over to prometheus/common in the past.

Does the move back have other benefits than just simplifying dependency resolution for Go modules?
Especially `expfmt` might be used by 3rd parties, which we would break if moving back.

**Comment by brian-brazil** [comment]
> Especially expfmt might be used by 3rd parties, which we would break if moving back.

One of my reasons is that expfmt is defacto a public API, however common is meant for things that are internal-only and use by others is at their own risk.

Model should be deleted imho, subsumed into the bits of code that need it.

**Comment by beorn7** [comment]
> One of my reasons is that expfmt is defacto a public API, however common is meant for things that are internal-only and use by others is at their own risk.

Wasn't that always the case? Why did we move expfmt out of client_golang then? (I really would like to understand the reasons we had back then. I don't remember a lot about it, just that I wasn't deeply involved in the decision.)

In any case, with Go Modules, we now have another reason to not have expfmt in client_golang: If we want to have only one module per repo, we have to version everything in that one repo together. That's already painful with the API client and the instrumentation client, which are not related at all. For expfmt, at least the encoding is related, but the parsing is not. From that perspective, it feels right to have expfmt in a separate module and repo.

Not that I'm strongly opposed to moving expfmt back here. I just would like to avoid flip-flopping with all the overhead caused for us and others, and thus I'd like to come to an informed and hopefully durable decision.

> Model should be deleted imho, subsumed into the bits of code that need it.

A quick search shows that model is used a lot throughout our repos. It looks like a perfect example for "things that are internal-only and use by others is at their own risk". What would be the gain of replicating it into almost each Go repository we have?

**Comment by beorn7** [comment]
Looking at it from the other side: The only dependency back from common to client_golang is the `version` package. We could move that one inte client_golang. However, it is quite specific to the Prometheus build system (which, I assume, is the reason to have it in common).

Bottom line is that there is actually very minimal cyclic dependency between client_golang and common. It is mostly that client_golang uses common. The latter has only one very tiny package where the opposite is true.

**Comment by brian-brazil** [comment]
> Why did we move expfmt out of client_golang then? 

No real context unfortunately: https://github.com/prometheus/client_golang/pull/172

> If we want to have only one module per repo, we have to version everything in that one repo together.

That applies no matter which repo the code is in.

> I just would like to avoid flip-flopping with all the overhead caused for us and others

Yeah, let's not bounce things around unnecessarily.

> A quick search shows that model is used a lot throughout our repos.

Only by Prometheus itself, AM, PGW and statsd_exporter. Most of the uses are to get constants, e.g. statsd_exporter is using it to get the byte value 255.

The only code that's shared is time parsing, which should stay in common as Prometheus and AM share that. The rest appears to be largely application-specific data structures, and various other vestigial code.

**Comment by beorn7** [comment]
### model usage:

> Only by Prometheus itself, AM, PGW and statsd_exporter.

And client_golang (of course). And (for tests only) in mysqld_exporter and prombench. That's seven repos. Even if the usage is minimal in some repos, it still seems sane to me to have it. Sharing data structures is not a bad thing, either.

### Go modules versioning vs. multiple independent things in one repo

> That applies no matter which repo the code is in.

Certainly. And common is a particularly bad offender. On the bright side, common is, as you say, meant for internal usage, so releases and versioning problems are contained to the project, while client_golang is (very very) public. Also, we put all the hassle into one repo instead of spreading it.

**Comment by brian-brazil** [comment]
> And (for tests only) in mysqld_exporter and prombench

Each importing it just for a single constant.

> Even if the usage is minimal in some repos, it still seems sane to me to have it.

I'm more saying that we should massively trim down its scope. It's a remainder from the days where a good chunk of changes in Prometheus required changes in client_golang too, as that's where all the constants were.

**Comment by beorn7** [comment]
I'd like to close this issue. The go mod interdependency is, from all I can see, acceptable. The easiest way to remove it would be to move the `version` package somewhere else. But it's probably not worth it, as that "weird" climbing down the version ladder is not really harmful in effect. It happens in the dependency solver, but doesn't mean that the code of all those version is actually used.

Even if we wanted to move `version`, it would be an issue in the common repo. Same goes for the two other things being discussed here: De-normalizing `model` and moving back `expfmt`. (The latter would actually effect client_golang significantly as the target of the move, but the discussion should still happen in common.)
