### ISSUE TITLE
feature: Allow consumer to configure full endpoint URLs

### ISSUE THREAD

**Issue by kakkoyun** [prometheus/client_golang#704]
I have recently realized while working on a [small testing tool](https://github.com/observatorium/up/blob/89757a581729932725d5ca72106cc77657b403e9/main.go#L296-L343), one cannot specify full endpoint URLs for the API. I had to use other available APIs and copy over encoding flow as a workaround. (I hope I haven't missed any other existing way to do this)

Endpoints are defined as constants,
https://github.com/prometheus/client_golang/blob/803ef2a759d7caaaa0de58e3815f1be4c8b5a42a/api/prometheus/v1/api.go#L119-L139

and exposed public APIs use those
https://github.com/prometheus/client_golang/blob/803ef2a759d7caaaa0de58e3815f1be4c8b5a42a/api/prometheus/v1/api.go#L661-L662

Since now we have other projects such as [Thanos](https://thanos.io/), [Context](https://cortexmetrics.io/)(or one can put a proxy in front of these APIs) that implements the same API, I'd like to have the ability to configure endpoints to use client library against compatible APIs.

I'm happy to contribute to the project to make this happen.

@beorn7 

cc @squat

**Comment by beorn7** [comment]
I don't quite understand. Wouldn't a compatible API have the same endpoints?

Assuming a "generic" method on `httpAPI` would make sense, how would it look like?

I'm happy to accept PRs. But note that I'm not really an expert. I'm just maintaining this port of this repo because it was dropped here in the past, and we don't have a more qualified maintainer available at the moment.

**Comment by kakkoyun** [comment]
Thanks for the comment, and apologies for late response.

> Wouldn't a compatible API have the same endpoints?
You have a point. They have to be compatible.

However, it'd be really useful to have a more flexible API when it comes to specifying URL and paths to execute requests against.

Something like:
```go
func (h *httpAPI) Query(ctx context.Context, queryEndpoint, query string, ts time.Time) (model.Value, Warnings, error {
 	u := h.client.URL(queryEndpoint, nil)
 	// ...
}
``` 

Or:
```go
func (h *httpAPI) Query(ctx context.Context, query string, ts time.Time) (model.Value, Warnings, error {
	var ok bool
	var epQuery string
	if epQuery, ok = h.epMap[epQueryKey]; !ok {
		epQuery = defaultEpQuery
	}

	u := h.client.URL(epQuery, nil)
	// ...
}
``` 

I will close this one, I don't think it's useful enough at this stage.
Maybe just food for thought while implementing the new version.

**Comment by beorn7** [comment]
Just for clarification: Semantic versioning currently only applies to the instrumentation client. The API client is still marked as experimental. Thus, we can do breaking changes in the API client if they are worth it.
