### ISSUE TITLE
API client: Support for new metadata endpoints (in v1)

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/client_golang#705]
There should be support for the new Prometheus metadata endpoints described in https://github.com/prometheus/prometheus/issues/6395 .

cc @gotjosh

**Comment by gotjosh** [comment]
@beorn7 feel free to assign this to me.

**Comment by beorn7** [comment]
Done. :o)

**Comment by slrtbtfs** [comment]
@gotjosh Are you planning to work on this over the next few days?

If not I can do a PR myself as well.

**Comment by gotjosh** [comment]
Sorry, @slrtbtfs I've been away for the past week and a half - I'm now back and will be getting down to this relatively soon.

Feel free to take this if you have a higher priority. I'll make sure to comment on this issue when I'm about to start.

**Comment by gotjosh** [comment]
Going to start working on this.
