### ISSUE TITLE
Error Message Upon Successful Push

### ISSUE THREAD

**Issue by texasbobs** [prometheus/client_golang#709]
We started seeing "error" messages coming out after pushing to the pushgateway.  Our code looks like this:
```
func (pg *PromGateway) Push() error {
	pusher := push.New(pg.url, pg.jobName).Gatherer(pg.registry)
	if err := pusher.Add(); err != nil {
		fmt.Printf("Could not push metrics to Prometheus Push Gateway on %v:", pg.url, err)
		return err
	}
	return nil
}
```
The result of this command is the metric actually gets pushed and is availavle in prometheus.  However, we are falling into the error fmt.Printf and showing this in the output:
```
Could not push metrics to Prometheus Push Gateway on thdks-prometheus-pushgateway.monitoring.svc:9091:%!(EXTRA *errors.errorString=unexpected status code 200 while pushing to http://thdks-prometheus-pushgateway.monitoring.svc:9091/metrics/job/mongodb_benchmark: )unexpected status code 200 while pushing to http://thdks-prometheus-pushgateway.monitoring.svc:9091/metrics/job/mongodb_benchmark:
```
We recently upgraded to `image: "prom/pushgateway:v1.0.1"`.  I just confirmed that this was working on `v0.8.0`.

**Comment by beorn7** [comment]
You need to upgrade client_golang to at least v1.2.0, see https://github.com/prometheus/client_golang/releases/tag/v1.2.0 changelog: "Support pushing to Pushgateway v0.10+."

**Comment by texasbobs** [comment]
Thanks.
