### ISSUE TITLE
process_resident_memory_bytes detected is wrong in Win7 32bit

### ISSUE THREAD

**Issue by cobolbaby** [prometheus/client_golang#728]
### Build Version: 

- golang: 1.13.8
- client_golang: 1.4.1

### Running OS:

- Windows7 32bit

### Details:

The memory usage I saw through resource management was about 30M. But the return value of the metrics interface is 300T, as shown below:

![2020-03-19 11-23-55屏幕截图](https://user-images.githubusercontent.com/11460848/77028726-a4609e00-69d4-11ea-9da0-a65573b7d67c.png)

In addition, process_virtual_memory_bytes metrics is 0.

**Comment by beorn7** [comment]
The memory definitions on Microsoft Windows are certainly very different than on Unix-like OSs. While that might explain the zero for `process_virtual_memory_bytes`, 300TiB for `process_resident_memory_bytes` is certainly not what this metric is intended for.

Sadly, I don't have access to Microsoft Windows machines. Help welcome!

**Comment by cobolbaby** [comment]
Help welcome!
