### ISSUE TITLE
Document better what MaxAge in a summary does

### ISSUE THREAD

**Issue by viruslobster** [prometheus/client_golang#737]
Taken from: https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?tab=doc#Summary

> A Summary captures individual observations from an event or sample stream and summarizes them in a manner similar to traditional summary statistics: 1. sum of observations, 2. observation count, 3. rank estimations.

And when creating a summary you specify a SummaryOpts, an option of which is MaxAge:
> // MaxAge defines the duration for which an observation stays relevant
	// for the summary. Must be positive. The default value is DefMaxAge.
	MaxAge time.Duration
 
This led me to believe that a Summary would provide me with sum, count, and rank estimations over the specified window. However it appears a Summary actually provides you with rank estimations __only__ over the specified window, while observation sum and count are calculated since the Summary's creation.

You can see here in this p95 latency graph that the metric is not monotonically increasing
![p95](https://user-images.githubusercontent.com/1095450/79814059-2a546980-8332-11ea-8655-413df8d9cfd0.png)

However the count exported by the same summary is monotonically increasing, since the same windowing algorithm applied to the rank estimations is not used
![count](https://user-images.githubusercontent.com/1095450/79814053-26c0e280-8332-11ea-9015-b1cd8bac5da4.png)

I can also see in the code that a `streams []*quantile.Stream` (one Stream for each age bucket) is used to calculate rank estimations but a single `sum float64` and `cnt uint64` are used to store sum and count respectively.

```
type summary struct {
	selfCollector

	bufMtx sync.Mutex // Protects hotBuf and hotBufExpTime.
	mtx    sync.Mutex // Protects every other moving part.
	// Lock bufMtx before mtx if both are needed.

	desc *Desc

	objectives       map[float64]float64
	sortedObjectives []float64

	labelPairs []*dto.LabelPair

	sum float64
	cnt uint64

	hotBuf, coldBuf []float64

	streams                          []*quantile.Stream
	streamDuration                   time.Duration
	headStream                       *quantile.Stream
	headStreamIdx                    int
	headStreamExpTime, hotBufExpTime time.Time
}
...
for i := uint32(0); i < opts.AgeBuckets; i++ {
	s.streams = append(s.streams, s.newStream())
}
```

Is this desired behavior? It would certainly be more convenient for my use case if all Summary statistics were calculated over the specified window instead of just rank estimations. Currently if you want this behavior you would have to build it out yourself by saving count and sum at intervals and subtracting them from the global totals. Why not calculate all three statistics over the specified window and if users want a global counter, have them use a Counter instead of or in addition to a Summary? At the very least the documentation should be updated to make clear that sum and count are not calculated over the window. 

Thanks!

**Comment by beorn7** [comment]
Yes, this is the desired behavior. But, as you have noticed, it's poorly documented. :-/

`_sum` and `_count` are additive, so you can use the usual PromQL tooling to calculate their values just for the last 10m etc. That's not possible for precalculated quantiles, which is the reason for doing the whole age jazz in the first place.

Would you like to create a PR that improves the documentation for `MaxAge`? It should clearly express that the age only applies to the pre-calculated quantile estimations but _not_ to `_sum` and `_count`.
