### ISSUE TITLE
Add support for /status/runtimeinfo endpoint to the api client

### ISSUE THREAD

**Issue by lilic** [prometheus/client_golang#746]
Seems like there is `status/config` and `status/flags` but not `status/runtimeinfo`, any particular reason why this endpoint is missing or just simply was not added yet? 
(Happy to add it, if it's the latter)

https://github.com/prometheus/client_golang/blob/6edbbd9e560190e318cdc5b4d3e630b442858380/api/prometheus/v1/api.go#L138-L139

**Comment by bwplotka** [comment]
It's a new endpoint, that's it (:

**Comment by bwplotka** [comment]
If I am not wrong, help wanted to add it :hugs:

**Comment by beorn7** [comment]
Yup. Potentially even very easy, if the structure is similar to the existing endpoints.

**Comment by lilic** [comment]
As mentioned in the issue happy to do this, just wanted to confirm this is welcome.
