### ISSUE TITLE
clean up staled metrics

### ISSUE THREAD

**Issue by yiyijin** [prometheus/client_golang#748]
Hi there, 

we are using opencensus-agent to collect metrics from application, and opencensus-agent is configured to allow prometheus to scrape from. 

Internally, opencensus-agent uses https://github.com/orijtech/prometheus-go-metrics-exporter to allow prometheus scrape, which in term uses promeetheus/client_golang.

My problem is: when application disconnected from opencensus-agent, it seems the Registry keeps the metrics, and everytime prometheus scrape, it will get the old staled metrics, I just wonder if there is a way to configure ttl for a metrics? 

Thanks!

**Comment by beorn7** [comment]
No, there is deliberately no TTL for metrics.

You can `Unregister` metrics from the [registry](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus@v1.6.0?tab=doc#Registerer), but it's a somewhat controversial topic when that should happen if at all.

If you want to mirror metrics from another monitoring system, you should use a custom implementation of the [`Collector` interface](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus@v1.6.0?tab=doc#hdr-Custom_Collectors_and_constant_Metrics). Such a custom `Collector` will only ever collect the metrics you need/want.

I'm not sure how the opencensus-agent is built. You have to ask over there for support. IIRC, the next version of opencensus is happening under the OpenTelemetry label. Perhaps things are solved there in a different way anyway, and if not, you can ask there for a fix.

If you have more questions about the usage of prometheus/client_golang, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). If you want to discuss why a TTL feature is deliberately missing, use the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).We use GH issues only for bug reports and to track (uncontroversial) feature requests.
