### ISSUE TITLE
push: properly handle empty label values in grouping key

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#750]
See https://github.com/prometheus/pushgateway/pull/346 for a documentation update for the PGW about empty label values in the grouping key. (Note: It's really just documenting the current state of the PGW. No change of behavior of the PGW involved.)

The `push` package currently accepts empty label values for the grouping key, as demonstrated in https://github.com/prometheus/pushgateway/issues/344 . However, it then attempts to push in an invalid way, see again https://github.com/prometheus/pushgateway/issues/344 for details.

While the use case for empty label values in the grouping key is somewhat esoteric, a case can be made for it. Thus, we should probably support it in the way now [documented](https://github.com/prometheus/pushgateway/pull/346). Alternative is to disallow it in the `push` package. Just the current state of pretending it works but then fail to push is clearly a bug.

**Comment by matevz** [comment]
Thanks, this works now.
