### ISSUE TITLE
Add PidFile option

### ISSUE THREAD

**Issue by SuperQ** [prometheus/client_golang#760]
A common way to use `prometheus.NewProcessCollector()` is to use a `PidFn` that reads a the PID from a file.

It would be nice to have `PidFile` as a first-class feature. Or maybe include a `NewPidFileFn()` helper.

**Comment by sbookworm** [comment]
Hope to help, but I don't know how to implement the feature, could you give me some advice? thanks

**Comment by beorn7** [comment]
Happy to give some pointers. But you need to ask me for something more specific @sbookworm .

@SuperQ for a starter, perhaps you could point to code using `NewProcessCollector` that reads from a PID file? That code needed to be pulled into the library here.

**Comment by SuperQ** [comment]
Sure, we have something like this in the [haproxy_exporter code](https://github.com/prometheus/haproxy_exporter/blob/5b3413f75ae8300e0794e1b67e1e0722abed3063/haproxy_exporter.go#L589-L603).

**Comment by sbookworm** [comment]
@SuperQ @beorn7 thanks, Let me try.

**Comment by sbookworm** [comment]
@SuperQ  sorry to bother, :)
my action:
1, create a new branch
2, changed the code and commit
3, git push origin my_branch_name

facing ERROR: Permission to prometheus/client_golang.git denied to sbookworm.
Should I apply the access for submitting code?

**Comment by beorn7** [comment]
You have to fork this repository and work in your own fork. From there, you can create a PR for this repo.

You could search for tutorials how to contribute to OSS projects on GitHub. For example, https://parbhatpuri.com/git-workflow-to-contribute-to-an-open-source-project.html might be a good starter (just googled that, did not check if it is particularly good).

**Comment by sbookworm** [comment]
@beorn7 thanks very much :)

**Comment by sbookworm** [comment]
https://github.com/prometheus/client_golang/pull/804
please help review, thanks :)
