### ISSUE TITLE
Flaky test `TestSummaryDecay`

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#765]
Recently, `TestSummaryDecay` started to become flaky on CircleCI. It's a timing dependent test. It used to work well, but I guess something has changed in CircleCI. Ideally, the test should be made less timing sensitive.

**Comment by beorn7** [comment]
Hasn't happened in a while. Will close this (although a proper solution would be better of course).

**Comment by bwplotka** [comment]
Happened again 2x times on new Go 1.20 https://app.circleci.com/pipelines/github/prometheus/client_golang/902/workflows/1a9e0222-09a4-4f9d-8c76-89441995bb24/jobs/3496

![image](https://user-images.githubusercontent.com/6950331/226727044-f2023c8d-27cb-4bd5-b58b-ada294df3608.png)

**Comment by imorph** [comment]
fixed in #1672
