### ISSUE TITLE
v1/api.go/LabelNames missing start/end time parameter

### ISSUE THREAD

**Issue by Nexucis** [prometheus/client_golang#766]
Hi
in the file `api/prometheus/v1/api.go`, the method exposed by the client `LabelNames` doesn't allow the usage of the `start/end parameter`.

Is it something that can be changed ?

**Comment by bwplotka** [comment]
Yes, the start and end were added just very recently. Help wanted to extend
api.go, but we need a way to support servers without start & end
implemented yet.

Bartek

**Comment by brian-brazil** [comment]
Wouldn't the extra URL parameters be ignored?

**Comment by bwplotka** [comment]
I double checked, it will be yes:
https://github.com/prometheus/prometheus/blob/v2.18.0/web/api/v1/api.go#L482 So
all good, let's add that (: Sorry for not remembering.

**Comment by Nexucis** [comment]
ok :) I will create the PR then

**Comment by Nexucis** [comment]
If it's ok to create it of course :). Or maybe someone else is eager to do it. But if not, I will be happy to do it.
