### ISSUE TITLE
How to use DeleteSeries API to delete all specific series?

### ISSUE THREAD

**Issue by microyahoo** [prometheus/client_golang#770]
https://github.com/prometheus/client_golang/blob/b05e50c9298cbadd2b4be3f1527f5c1b178acb55/api/prometheus/v1/api.go#L623
The current DeleteSeries API must specify the parameters of startTime and endTime, but in prometheus document startTime and endTime are all optional like below.
> https://prometheus.io/docs/prometheus/latest/querying/api/
POST /api/v1/admin/tsdb/delete_series
PUT /api/v1/admin/tsdb/delete_series
URL query parameters:
match[]=<series_selector>: Repeated label matcher argument that selects the series to delete. At least one match[] argument must be provided.
start=<rfc3339 | unix_timestamp>: Start timestamp. Optional and defaults to minimum possible time.
end=<rfc3339 | unix_timestamp>: End timestamp. Optional and defaults to maximum possible time.

If we specify the start and end, the prometheus server will delete data for a selection of series in a time range. 
https://github.com/prometheus/prometheus/blob/8d3c2f6829d73be15a6684f9324917e72fbf1a31/web/api/v1/api.go#L1364

**Comment by beorn7** [comment]
For `end`, I'd just use `time.Now()`.

For `start`, does `time.Time{}` work? The zero value of `time.Time` is 0001-01-01 00:00 UTC. That should be early enough for most purposes.

Not sure if that's the most idiomatic way. The experts for the API library might know. In general, wo have the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) for questions like this and don't use GitHub issues. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
