### ISSUE TITLE
RuntimeinfoResult.StartTime should be a time.Time

### ISSUE THREAD

**Issue by mxey** [prometheus/client_golang#776]
Observed on release v1.7.1

RuntimeinfoResult.StartTime is a string containing a timestamp. If the field was a time.Time, Go's encoding/json would automatically parse the timestamp while unmarshalling.

**Comment by bwplotka** [comment]
hm, yes I think we could change this (if compatibility allows ;p @beorn7)

Help wanted!

**Comment by beorn7** [comment]
No compatibility guarantees for the API client, anyway. So please go ahead and create a PR. (o:
