### ISSUE TITLE
unexpected status code 200 when pushing

### ISSUE THREAD

**Issue by huzilin** [prometheus/client_golang#788]
## Version

```
github.com/prometheus/client_golang v1.5.1
```

## Code

```go
var pusher *push.Pusher
pusher = push.New(service, localIP+"_xxx").Gatherer(reg)
if err := pusher.Add(); err != nil {
    ...
}
```

## System information

CPU architecture: x86_64
kernel version: 4.4.38-1.el7.elrepo.x86_64
CPU architecture: x86_64

**Comment by beorn7** [comment]
This smells like you are not actually using v1.5.1. See #709 .

Could you double-check the version you are compiling into your binary?

**Comment by huzilin** [comment]
oh my bad. My colleague build in old version and push to online.

Thx.
