### ISSUE TITLE
deadlock when  concurrency  delete and insert labal

### ISSUE THREAD

**Issue by liukeyou** [prometheus/client_golang#789]
getOrCreateMetricWithLabelValues 、 deleteByHashWithLabels and Collect func acquire m.mtx lock in vec.go
will deadlock

goroutine profile: total 8
1 @ 0x10367a4 0x1031981 0x1030eee 0x10a08ab 0x10a0945 0x10a1baf 0x129356c 0x12b22e5 0x141938a 0x114b843 0x114d31b 0x114d3d8 0x13816e7 0x138129f 0x1410190 0x141a8d4 0x1421816 0x10668b1
	0x1030eed	internal/poll.runtime_pollWait+0x5d		/usr/local/go/src/runtime/netpoll.go:182
	0x10a08aa	internal/poll.(*pollDesc).wait+0x9a		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
	0x10a0944	internal/poll.(*pollDesc).waitRead+0x44		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
	0x10a1bae	internal/poll.(*FD).Read+0x39e			/usr/local/go/src/internal/poll/fd_unix.go:169
	0x129356b	net.(*netFD).Read+0x7b				/usr/local/go/src/net/fd_unix.go:202
	0x12b22e4	net.(*conn).Read+0xb4				/usr/local/go/src/net/net.go:177
	0x1419389	net/http.(*connReader).Read+0x2c9		/usr/local/go/src/net/http/server.go:787
	0x114b842	bufio.(*Reader).fill+0x2d2			/usr/local/go/src/bufio/bufio.go:100
	0x114d31a	bufio.(*Reader).ReadSlice+0x3ca			/usr/local/go/src/bufio/bufio.go:356
	0x114d3d7	bufio.(*Reader).ReadLine+0x87			/usr/local/go/src/bufio/bufio.go:385
	0x13816e6	net/textproto.(*Reader).readLineSlice+0xb6	/usr/local/go/src/net/textproto/reader.go:55
	0x138129e	net/textproto.(*Reader).ReadLine+0x6e		/usr/local/go/src/net/textproto/reader.go:36
	0x141018f	net/http.readRequest+0xaf			/usr/local/go/src/net/http/request.go:968
	0x141a8d3	net/http.(*conn).readRequest+0x4e3		/usr/local/go/src/net/http/server.go:967
	0x1421815	net/http.(*conn).serve+0xca5			/usr/local/go/src/net/http/server.go:1819

1 @ 0x10367a4 0x1031981 0x1030eee 0x10a08ab 0x10a0945 0x10a3eb5 0x1293f22 0x12bfd5e 0x12bdb29 0x1429b10 0x1427fc0 0x1427b1d 0x1429276 0x1904e2e 0x10668b1
	0x1030eed	internal/poll.runtime_pollWait+0x5d		/usr/local/go/src/runtime/netpoll.go:182
	0x10a08aa	internal/poll.(*pollDesc).wait+0x9a		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
	0x10a0944	internal/poll.(*pollDesc).waitRead+0x44		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
	0x10a3eb4	internal/poll.(*FD).Accept+0x3a4		/usr/local/go/src/internal/poll/fd_unix.go:384
	0x1293f21	net.(*netFD).accept+0x81			/usr/local/go/src/net/fd_unix.go:238
	0x12bfd5d	net.(*TCPListener).accept+0x5d			/usr/local/go/src/net/tcpsock_posix.go:139
	0x12bdb28	net.(*TCPListener).AcceptTCP+0x78		/usr/local/go/src/net/tcpsock.go:247
	0x1429b0f	net/http.tcpKeepAliveListener.Accept+0x4f	/usr/local/go/src/net/http/server.go:3264
	0x1427fbf	net/http.(*Server).Serve+0x36f			/usr/local/go/src/net/http/server.go:2859
	0x1427b1c	net/http.(*Server).ListenAndServe+0x1ec		/usr/local/go/src/net/http/server.go:2797
	0x1429275	net/http.ListenAndServe+0xd5			/usr/local/go/src/net/http/server.go:3037
	0x1904e2d	pkg/test.Test.func1+0x3d				/Users/x/dev/ttt/src/pkg/test/test_test.go:20

1 @ 0x10367a4 0x1036863 0x1007990 0x1007785 0x18b0cab 0x1904496 0x10668b1
	0x18b0caa	pkg/clients/prometheus.(*metricMap).Collect+0x1ea	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:232
	0x1904495	pkg/test.inittest.func1.1+0x45				/Users/x/dev/ttt/src/pkg/test/test.go:56

1 @ 0x10367a4 0x1036863 0x100844e 0x10081fb 0x11431e7 0x11495cc 0x1142b12 0x114535a 0x1143bc7 0x1905021 0x10363cf 0x10668b1
	0x11431e6	testing.(*T).Run+0x686		/usr/local/go/src/testing/testing.go:917
	0x11495cb	testing.runTests.func1+0xdb	/usr/local/go/src/testing/testing.go:1157
	0x1142b11	testing.tRunner+0x111		/usr/local/go/src/testing/testing.go:865
	0x1145359	testing.runTests+0x399		/usr/local/go/src/testing/testing.go:1155
	0x1143bc6	testing.(*M).Run+0x446		/usr/local/go/src/testing/testing.go:1072
	0x1905020	main.main+0xc0			_testmain.go:42
	0x10363ce	runtime.main+0x1be		/usr/local/go/src/runtime/proc.go:200

1 @ 0x10367a4 0x1036863 0x1047946 0x10476dd 0x107155b 0x18b1f88 0x18b0010 0x189ea0d 0x189ed18 0x1903daf 0x190436a 0x1142b12 0x10668b1
	0x10476dc	sync.runtime_SemacquireMutex+0x3c					/usr/local/go/src/runtime/sema.go:71
	0x107155a	sync.(*RWMutex).RLock+0x5a						/usr/local/go/src/sync/rwmutex.go:50
	0x18b1f87	pkg/clients/prometheus.(*metricMap).getOrCreateMetricWithLabels+0x57	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:332
	0x18b000f	pkg/clients/prometheus.(*metricVec).getMetricWith+0x16f			/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:142
	0x189ea0c	pkg/clients/prometheus.(*CounterVec).GetMetricWith+0x7c			/Users/x/dev/ttt/src/pkg/clients/prometheus/counter.go:192
	0x189ed17	pkg/clients/prometheus.(*CounterVec).With+0x67				/Users/x/dev/ttt/src/pkg/clients/prometheus/counter.go:215
	0x1903dae	pkg/test.Send+0x21e							/Users/x/dev/ttt/src/pkg/test/test.go:27
	0x1904369	pkg/test.Test+0x209							/Users/x/dev/ttt/src/pkg/test/test_test.go:38
	0x1142b11	testing.tRunner+0x111							/usr/local/go/src/testing/testing.go:865

1 @ 0x10367a4 0x1036863 0x1047946 0x10476dd 0x1071720 0x18b1485 0x18af3d9 0x1904d46 0x10668b1
	0x10476dc	sync.runtime_SemacquireMutex+0x3c				/usr/local/go/src/runtime/sema.go:71
	0x107171f	sync.(*RWMutex).Lock+0xaf					/usr/local/go/src/sync/rwmutex.go:98
	0x18b1484	pkg/clients/prometheus.(*metricMap).deleteByHashWithLabels+0x54	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:280
	0x18af3d8	pkg/clients/prometheus.(*metricVec).Delete+0x138		/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:91
	0x1904d45	pkg/test.inittest.func1+0x885					/Users/x/dev/ttt/src/pkg/test/test.go:77

1 @ 0x11aa675 0x11aa2f9 0x11a5450 0x1902274 0x19025b0 0x1423004 0x1425ca4 0x14278c6 0x1421fd3 0x10668b1
	0x11aa674	runtime/pprof.writeRuntimeProfile+0x104	/usr/local/go/src/runtime/pprof/pprof.go:708
	0x11aa2f8	runtime/pprof.writeGoroutine+0xb8	/usr/local/go/src/runtime/pprof/pprof.go:670
	0x11a544f	runtime/pprof.(*Profile).WriteTo+0x9f	/usr/local/go/src/runtime/pprof/pprof.go:329
	0x1902273	net/http/pprof.handler.ServeHTTP+0x303	/usr/local/go/src/net/http/pprof/pprof.go:245
	0x19025af	net/http/pprof.Index+0x12f		/usr/local/go/src/net/http/pprof/pprof.go:268
	0x1423003	net/http.HandlerFunc.ServeHTTP+0x43	/usr/local/go/src/net/http/server.go:1995
	0x1425ca3	net/http.(*ServeMux).ServeHTTP+0x1a3	/usr/local/go/src/net/http/server.go:2375
	0x14278c5	net/http.serverHandler.ServeHTTP+0x1f5	/usr/local/go/src/net/http/server.go:2774
	0x1421fd2	net/http.(*conn).serve+0x1462		/usr/local/go/src/net/http/server.go:1878

1 @ 0x1418ae0 0x10668b1
	0x1418ae0	net/http.(*connReader).backgroundRead+0x0	/usr/local/go/src/net/http/server.go:676

**Comment by liukeyou** [comment]
goroutine profile: total 8
1 @ 0x10367a4 0x1031981 0x1030eee 0x10a08ab 0x10a0945 0x10a1baf 0x129356c 0x12b22e5 0x141938a 0x114b843 0x114d31b 0x114d3d8 0x13816e7 0x138129f 0x1410190 0x141a8d4 0x1421816 0x10668b1
#	0x1030eed	internal/poll.runtime_pollWait+0x5d		/usr/local/go/src/runtime/netpoll.go:182
#	0x10a08aa	internal/poll.(*pollDesc).wait+0x9a		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x10a0944	internal/poll.(*pollDesc).waitRead+0x44		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#	0x10a1bae	internal/poll.(*FD).Read+0x39e			/usr/local/go/src/internal/poll/fd_unix.go:169
#	0x129356b	net.(*netFD).Read+0x7b				/usr/local/go/src/net/fd_unix.go:202
#	0x12b22e4	net.(*conn).Read+0xb4				/usr/local/go/src/net/net.go:177
#	0x1419389	net/http.(*connReader).Read+0x2c9		/usr/local/go/src/net/http/server.go:787
#	0x114b842	bufio.(*Reader).fill+0x2d2			/usr/local/go/src/bufio/bufio.go:100
#	0x114d31a	bufio.(*Reader).ReadSlice+0x3ca			/usr/local/go/src/bufio/bufio.go:356
#	0x114d3d7	bufio.(*Reader).ReadLine+0x87			/usr/local/go/src/bufio/bufio.go:385
#	0x13816e6	net/textproto.(*Reader).readLineSlice+0xb6	/usr/local/go/src/net/textproto/reader.go:55
#	0x138129e	net/textproto.(*Reader).ReadLine+0x6e		/usr/local/go/src/net/textproto/reader.go:36
#	0x141018f	net/http.readRequest+0xaf			/usr/local/go/src/net/http/request.go:968
#	0x141a8d3	net/http.(*conn).readRequest+0x4e3		/usr/local/go/src/net/http/server.go:967
#	0x1421815	net/http.(*conn).serve+0xca5			/usr/local/go/src/net/http/server.go:1819

1 @ 0x10367a4 0x1031981 0x1030eee 0x10a08ab 0x10a0945 0x10a3eb5 0x1293f22 0x12bfd5e 0x12bdb29 0x1429b10 0x1427fc0 0x1427b1d 0x1429276 0x1904e2e 0x10668b1
#	0x1030eed	internal/poll.runtime_pollWait+0x5d		/usr/local/go/src/runtime/netpoll.go:182
#	0x10a08aa	internal/poll.(*pollDesc).wait+0x9a		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x10a0944	internal/poll.(*pollDesc).waitRead+0x44		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#	0x10a3eb4	internal/poll.(*FD).Accept+0x3a4		/usr/local/go/src/internal/poll/fd_unix.go:384
#	0x1293f21	net.(*netFD).accept+0x81			/usr/local/go/src/net/fd_unix.go:238
#	0x12bfd5d	net.(*TCPListener).accept+0x5d			/usr/local/go/src/net/tcpsock_posix.go:139
#	0x12bdb28	net.(*TCPListener).AcceptTCP+0x78		/usr/local/go/src/net/tcpsock.go:247
#	0x1429b0f	net/http.tcpKeepAliveListener.Accept+0x4f	/usr/local/go/src/net/http/server.go:3264
#	0x1427fbf	net/http.(*Server).Serve+0x36f			/usr/local/go/src/net/http/server.go:2859
#	0x1427b1c	net/http.(*Server).ListenAndServe+0x1ec		/usr/local/go/src/net/http/server.go:2797
#	0x1429275	net/http.ListenAndServe+0xd5			/usr/local/go/src/net/http/server.go:3037
#	0x1904e2d	pkg/test.Test.func1+0x3d				/Users/x/dev/ttt/src/pkg/test/test_test.go:20

1 @ 0x10367a4 0x1036863 0x1007990 0x1007785 0x18b0cab 0x1904496 0x10668b1
#	0x18b0caa	pkg/clients/prometheus.(*metricMap).Collect+0x1ea	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:232
#	0x1904495	pkg/test.inittest.func1.1+0x45				/Users/x/dev/ttt/src/pkg/test/test.go:56

1 @ 0x10367a4 0x1036863 0x100844e 0x10081fb 0x11431e7 0x11495cc 0x1142b12 0x114535a 0x1143bc7 0x1905021 0x10363cf 0x10668b1
#	0x11431e6	testing.(*T).Run+0x686		/usr/local/go/src/testing/testing.go:917
#	0x11495cb	testing.runTests.func1+0xdb	/usr/local/go/src/testing/testing.go:1157
#	0x1142b11	testing.tRunner+0x111		/usr/local/go/src/testing/testing.go:865
#	0x1145359	testing.runTests+0x399		/usr/local/go/src/testing/testing.go:1155
#	0x1143bc6	testing.(*M).Run+0x446		/usr/local/go/src/testing/testing.go:1072
#	0x1905020	main.main+0xc0			_testmain.go:42
#	0x10363ce	runtime.main+0x1be		/usr/local/go/src/runtime/proc.go:200

1 @ 0x10367a4 0x1036863 0x1047946 0x10476dd 0x107155b 0x18b1f88 0x18b0010 0x189ea0d 0x189ed18 0x1903daf 0x190436a 0x1142b12 0x10668b1
#	0x10476dc	sync.runtime_SemacquireMutex+0x3c					/usr/local/go/src/runtime/sema.go:71
#	0x107155a	sync.(*RWMutex).RLock+0x5a						/usr/local/go/src/sync/rwmutex.go:50
#	0x18b1f87	pkg/clients/prometheus.(*metricMap).getOrCreateMetricWithLabels+0x57	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:332
#	0x18b000f	pkg/clients/prometheus.(*metricVec).getMetricWith+0x16f			/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:142
#	0x189ea0c	pkg/clients/prometheus.(*CounterVec).GetMetricWith+0x7c			/Users/x/dev/ttt/src/pkg/clients/prometheus/counter.go:192
#	0x189ed17	pkg/clients/prometheus.(*CounterVec).With+0x67				/Users/x/dev/ttt/src/pkg/clients/prometheus/counter.go:215
#	0x1903dae	pkg/test.Send+0x21e							/Users/x/dev/ttt/src/pkg/test/test.go:27
#	0x1904369	pkg/test.Test+0x209							/Users/x/dev/ttt/src/pkg/test/test_test.go:38
#	0x1142b11	testing.tRunner+0x111							/usr/local/go/src/testing/testing.go:865

1 @ 0x10367a4 0x1036863 0x1047946 0x10476dd 0x1071720 0x18b1485 0x18af3d9 0x1904d46 0x10668b1
#	0x10476dc	sync.runtime_SemacquireMutex+0x3c				/usr/local/go/src/runtime/sema.go:71
#	0x107171f	sync.(*RWMutex).Lock+0xaf					/usr/local/go/src/sync/rwmutex.go:98
#	0x18b1484	pkg/clients/prometheus.(*metricMap).deleteByHashWithLabels+0x54	/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:280
#	0x18af3d8	pkg/clients/prometheus.(*metricVec).Delete+0x138		/Users/x/dev/ttt/src/pkg/clients/prometheus/vec.go:91
#	0x1904d45	pkg/test.inittest.func1+0x885					/Users/x/dev/ttt/src/pkg/test/test.go:77

1 @ 0x11aa675 0x11aa2f9 0x11a5450 0x1902274 0x19025b0 0x1423004 0x1425ca4 0x14278c6 0x1421fd3 0x10668b1
#	0x11aa674	runtime/pprof.writeRuntimeProfile+0x104	/usr/local/go/src/runtime/pprof/pprof.go:708
#	0x11aa2f8	runtime/pprof.writeGoroutine+0xb8	/usr/local/go/src/runtime/pprof/pprof.go:670
#	0x11a544f	runtime/pprof.(*Profile).WriteTo+0x9f	/usr/local/go/src/runtime/pprof/pprof.go:329
#	0x1902273	net/http/pprof.handler.ServeHTTP+0x303	/usr/local/go/src/net/http/pprof/pprof.go:245
#	0x19025af	net/http/pprof.Index+0x12f		/usr/local/go/src/net/http/pprof/pprof.go:268
#	0x1423003	net/http.HandlerFunc.ServeHTTP+0x43	/usr/local/go/src/net/http/server.go:1995
#	0x1425ca3	net/http.(*ServeMux).ServeHTTP+0x1a3	/usr/local/go/src/net/http/server.go:2375
#	0x14278c5	net/http.serverHandler.ServeHTTP+0x1f5	/usr/local/go/src/net/http/server.go:2774
#	0x1421fd2	net/http.(*conn).serve+0x1462		/usr/local/go/src/net/http/server.go:1878

1 @ 0x1418ae0 0x10668b1
#	0x1418ae0	net/http.(*connReader).backgroundRead+0x0	/usr/local/go/src/net/http/server.go:676

**Comment by jxyy** [comment]
Hi @liukeyou , any update for this issue? 
I am very interested with the test case to trigger the deadlock. Could you kindly help to share it?
