### ISSUE TITLE
Consider adding a "global label" to registries

### ISSUE THREAD

**Issue by Tigraine** [prometheus/client_golang#799]
I have a bunch of canary workflows where it's important to have a `version` label on the metrics to draw comparisons.
Currently I always end up exposing one metric similar to `up` that has the label attached and then with recording-rules on the server merge the version with the other metrics as there doesn't seem to be a way to attach the label to ALL metrics coming from a registry.

Having the ability to set a global label would be a HUGE help as it saves me from having to write hundreds of recording rules

Is this something I am totally missing in the code (couldn't find anything) or is this something that you would consider. If so I'd be happy to try creating a PR

**Comment by beorn7** [comment]
Labels to be attached to all metrics coming from a target should be configured on the Prometheus side as target labels.

Having said that, there is already a helper to add a label to all metrics registered with a registry: https://pkg.go.dev/github.com/prometheus/client_golang/prometheus@v1.7.1?tab=doc#WrapRegistererWith

But as written in the doc comment, that's meant for subset of metrics (registered with "sub" registries). It's explicitly not meant to be used on the registry you use to expose metrics. See also https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels
