### ISSUE TITLE
Ignore unsupported charsets

### ISSUE THREAD

**Issue by hatamiarash7** [prometheus/client_golang#805]
We have many problems with **non-english** users. They used some texts in projects that isn't UTF-8 for example Russian.

```
panic: label value "\xdd\xed\xe3\xe5\xeb\xfc\xf1" is not valid UTF-8

goroutine 23 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/value.go:102
mikrotik-exporter/collector.(*interfaceCollector).collectMetricForProperty(0xc0000f8140, 0x9a5f2c, 0x7, 0xc000025770, 0x6, 0xc000025790, 0x7, 0xc00006b900, 0xc00000d7e0)
.
.
.
```

Is there any way to ignore this panic or replace non-english string with another one like _Unknown_ ? It does not make sense for us to **add exception for all collectors in many projects**.

---
**GO** : 1.14
**client_golang** : v1.2.1

**Comment by beorn7** [comment]
Prometheus doesn't support invalid UTF-8 in label values, and thus client_golang doesn't allow it, either.

However, all unicode characters can be represented in UTF-8, and therefore it is not restricted to English. There should be a library somewhere to convert a string from whatever encoding you are using into UTF-8. I recommend to use such a transcoding.

**Comment by hatamiarash7** [comment]
Yes, I can. But we should do the same thing for many projects or collectors. And other people may have the same problem.  
It would be great if such a feature could be placed in the library

**Comment by ArthurSens** [comment]
I think that abstracting the conversion from whatever encoding to UTF-8 is not a good option. 

If the user creates a metric/label named "X" he will expect that "X" is exposed, but will then find something completely different after the conversion. If the application/exporter exposes multiple metrics, it will be really hard to identify each metric.

**Comment by hatamiarash7** [comment]
@ArthurSens So what is your suggestion? What should we do in these situations?

**Comment by ArthurSens** [comment]
For now, just like @beorn7 said. The users should handle the conversion themselves, as it gives them more control over their own metrics. But from what it looks like, you don't have control over the label names? You gather info from third-parties and give them back as metrics? 

I guess that would be a problem as those third-parties will also see labels with names they don't expect, right? I don't see any alternatives besides adding support for other encodings inside Prometheus, but I can't say if it is possible or plausible. Sorry :grimacing:

**Comment by juliusv** [comment]
Yeah, it doesn't make sense to support other encodings in Prometheus itself, since UTF-8 can represent all characters from the other encodings and is the most standard one. So all you need to do is a conversion to UTF-8 before sending data to Prometheus.

**Comment by beorn7** [comment]
Indeed, I see no point in adding non UTF-8 support to the Prometheus server itself. It's the whole point of UTF-8 to not require every piece of software in the world to support every text encoding in the world. UTF-8 is also baked quite deeply into the Prometheus server. For example, there are bytes that can never occur in valid UTF-8, and they are used internally as marker bytes to separate UTF-8 strings.

The strategy is indeed to convert from whatever legacy text encoding you use into UTF-8 as early as possible, but at latest when you enter the Prometheus universe, i.e. in this case when you feed label values to prometheus/client_golang. There's probably a Go package out there that gives you something like a `ToUTF8String` helper function.
