### ISSUE TITLE
Add TLS support to API client

### ISSUE THREAD

**Issue by mrueg** [prometheus/client_golang#807]
I tried using the client_golang API client, unfortunately it seems to have no support for TLS and client certificates. 
Are there any plans to add this functionality or is the idea to overload RoundTripper to get it supported?

**Comment by beorn7** [comment]
Things should work out of the box if you just want to access an `https://...` URL. If you want to use TLS client certificates, you indeed have to provide your own `http.RoundTripper` in https://pkg.go.dev/github.com/prometheus/client_golang@v1.8.0/api#Config . https://golang.org/pkg/net/http/#Transport is the usual `http.RoundTripper` implementation from the standard library. In there, you can set a https://golang.org/pkg/crypto/tls/#Config . But that's really a question about HTTP handling in the Go standard library, nothing specific to the Prometheus API client. I suggest to use the relevant support channels for Go.
