### ISSUE TITLE
Add /metrics?format=openmetrics

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/client_golang#815]
When debugging exemplars, I'd like to do it straight from the browser. Therefore a ?format=openmetrics would be awesome.

**Comment by beorn7** [comment]
Oooooof, is there really no better way? Like some dev tool in the browser that lets you pick the content-type header?

Content negotiation is there precisely for the reason to not require HTTP parameters for it.

I just use `curl -H 'Accept: application/openmetrics-text' localhost:8080/metrics` for debugging. If `curl` can do it, then your browser should be able to, too?

**Comment by roidelapluie** [comment]
Not easily. Can we default to openmetrics for browsers? (accept = */*)

**Comment by brian-brazil** [comment]
Per a previous dev summit, the standing plan is to switch the default exposition to OM a year after warning potential consumers to give them time to set appropriate Accept headers.

I don't think it'd be wise to have different behaviour between wget/curl and browsers. There are various browser extensions that allow setting HTTP headers.

**Comment by roidelapluie** [comment]
OK
