### ISSUE TITLE
Dependency failures on build

### ISSUE THREAD

**Issue by vulcanfan** [prometheus/client_golang#818]
Hi,

I'm having trouble incorporating this client library into my own application.  Go build generates the dependency error pasted below.  

I'm using Go 1.13 on CentOS7, the application uses modules and I included in the import () section the following:
```
"github.com/prometheus/client_golang/prometheus/promhttp"
```
Building gave these errors: 

```
go: finding github.com/prometheus/client_golang/prometheus/promhttp latest
go: finding github.com/prometheus/client_golang/prometheus latest
go: finding github.com/prometheus/client_golang v1.8.0
go: downloading github.com/prometheus/client_golang v1.8.0
go: extracting github.com/prometheus/client_golang v1.8.0
go: github.com/prometheus/client_golang@v1.8.0 requires
        github.com/prometheus/common@v0.14.0 requires
        github.com/go-kit/kit@v0.10.0 requires
        github.com/casbin/casbin/v2@v2.1.2 requires
        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible: invalid pseudo-version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/dac3237ce23c7a321475df4e3bb8c7115ea5c093fdf9bc1798a57a9ef75ede77: exit status 128:
        fatal: git fetch-pack: expected shallow list
```
 
Can someone please point me in the right direction to resolve?

Many thanks

**Comment by beorn7** [comment]
Does anyone else see this?

It seems a problem further down the dependency tree. I'm curious if/why that's affecting many users or just you in your specific set up.

**Comment by brian-brazil** [comment]
We've had reports of this in other repos, I'm guessing there's something odd in either the casbin or govaluate git repo.

**Comment by brian-brazil** [comment]
I do note that all of the other reports are on CentOS and/or RHEL. So it'd probably something to do with their version of git.

**Comment by beorn7** [comment]
I assume there is nothing we can do here in this repo. Therefore, I'll close this issue. Feel free to add information here if you know a work around or have a status update WRT casbin, govaluate, CentOS and/or RHEL
