### ISSUE TITLE
Pusher defaults to `FmtProtoDelim` which is obsolete

### ISSUE THREAD

**Issue by bboreham** [prometheus/client_golang#824]
Default is here:
https://github.com/prometheus/client_golang/blob/8b73bd904c6b7929b7dcaefea4fbcc9c7a439449/prometheus/push/push.go#L112

Protos declared to be no longer supported here: https://github.com/prometheus/docs/blob/33f891f6b8392aead6089bfe388e07b1ee2cde14/content/docs/instrumenting/exposition_formats.md#exposition-formats

**Comment by beorn7** [comment]
The Pushgateway is still following the "old faith" of building everything around the protobuf as the data model. So in fact, the Pushgateway prefers to receive the pushed metrics in protobuf format. Not using it would mean that prometheus/client_golang jumps through hoops to convert protobuf to text format to send it out to the wire. And then the Pushgateway is performing the inverse of all those jumps through hoops to convert it back into protobuf.

Therefore, I'd prefer to keep the default for now. (Also, some users might actually depend on it and will be very surprised if the default changes.) I think the doc comment is already quite clear, and it could be emphasized in weaveworks/prom-aggregation-gateway that it is a custom implementation that requires the text format.

**Comment by bboreham** [comment]
I cannot see how you reconcile this with the statement “As of version 2.0, however, Prometheus no longer supports the Protobuf-based format”.

Maybe add a rider saying it is still the preferred format for certain components?

**Comment by beorn7** [comment]
Yeah, the distinction between "Prometheus the ecosystem" and "Prometheus the metrics collection server" is not always clear.

The version 2.0 kind of gives it away that this sentence refers to the server. The ecosystem as a whole isn't versioned. (o:

Perhaps that paragraph can be updated to make clear it refers to scraping by the Prometheus server.
