### ISSUE TITLE
how to set buckets adaptively?

### ISSUE THREAD

**Issue by bluesky1024** [prometheus/client_golang#827]
version:  tag 1.9.0 /2020-12-17
as the [example/random](https://github.com/prometheus/client_golang/blob/85aa957f631d2e252dade63ca7138946197a772c/examples/random/main.go#L59) shows, the Buckets of Histogram is pre set before the service running.
```go
	rpcDurationsHistogram = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "rpc_durations_histogram_seconds",
		Help:    "RPC latency distributions.",
		Buckets: prometheus.LinearBuckets(*normMean-5**normDomain, .5**normDomain, 20),
	})
```
However, the distribution of histogram is unknown in most scenarios.

the default buckets is given as [[]float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}](https://github.com/prometheus/client_golang/blob/85aa957f631d2e252dade63ca7138946197a772c/prometheus/histogram.go#L189), but the distribution is not so reasonable.

So is there any possibility that we could use prometheus report without pre setting of Buckets?
 (maybe there are some related api i ignored... and where could i find related wiki?)

**Comment by bwplotka** [comment]
Hello 👋🏽 

At the current moment, buckets are pre-set for the process and you cannot change them after metric creation. Of course you can create a new metric and replace the old one, but this will break the histogram time series continuation and thus it will be hard to query/understand. However, doing this during initial adjustments for buckets is totally ok. The aim is to have buckets stable over time. 

This is a known limitation of histograms. There is on-going work to improve this, but currently in this case you can use [`Summary`](https://prometheus.io/docs/practices/histograms/) instead. Also, I believe you can use the prometheus user mailing list for these kinds of questions. I don't think it's client_golang bug, so closing. 🤗 Hope I helped.

**Comment by bluesky1024** [comment]
thanks for your reply

**Comment by beorn7** [comment]
Shameless plug: You could watch my "histogram trilogy of talks":

1. https://fosdem.org/2020/schedule/event/histograms/
2. https://promcon.io/2019-munich/talks/prometheus-histograms-past-present-and-future/
3. https://www.youtube.com/watch?v=HG7uzON-IDM
