### ISSUE TITLE
Circular dependency with prometheus/prometheus

### ISSUE THREAD

**Issue by TheTincho** [prometheus/client_golang#84]
Hi,

While working on Debian packages for Prometheus, I've found a circular dependency between prometheus and client_golang. Prometheus depends on the whole client_golang, while the latter depends on utility/test/error.go from prometheus for some tests.

**Comment by beorn7** [comment]
Sounds weird. I'll look into it ASAP.

**Comment by beorn7** [comment]
https://github.com/prometheus/client_golang/pull/83 fixes this, incidentally... :)

**Comment by juliusv** [comment]
See https://github.com/prometheus/client_golang/pull/83, which
coincidentally resolves this (see PR description).

**Comment by beorn7** [comment]
Once more, Julius and I are concurrent goroutines doing the same thing... ;)

**Comment by juliusv** [comment]
Same-second reply :)

**Comment by TheTincho** [comment]
Hah, thanks guys for the quick reply!
