### ISSUE TITLE
Graph annotations

### ISSUE THREAD

**Issue by Javirln** [prometheus/client_golang#840]
Hello all,

I was wondering if the creation of annotations was something possible through the client API.

![Screenshot 2021-02-23 at 16 44 40](https://user-images.githubusercontent.com/4128269/108868363-6e6d6600-75f6-11eb-9503-120603e23b90.png)

Thank you so much!

**Comment by beorn7** [comment]
The HTTP client in this repo is for the [Prometheus HTTP API](https://prometheus.io/docs/prometheus/latest/querying/api/). I don't see how that's related to Grafana annotations.

**Comment by Javirln** [comment]
@beorn7 Totally right, I mixed it and realised after submitting the issue. I'll close the issue, thanks!
