### ISSUE TITLE
Using push library to push to InfluxDB 1.8 (or other Prometheus remote write APIs besides the pushgateway)

### ISSUE THREAD

**Issue by epsteina16** [prometheus/client_golang#852]
Does the push library support writing to remote write APIs besides the pushgateway?

I am interested in using it to write to InfluxDB 1.8, but without any advanced configuration I get a 404 error "database not found "prometheus/metrics/job/test". It looks like the push code appends the job and metrics info to the POST request URL making it look like http://localhost:8086/api/v1/prom/write?db=prometheus/metrics/job/test when the database name is just prometheus.

Does anyone have experience configuring it to use the API correctly? Is it necessary to implement a custom HTTPDoer for this?

**Comment by beorn7** [comment]
The InfluxDB `/api/v1/prom/write` endpoint receives the Prometheus remote write protocol. That's very different from anything dealt with here in prometheus/client_golang. This repo is about exposition. The `push` package is about pushing metrics specifically to [the Prometheus Pushgateway](https://github.com/prometheus/pushgateway).

The Prometheus remote write protocol is used by the Prometheus server itself to send metrics it has scraped to remote databases (like InfluxDB). If you have questions about Prometheus remote write, I recommend to ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
