### ISSUE TITLE
Build fails go_commector.go:388:15

### ISSUE THREAD

**Issue by PatMis16** [prometheus/client_golang#858]
I am trying to build a project of mine with an action on gitub. The Project github.com/PatMis16/promalert2bmctsom uses the prometheus client. The last line of the build which fails is:

 ../../prometheus/client_golang/prometheus/go_collector.go:388:15: undefined: debug.ReadBuildInfo

I am not 100% sure if this causes the build to fail. However, it is the last line and a point to start.

**Comment by beorn7** [comment]
debug.ReadBuildInfo was introduced to Go in Go 1.12. I assume you are using an earlier Go version.

Note that prometheus/client_golang requires at least Go 1.13.

**Comment by PatMis16** [comment]
Got it. My build workglow used Go 1.11. Changed it, now it works.
Thank you very much!
