### ISSUE TITLE
Simplify sanitisation code in instrument_server.go

### ISSUE THREAD

**Issue by zserge** [prometheus/client_golang#869]
Not sure if I'm missing the big picture, but some sanitization methods in `instrument_server.go` look redundant:

* https://github.com/prometheus/client_golang/blob/a7515ca7c9c6388a5ab84ea336faef795bbf866f/prometheus/promhttp/instrument_server.go#L333-L354
* https://github.com/prometheus/client_golang/blob/a7515ca7c9c6388a5ab84ea336faef795bbf866f/prometheus/promhttp/instrument_server.go#L359-L458

Maybe these could be simplified as:

```go
func sanitizeMethod(m string) string {
	return strings.ToLower(m)
}

func sanitizeCode(s int) string {
	if s == 0 {
		return "200"
	}
	return strconv.Itoa(s)
}
```

I doubt that switch/case over particular string constants would bring any noticeable performance benefits than calling `ToLower` on any input string (same about `Itoa`).

**Comment by beorn7** [comment]
Those methods are potentially in a very hot path. Your suggested changes cause allocations, which may be problematic (even if the runtime alone doesn't look like it). See also discussion for #813.
