### ISSUE TITLE
Release v1.11.0

### ISSUE THREAD

**Issue by howardjohn** [prometheus/client_golang#876]
Since the changes to drop github.com/go-kit/kit have been merged, it would be great to tag a new release to encourage downstream importers to pick up the new version. Without doing this, the change is not effective since *all* dependencies need to be updated to now import the large dependency to have any impact.

See https://github.com/prometheus/common/issues/255 for context.

Note: the PR to drop the dependency is already merged, I was just hoping to tag the release as tagged releases are *much* more likely to be adopted.

**Comment by kakkoyun** [comment]
@howardjohn Thanks for reaching out. I'm going to prioritise this and try to release it ASAP.

**Comment by sagikazarmark** [comment]
The circular dependency between client_golang and common is a bit unfortunate: in order to truly clean up the transitive dependency mess, client_golang neeeds to be released, common updated and released, then client_golang updated and released.
