### ISSUE TITLE
.With, or .WithLabels metric throws a nil pointer if a metric isn't registered, when it should error

### ISSUE THREAD

**Issue by AskAlice** [prometheus/client_golang#887]
Our codebase is on 1.3.0, but this still appears to be an issue with the latest release just by looking at the code.

If I were to simply run

```golang
MyMetric.GetMetricWith(prometheus.Labels{
		"label1": var1,
		"label2": var2}).Inc()
```

Before registering my metrics, ie: in a test

Then I would be greeted with a wonderful nil pointer exception

```shell
testing.tRunner.func1.2(0x94fec0, 0xd656d0)
        /usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000082a80)
        /usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x94fec0, 0xd656d0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/prometheus/client_golang/prometheus.(*CounterVec).GetMetricWith(...)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.3.0/prometheus/counter.go:192
github.com/prometheus/client_golang/prometheus.(*CounterVec).With(0x0, 0xc0000aac60, 0x9d8361, 0x7)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.3.0/prometheus/counter.go:215 +0x26
myapp/mypackage.myFunction(0x0)
        /src/myfile.go:123 +0x123
```

I wish it would return an error rather than throwing a panic, because it would be easier to write tests.

**Comment by beorn7** [comment]
Your example code above would not compile because `GetMetricWith` returns `(metric, error)`.

It _would_ compile if you used `With` or `WithLabels` instead. But those functions are meant to panic if an error occurs. If you want to catch the error, you need to use `GetMetricWith` / `GetMetricWithLabels`.
