### ISSUE TITLE
No API to query the metrics?

### ISSUE THREAD

**Issue by jiping-s** [prometheus/client_golang#910]
Hi!

We've been using the library in a project which needs to list metrics and query their values for test mode. It works partially for now with custom metric types and custom registry which duplicates a small part of the library itself, but as we need more and more features I begin to wonder if we're doing it the right way or should we use the library at all, and I'm hoping someone with such experience could help clarify things or suggest which way we should go.

Our needs are quite simple if we see the metric registry as some sort of in-memory database and each metric family a composite object of metrics:
- List metric families in registry, either all of them flattened or in a tree structure organized by Collector(s). NOT *export*.
- Find metric family by name in registry
- List metrics inside a metric family
- Get values from metrics which double as internal counters.

None of them seems to be possible or straightforward with the current API. 

Thanks!

**Comment by beorn7** [comment]
The instrumentation library is deliberately lightweight and does not intend to implement an in-memory database. (It already does quite a few things to ensure consistency, but we would really like to leave it there. There are already alternative instrumentation libraries in Go out there by developers for which this one here appeared too heavy-weight!)

If you do want more sophisticated querying, there is nothing wrong with writing your own code for it (and perhaps even open-source it?). But I would recommend to keep it out of this instrumentation library (which is already quite overwhelming for the beginner). You could still make use of this library in your code, either by doing the instrumentation normally and then internally call `Gather` and funnel the result into your own custom processing/querying engine. Or you do it the other way round, manage all the metrics on your own, and use `NewConstMetric` and friends to gather them all upon a regular scrape. In both ways, you can benefit from the consistency checks of this library (which would take quite some effort to duplicate correctly in your own code).

**Comment by jiping-s** [comment]
Thanks for the ideas @beorn7!

**Comment by jiping-s** [comment]
I cleaned up our work and extracted it to https://github.com/relex/gotils/tree/master/promexporter/promreg (main front) & https://github.com/relex/gotils/tree/master/promexporter/promext (support types/funcs), in case anyone might be interested.
