### ISSUE TITLE
Some weird panics occur when using prometheus client exporter

### ISSUE THREAD

**Issue by yuyue0225sc** [prometheus/client_golang#915]
I used the prometheus golang client expoerter on a service with more than 10,000 qps to calculate the http interface indicators. I found that the following weird panic occasionally appeared on a few instances. Do you know the reason for this? thanks

1.runtime error: growslice: cap out of range
panic.go:969 +0x1b9\ngithub.com/beorn7/perks/quantile.(*Stream).insert(...)\n    /home/ferry/go/pkg/mod/github.com/beorn7/perks@v1.0.1/quantile/stream.go:142\ngithub.com/beorn7/perks/quantile.(*Stream).Insert(0xc008322030, 0x4014000000000000)\n    /home/ferry/go/pkg/mod/github.com/beorn7/perks@v1.0.1/quantile/stream.go:138 +0xb0\ngithub.com/prometheus/client_golang/prometheus.(*summary).flushColdBuf(0xc0093ba200)\n    /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/summary.go:372 +0x5a\ngithub.com/prometheus/client_golang/prometheus.(*summary).Write(0xc0093ba200, 0xc00c8c8930, 0x3, 0xc008e934a2)\n    /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/summary.go:308 +0x145\ngithub.com/prometheus/client_golang/prometheus.processMetric(0xf9a140, 0xc0093ba200, 0xc008e93650, 0xc008e93680, 0x0, 0x0, 0x0)\n    /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:598 +0xa2\ngithub.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc00071a190, 0x0, 0x0, 0x0, 0x0, 0x0)\n    /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:492 

2.unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x95e051]
goroutine 1095620 [running]:
runtime.throw(0xe83b67, 0x5)
/go1-15-linux-amd64/src/runtime/signal_unix.go:749 +0x405 fp=0xc0104732e8 sp=0xc0104732b8 pc=0x452ca5
github.com/prometheus/client_golang/prometheus.processMetric(0xf9a000, 0xc008cc8180, 0xc010473650, 0xc010473680, 0x0, 0x0, 0x0)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:594 +0x51 fp=0xc010473410 sp=0xc0104732e8 pc=0x95e051
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000180b90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:492 +0x8ca fp=0xc010473930 sp=0xc010473410 pc=0x95d90a

3.unexpected fault address 0x0
go-env/go1-15-linux-amd64/src/runtime/signal_unix.go:749 +0x405 fp=0xc010565138 sp=0xc010565108 pc=0x452ca5
github.com/prometheus/client_model/go.(*LabelPair).GetName(...)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_model@v0.2.0/go/metrics.pb.go:107
github.com/prometheus/client_golang/prometheus.checkMetricConsistency(0xc012644af0, 0xc0108f7ce0, 0xc010565680, 0x1, 0xc0105658c0)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:854 +0x1e9 fp=0xc0105652e8 sp=0xc010565138 pc=0x95fb09
github.com/prometheus/client_golang/prometheus.processMetric(0xf9a000, 0xc00cf0eba0, 0xc010565650, 0xc010565680, 0x0, 0x0, 0x0)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:673 +0x3cc fp=0xc010565410 sp=0xc0105652e8 pc=0x95e3cc
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000514a00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:492 +0x8ca fp=0xc010565930 sp=0xc010565410 pc=0x95d90a

golang version is 1.15.0
 
client_golang version is 1.11.0

**Comment by bwplotka** [comment]
Thanks! Sounds like something to investigate.

**Comment by shivamrustagi** [comment]
@yuyue0225sc @bwplotka was this fixed?

**Comment by shivamrustagi** [comment]
`2.unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x95e051]
goroutine 1095620 [running]:
runtime.throw(0xe83b67, 0x5)
/go1-15-linux-amd64/src/runtime/signal_unix.go:749 +0x405 fp=0xc0104732e8 sp=0xc0104732b8 pc=0x452ca5
github.com/prometheus/client_golang/prometheus.processMetric(0xf9a000, 0xc008cc8180, 0xc010473650, 0xc010473680, 0x0, 0x0, 0x0)
/home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:594 +0x51 fp=0xc010473410 sp=0xc0104732e8 pc=0x95e051
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000180b90, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/ferry/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:492 +0x8ca fp=0xc010473930 sp=0xc010473410 pc=0x95d90a`

getting panic with similar stack trace

**Comment by ekostogorov** [comment]
Faced the same issue with

github.com/prometheus/client_golang@v1.16.0
github.com/prometheus/client_model@v0.4.0

```
http: panic serving 127.0.0.6:0000: runtime error: invalid memory address or nil pointer dereference
goroutine 2711083 [running]:
net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1258ea0?, 0x2a2edb0?})
    /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/prometheus/client_model/go.(*LabelPair).GetName(...)
    /src/vendor/github.com/prometheus/client_model/go/metrics.pb.go:154
github.com/prometheus/client_golang/prometheus.checkMetricConsistency(0x1245540?, 0xc001da49a0, 0x14fa096?)
    /src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:889 +0x29b
github.com/prometheus/client_golang/prometheus.processMetric({0x1e7ddb8, 0xc001bfd2b0}, 0x2?, 0x0?, 0x0)
    /src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:707 +0x877
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0x2a63d00)
    /src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:501 +0x819
github.com/prometheus/client_golang/prometheus.(*noTransactionGatherer).Gather(0x2a?)
    /src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:1073 +0x1b
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1({0x7fdfa6d46dc0, 0xc001bc06e0}, 0xc001a9a200)
    /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:140 +0x2b0
net/http.HandlerFunc.ServeHTTP(0x1e6c2e0?, {0x7fdfa6d46dc0?, 0xc001bc06e0?}, 0xc0027a3a70?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentMetricHandler.InstrumentHandlerInFlight.func1({0x7fdfa6d46dc0, 0xc001bc06e0}, 0x1e80d00?)
    /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:60 +0xcb
net/http.HandlerFunc.ServeHTTP(0x1e80d38?, {0x7fdfa6d46dc0?, 0xc001bc06e0?}, 0xc000010ac8?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1e80d38?, 0xc001a73ce0?}, 0xc001a9a200)
    /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:147 +0xb6
net/http.HandlerFunc.ServeHTTP(0x10?, {0x1e80d38?, 0xc001a73ce0?}, 0x2a64060?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.HandlerFunc.ServeHTTP(0x4466e0?, {0x1e80d38?, 0xc001a73ce0?}, 0x6e5eba?)
    /usr/local/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x2a97580?, {0x1e80d38, 0xc001a73ce0}, 0xc001a9a200)
    /usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc0027a3950?}, {0x1e80d38?, 0xc001a73ce0?}, 0x6?)
    /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc002578120, {0x1e833e0, 0xc000a2d8c0})
    /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 418
    /usr/local/go/src/net/http/server.go:3086 +0x5cb
```
