### ISSUE TITLE
example: flag variable used before parse - can't adjust bucket start, width using flag arguments

### ISSUE THREAD

**Issue by ii64** [prometheus/client_golang#933]
flag defined here
https://github.com/prometheus/client_golang/blob/679eb0d315d3bad8963927751537034476a52e25/examples/random/main.go
#L32-L38

used before calling `flag.Parse()` (derefencing from pointer), default value all the time
https://github.com/prometheus/client_golang/blob/679eb0d315d3bad8963927751537034476a52e25/examples/random/main.go#L50-L63

calling `flag.Parse()` (updates the flag value)
https://github.com/prometheus/client_golang/blob/679eb0d315d3bad8963927751537034476a52e25/examples/random/main.go#L70-L73

**Comment by beorn7** [comment]
Good catch. I simply moved everything into main() in #935.
