### ISSUE TITLE
New release with updated deps?

### ISSUE THREAD

**Issue by jeffwidman** [prometheus/client_golang#946]
Could you cut a new release? 

I noticed some changes were made to the deps that fixes a go 1.17 issue (#913), but it hasn't been released yet.

This may be blocked by #911

**Comment by kakkoyun** [comment]
I will check all the open PRs and see if we can cut a release this week.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/105142 depends on it as well.

**Comment by pacoxu** [comment]
Any update here? Kindly ping. 😄

**Comment by kakkoyun** [comment]
Sorry, I've dropped the ball on this. I'm back after a break. I'll look into this. Thanks for the ping.

**Comment by kakkoyun** [comment]
I want to have at least https://github.com/prometheus/client_golang/pull/955 merged. It's closed, please stay tuned.

**Comment by pacoxu** [comment]
> I want to have at least #955 merged. It's closed, please stay tuned.
@kakkoyun  #955 is merged.
Any plan for the release? 😄 Or there's another blocker.

**Comment by kakkoyun** [comment]
No, we have handled everything. We will release soon.
