### ISSUE TITLE
Add memstats to go_collector.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#96]

**Comment by grobie** [comment]
:+1: I was just missing them yesterday.

**Comment by KevinPike** [comment]
Hey @beorn7 , any update on this?

**Comment by beorn7** [comment]
Still on my plate.

I'm more concerned at the moment with the general refactoring of `client_golang`. This feature is relatively independent from the refactoring, so it could in principle be done by anybody. Hopefully I'll get to it in the next weeks if nobody else is...
