### ISSUE TITLE
Add `ScrapeAndCompare` utility

### ISSUE THREAD

**Issue by bwplotka** [prometheus/client_golang#993]
See https://github.com/kubernetes/kubernetes/pull/108277

Ideally we have method for comparing expected output with HTTP scrape, or at least body response form scrape.

Optionally:
* We could also learn from utils https://github.com/kubernetes/component-base/blob/master/metrics/testutil/testutil.go#L48 and add some of them to client_golang

cc @kakkoyun @saswatamcode

**Comment by sazary** [comment]
@bwplotka i think we can resolve this now
