### ISSUE TITLE
Invalid le label value on go_gc_pauses_seconds_total_bucket

### ISSUE THREAD

**Issue by prymitive** [prometheus/client_golang#995]
Reporting https://github.com/prometheus/client_golang/issues/967#issuecomment-1028850776 as a separate issue so it won't get lost

`go_gc_pauses_seconds_total_bucket` ends up with a negative `le` bucket and a `NaN` value for `go_gc_pauses_seconds_total_sum`
```
# HELP go_gc_pauses_seconds_total Distribution individual GC-related stop-the-world pause latencies.
# TYPE go_gc_pauses_seconds_total histogram
go_gc_pauses_seconds_total_bucket{le="-5e-324"} 0
go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-10"} 0
go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-09"} 0
go_gc_pauses_seconds_total_bucket{le="1.2799999999999998e-07"} 0
go_gc_pauses_seconds_total_bucket{le="1.2799999999999998e-06"} 0
go_gc_pauses_seconds_total_bucket{le="1.6383999999999998e-05"} 0
go_gc_pauses_seconds_total_bucket{le="0.00016383999999999998"} 3307
go_gc_pauses_seconds_total_bucket{le="0.0020971519999999997"} 6712
go_gc_pauses_seconds_total_bucket{le="0.020971519999999997"} 6809
go_gc_pauses_seconds_total_bucket{le="0.26843545599999996"} 6812
go_gc_pauses_seconds_total_bucket{le="+Inf"} 6812
go_gc_pauses_seconds_total_sum NaN
go_gc_pauses_seconds_total_count 6812
```

**Comment by kakkoyun** [comment]
I guess there's a legitimate answer to that in the same thread by @mknyszek  https://github.com/prometheus/client_golang/issues/967#issuecomment-1029260834

That being said, we could consider an absorbing the negative values here.

**Comment by fly3366** [comment]
Calculate quantile need bucket include Inf, but main branch has exclude Inf. So quantile return NaN. if someone need a patch, I will pr.

**Comment by kakkoyun** [comment]
@fly3366 Feel free to contribute. The contributions are always welcome :hugs:  Please note we have reverted new enabling new collector by default and this is a bug in that. See #1033. There are several other issues we need to take care of for the new collector, so again help is very much appriciated.

**Comment by kakkoyun** [comment]
Fixed with https://github.com/prometheus/client_golang/pull/1049
