### ISSUE TITLE
Allow passing timeout parameter in Prometheus queries

### ISSUE THREAD

**Issue by prymitive** [prometheus/client_golang#999]
Prometheus HTTP API allows to pass `timeout` parameter for queries: https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries but API doesn't allow to pass it.
One easy way would be to add a new parameter to Query and QueryRange but that would be incompatible.
Another way could to to check if passed context has a deadline and set a timeout smaller than that deadline, like:

```
func (h *httpAPI) Query(ctx context.Context, query string, ts time.Time) (model.Value, Warnings, error) {
	u := h.client.URL(epQuery, nil)
	q := u.Query()

	q.Set("query", query)
	if !ts.IsZero() {
		q.Set("time", formatTime(ts))
	}
	if deadline, ok := ctx.Deadline(); ok {
		q.Set("timeout", fmt.Sprintf("%ds", int(time.Until(deadline).Truncate(time.Millisecond*500).Seconds())))
	}
[...]
```

but smaller by what duration? So one way or another extra information is needed I think.

**Comment by kakkoyun** [comment]
I would rather prefer to use an explicit parameter to the function, since it's already part of the HTTP API.

Also as a side note, we can consider using functional optional parameters for the httpAPI since we don't provide stability guarantees for this package we have the liberty to change things to make it more elegant.

**Comment by JosephWoodward** [comment]
> I would rather prefer to use an explicit parameter to the function, since it's already part of the HTTP API.

I agree, seems like the clearest, least surprising approach from a client usability perspective. I also agree that functional options pattern for these types of optional parameters seems a reasonable approach (is the pattern used anywhere else in the client's public API?)

I'm happy to pick this one up.

**Comment by kakkoyun** [comment]
@JosephWoodward Not right now. Client for HTTP API is the best place to start introducing it. It still in alpha stage.

Please go ahead.

**Comment by JosephWoodward** [comment]
I've started on an initial draft PR [here](https://github.com/prometheus/client_golang/pull/1014/files)
